### ISSUE TITLE
TipsManager Milestone updating: IndexOutOfBoundsException

### ISSUE THREAD

**Issue by alfredch** [iotaledger/iri#11]
17:57:21.027 [main] INFO com.iota.iri.IRI - Welcome to IRI 1.1.1
17:57:21.682 [pool-1-thread-2] INFO com.iota.iri.service.Node - Spawning Broadcaster Thread
17:57:21.682 [pool-1-thread-1] INFO com.iota.iri.service.Node - Spawing Receiver Thread
17:57:21.706 [pool-1-thread-3] INFO com.iota.iri.service.Node - Spawning Tips Requester Thread
17:57:21.767 [main] DEBUG org.jboss.logging - Logging Provider: org.jboss.logging.Slf4jLoggerProvider
17:57:21.787 [main] INFO org.xnio - XNIO version 3.3.1.Final
17:57:21.873 [main] INFO org.xnio.nio - XNIO NIO Implementation Version 3.3.1.Final
17:57:21.959 [XNIO-1 I/O-3] DEBUG org.xnio.nio - Started channel thread 'XNIO-1 I/O-3', selector sun.nio.ch.WindowsSelectorImpl@42ba10bb
17:57:21.959 [XNIO-1 I/O-1] DEBUG org.xnio.nio - Started channel thread 'XNIO-1 I/O-1', selector sun.nio.ch.WindowsSelectorImpl@6da87479
17:57:21.959 [XNIO-1 I/O-4] DEBUG org.xnio.nio - Started channel thread 'XNIO-1 I/O-4', selector sun.nio.ch.WindowsSelectorImpl@662a366
17:57:21.960 [XNIO-1 I/O-2] DEBUG org.xnio.nio - Started channel thread 'XNIO-1 I/O-2', selector sun.nio.ch.WindowsSelectorImpl@d24e5c7
17:57:21.960 [XNIO-1 I/O-7] DEBUG org.xnio.nio - Started channel thread 'XNIO-1 I/O-7', selector sun.nio.ch.WindowsSelectorImpl@4f25503b
17:57:21.960 [XNIO-1 I/O-5] DEBUG org.xnio.nio - Started channel thread 'XNIO-1 I/O-5', selector sun.nio.ch.WindowsSelectorImpl@49a2fda5
17:57:21.982 [XNIO-1 I/O-6] DEBUG org.xnio.nio - Started channel thread 'XNIO-1 I/O-6', selector sun.nio.ch.WindowsSelectorImpl@3a4eacfa
17:57:21.982 [XNIO-1 I/O-8] DEBUG org.xnio.nio - Started channel thread 'XNIO-1 I/O-8', selector sun.nio.ch.WindowsSelectorImpl@5b543aaf
17:57:22.449 [Latest Milestone Tracker] ERROR com.iota.iri.service.TipsManager - Error during TipsManager Milestone updating
java.lang.IndexOutOfBoundsException: -8192
        at java.nio.DirectByteBuffer.get(Unknown Source)
        at com.iota.iri.service.storage.Storage.setAnalyzedTransactionFlag(Storage.java:145)
        at com.iota.iri.Milestone.updateLatestSolidSubtangleMilestone(Milestone.java:113)
        at com.iota.iri.service.TipsManager.lambda$launch$0(TipsManager.java:44)
        at java.lang.Thread.run(Unknown Source)

**Comment by alfredch** [comment]
It crashed with the same error while trying to sync with network.
Then I restarted and that is what happened.

**Comment by mettenian** [comment]
same error here with 1.1.2:

13:58:47.951 [Latest Milestone Tracker] ERROR com.iota.iri.service.TipsManager - Error during TipsManager Milestone updating
java.lang.ArrayIndexOutOfBoundsException: 85719776
        at com.iota.iri.service.storage.StorageTransactions.loadTransaction(StorageTransactions.java:141)
        at com.iota.iri.Bundle.loadTransactionsFromTangle(Bundle.java:130)
        at com.iota.iri.Bundle.<init>(Bundle.java:33)
        at com.iota.iri.Milestone.updateLatestMilestone(Milestone.java:47)
        at com.iota.iri.service.TipsManager.lambda$init$0(TipsManager.java:42)
        at java.lang.Thread.run(Unknown Source)

**Comment by mettenian** [comment]
14:34:25.618 [Latest Milestone Tracker] ERROR com.iota.iri.service.TipsManager - Error during TipsManager Milestone updating
java.lang.ArrayIndexOutOfBoundsException: 681768137
        at com.iota.iri.service.storage.StorageAddresses.addressPointer(StorageAddresses.java:80)
        at com.iota.iri.service.storage.StorageAddresses.addressesOf(StorageAddresses.java:257)
        at com.iota.iri.Milestone.updateLatestMilestone(Milestone.java:37)
        at com.iota.iri.service.TipsManager.lambda$init$0(TipsManager.java:42)
        at java.lang.Thread.run(Unknown Source)

**Comment by pinpong** [comment]
[Latest Milestone Tracker] ERROR com.iota.iri.service.TipsManager - Error during TipsManager Milestone updating
java.lang.ArrayIndexOutOfBoundsException: null
[Latest Milestone Tracker] ERROR com.iota.iri.service.TipsManager - Error during TipsManager Milestone updating
java.lang.ArrayIndexOutOfBoundsException: 568748477
at com.iota.iri.service.storage.StorageAddresses.addressPointer(StorageAddresses.java:80)
at com.iota.iri.service.storage.StorageAddresses.addressesOf(StorageAddresses.java:257)
at com.iota.iri.Milestone.updateLatestMilestone(Milestone.java:37)
at com.iota.iri.service.TipsManager.lambda$init$0(TipsManager.java:42)
at java.lang.Thread.run(Thread.java:745)

**Comment by davassi** [comment]
this should be fixed by now in the dev branch.
