### ISSUE TITLE
getNeighbors Error while syncing

### ISSUE THREAD

**Issue by jayjoe13** [iotaledger/iri#112]
Testnet / IRI-1.1.3.8 
Before and after this error the syncing process continued normal. 

`[XNIO-1 task-12] ERROR com.iota.iri.service.API - API Exception:
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 16 path $.
        at com.google.gson.Gson.fromJson(Gson.java:902) ~[iri-1.1.3.8.jar:na]
        at com.google.gson.Gson.fromJson(Gson.java:852) ~[iri-1.1.3.8.jar:na]
        at com.google.gson.Gson.fromJson(Gson.java:801) ~[iri-1.1.3.8.jar:na]
        at com.google.gson.Gson.fromJson(Gson.java:773) ~[iri-1.1.3.8.jar:na]
        at com.iota.iri.service.API.process(API.java:149) [iri-1.1.3.8.jar:na]
        at com.iota.iri.service.API.processRequest(API.java:141) [iri-1.1.3.8.jar:na]
        at com.iota.iri.service.API.access$000(API.java:89) [iri-1.1.3.8.jar:na]
        at com.iota.iri.service.API$1.handleRequest(API.java:129) [iri-1.1.3.8.jar:na]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:208) [iri-1.1.3.8.jar:na]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809) [iri-1.1.3.8.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 16 path $.
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[iri-1.1.3.8.jar:na]
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491) ~[iri-1.1.3.8.jar:na]
        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414) ~[iri-1.1.3.8.jar:na]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:184) ~[iri-1.1.3.8.jar:na]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[iri-1.1.3.8.jar:na]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[iri-1.1.3.8.jar:na]
        ... 12 common frames omitted`

**Comment by alfredch** [comment]
Most probably a syntax error in the getNeighbors request. IRI cannot parse the JSON request. Nothing related to IRI core functionality.
