### ISSUE TITLE
NullPointer when shutting down

### ISSUE THREAD

**Issue by pinpong** [iotaledger/iri#117]
```[Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...
[Shutdown Hook] ERROR com.iota.iri.IRI - Exception occurred shutting down IOTA node: 
java.lang.NullPointerException: null
	at com.iota.iri.service.TipsManager.shutdown(TipsManager.java:63) ~[iri-1.1.3.7.jar:na]
	at com.iota.iri.IRI.lambda$shutdownHook$0(IRI.java:253) ~[iri-1.1.3.7.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_91]

**Comment by alfredch** [comment]
A timing problem in the shutdown sequence. Will be fixed in next release.
