### ISSUE TITLE
iri stopped responding | 1.1.3.9 testnet

### ISSUE THREAD

**Issue by mettenian** [iotaledger/iri#119]
05/19 09:47:38.520 [XNIO-1 I/O-1] ERROR com.iota.iri.service.API - Error writing response
java.nio.channels.ClosedChannelException: null
        at io.undertow.conduits.AbstractFixedLengthStreamSinkConduit.write(AbstractFixedLengthStreamSinkConduit.java:96) ~[iri-1.1.3.9.jar:na]
        at org.xnio.conduits.ConduitStreamSinkChannel.write(ConduitStreamSinkChannel.java:150) ~[iri-1.1.3.9.jar:na]
        at io.undertow.channels.DetachableStreamSinkChannel.write(DetachableStreamSinkChannel.java:240) ~[iri-1.1.3.9.jar:na]
        at io.undertow.server.HttpServerExchange$WriteDispatchChannel.write(HttpServerExchange.java:2039) ~[iri-1.1.3.9.jar:na]
        at com.iota.iri.service.API.lambda$sendResponse$7(API.java:837) ~[iri-1.1.3.9.jar:na]
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[iri-1.1.3.9.jar:na]
        at io.undertow.channels.DetachableStreamSinkChannel$SetterDelegatingListener.handleEvent(DetachableStreamSinkChannel.java:285) ~[iri-1.1.3.9.jar:na]
        at io.undertow.channels.DetachableStreamSinkChannel$SetterDelegatingListener.handleEvent(DetachableStreamSinkChannel.java:272) ~[iri-1.1.3.9.jar:na]
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[iri-1.1.3.9.jar:na]
        at org.xnio.conduits.WriteReadyHandler$ChannelListenerHandler.writeReady(WriteReadyHandler.java:65) ~[iri-1.1.3.9.jar:na]
        at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:93) ~[iri-1.1.3.9.jar:na]
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:559) ~[iri-1.1.3.9.jar:na]

**Comment by Nyrsta** [comment]
I had the same issue on my node.
I was using nostagia, making transfers, generating addresses at that moment.
The latest transfer wasn't successfull due to not have enough confirmed balance. (don't know if related)
Later I discovered this message was continuesly scrolling in my node log.
This until I stopped IRI manually which worked as normal.

At that moment the node was running 18hours without any issues.
And the node was spamming.

05/19 12:05:16.826 [XNIO-1 I/O-1] ERROR com.iota.iri.service.API - Error writing response
java.nio.channels.ClosedChannelException: null
        at io.undertow.conduits.AbstractFixedLengthStreamSinkConduit.write(AbstractFixedLengthStreamSinkConduit.java:96) ~[iri-1.1.3.9.jar:na]
        at org.xnio.conduits.ConduitStreamSinkChannel.write(ConduitStreamSinkChannel.java:150) ~[iri-1.1.3.9.jar:na]
        at io.undertow.channels.DetachableStreamSinkChannel.write(DetachableStreamSinkChannel.java:240) ~[iri-1.1.3.9.jar:na]
        at io.undertow.server.HttpServerExchange$WriteDispatchChannel.write(HttpServerExchange.java:2039) ~[iri-1.1.3.9.jar:na]
        at com.iota.iri.service.API.lambda$sendResponse$7(API.java:789) ~[iri-1.1.3.9.jar:na]
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[iri-1.1.3.9.jar:na]
        at io.undertow.channels.DetachableStreamSinkChannel$SetterDelegatingListener.handleEvent(DetachableStreamSinkChannel.java:285) ~[iri-1.1.3.9.jar:na]
        at io.undertow.channels.DetachableStreamSinkChannel$SetterDelegatingListener.handleEvent(DetachableStreamSinkChannel.java:272) ~[iri-1.1.3.9.jar:na]
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[iri-1.1.3.9.jar:na]
        at org.xnio.conduits.WriteReadyHandler$ChannelListenerHandler.writeReady(WriteReadyHandler.java:65) ~[iri-1.1.3.9.jar:na]
        at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:93) ~[iri-1.1.3.9.jar:na]
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:559) ~[iri-1.1.3.9.jar:na]

**Comment by alfredch** [comment]
The origin of that error is a situation where the connection from a web-client to the IRI web server got lost (network reset, client deliberately closed, client exception).  Normally, IRI detects the loss of a connection only once it has the response ready. That can be minutes after the client made the request (for instance when doing PoW).
An error in IRI caused the responder thread not to terminate in such a situation, but it looped continuously and printed Java stack trace.
NEW:
There is only one error message printed per outstanding request, it has the format:

ERROR com.iota.iri.service.API - Lost connection to client - cannot send response
