### ISSUE TITLE
NullPointer on restart after force closing IRI

### ISSUE THREAD

**Issue by pinpong** [iotaledger/iri#123]
```[main] INFO  com.iota.iri.IRI - Remote access enabled. Binding API socket to listen any interface.
[main] INFO  com.iota.iri.IRI - Welcome to IRI Testnet 1.1.3.10
[main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - Initializing Database Backend... 
[main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - RocksDB persistence provider initialized.
[Solid Milestone Tracker] INFO  com.iota.iri.LedgerValidator - Latest Milestone index: 0
[Solid Milestone Tracker] INFO  com.iota.iri.LedgerValidator - Latest SOLID Milestone index:0
[main] ERROR com.iota.iri.IRI - Exception during IOTA node initialisation: 
java.net.BindException: Address already in use
	at java.net.PlainDatagramSocketImpl.bind0(Native Method) ~[na:1.8.0_91]
	at java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:93) ~[na:1.8.0_91]
	at java.net.DatagramSocket.bind(DatagramSocket.java:392) ~[na:1.8.0_91]
	at java.net.DatagramSocket.<init>(DatagramSocket.java:242) ~[na:1.8.0_91]
	at java.net.DatagramSocket.<init>(DatagramSocket.java:299) ~[na:1.8.0_91]
	at java.net.DatagramSocket.<init>(DatagramSocket.java:271) ~[na:1.8.0_91]
	at com.iota.iri.network.UDPReceiver.init(UDPReceiver.java:49) ~[iri-1.1.3.10.jar:na]
	at com.iota.iri.Iota.init(Iota.java:82) ~[iri-1.1.3.10.jar:na]
	at com.iota.iri.IRI.main(IRI.java:86) ~[iri-1.1.3.10.jar:na]
[Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...
[Shutdown Hook] ERROR com.iota.iri.IRI - Exception occurred shutting down IOTA node: 
java.lang.NullPointerException: null
	at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:76) ~[iri-1.1.3.10.jar:na]
	at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:30) ~[iri-1.1.3.10.jar:na]
	at com.iota.iri.Iota.shutdown(Iota.java:92) ~[iri-1.1.3.10.jar:na]
	at com.iota.iri.IRI.lambda$shutdownHook$0(IRI.java:243) ~[iri-1.1.3.10.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_91]

**Comment by pinpong** [comment]
```
[main] ERROR com.iota.iri.IRI - Exception during IOTA node initialisation: 
org.rocksdb.RocksDBException: lock testnetdb/LOCK: Resource temporarily unavailable
	at org.rocksdb.RocksDB.open(Native Method) ~[iri-1.1.3.10.jar:na]
	at org.rocksdb.RocksDB.open(RocksDB.java:286) ~[iri-1.1.3.10.jar:na]
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.initDB(RocksDBPersistenceProvider.java:492) ~[iri-1.1.3.10.jar:na]
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.init(RocksDBPersistenceProvider.java:71) ~[iri-1.1.3.10.jar:na]
	at com.iota.iri.storage.Tangle.init(Tangle.java:27) ~[iri-1.1.3.10.jar:na]
	at com.iota.iri.Iota.init(Iota.java:77) ~[iri-1.1.3.10.jar:na]
	at com.iota.iri.IRI.main(IRI.java:86) ~[iri-1.1.3.10.jar:na]
[Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...
[Shutdown Hook] ERROR com.iota.iri.IRI - Exception occurred shutting down IOTA node: 
java.lang.NullPointerException: null
	at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:76) ~[iri-1.1.3.10.jar:na]
	at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:30) ~[iri-1.1.3.10.jar:na]
	at com.iota.iri.Iota.shutdown(Iota.java:92) ~[iri-1.1.3.10.jar:na]
	at com.iota.iri.IRI.lambda$shutdownHook$0(IRI.java:243) ~[iri-1.1.3.10.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_91]

**Comment by paulhandy** [comment]
You must delete the db/LOCK file if you force-kill it.
