### ISSUE TITLE
IllegalArgumentException: hostname can't be null

### ISSUE THREAD

**Issue by pinpong** [iotaledger/iri#127]
$ java -jar iri-1.1.3.10.jar -p 14777 --testnet -n 'udp://14.14.14.14:14777 tcp://14:14:14:14:15777' --remote --remote-limit-api 'attachToTangle, addNeighbors, removeNeighbors'
```
[main] INFO  com.iota.iri.IRI - Remote access enabled. Binding API socket to listen any interface.
[main] INFO  com.iota.iri.IRI - Welcome to IRI Testnet 1.1.3.10
[main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - Initializing Database Backend... 
[main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - RocksDB persistence provider initialized.
[Solid Milestone Tracker] INFO  com.iota.iri.LedgerValidator - Latest Milestone index: 0
[Solid Milestone Tracker] INFO  com.iota.iri.LedgerValidator - Latest SOLID Milestone index:0
[main] INFO  com.iota.iri.network.UDPReceiver - UDP replicator is accepting connections on udp port 14600
[UDP receiving thread] INFO  com.iota.iri.network.UDPReceiver - Spawning Receiver Thread
[main] INFO  c.i.i.network.replicator.Replicator - Started ReplicatorSourcePool
[UDP receiving thread] INFO  com.iota.iri.network.UDPReceiver - Receiver thread processed/dropped ratio: 0/0
[Thread-2] INFO  c.i.i.n.r.ReplicatorSourcePool - TCP replicator is accepting connections on tcp port 15600
[main] INFO  com.iota.iri.network.Node - -> Adding neighbor : /14.14.14.14:14600 
[main] ERROR com.iota.iri.IRI - Exception during IOTA node initialisation: 
java.lang.IllegalArgumentException: hostname can't be null
	at java.net.InetSocketAddress.checkHost(InetSocketAddress.java:149) ~[na:1.8.0_91]
	at java.net.InetSocketAddress.<init>(InetSocketAddress.java:216) ~[na:1.8.0_91]
	at com.iota.iri.network.Node.lambda$init$1(Node.java:116) ~[iri-1.1.3.10.jar:na]
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:372) ~[na:1.8.0_91]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_91]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_91]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_91]
	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175) ~[na:1.8.0_91]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:1.8.0_91]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_91]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_91]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:1.8.0_91]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:1.8.0_91]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_91]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[na:1.8.0_91]
	at com.iota.iri.network.Node.init(Node.java:124) ~[iri-1.1.3.10.jar:na]
	at com.iota.iri.Iota.init(Iota.java:84) ~[iri-1.1.3.10.jar:na]
	at com.iota.iri.IRI.main(IRI.java:86) ~[iri-1.1.3.10.jar:na]
[Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...
[Shutdown Hook] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers...

**Comment by vmatekole** [comment]
I have this same issue when running 1.2.4 within Docker image. I have set hostname at runtime with ``` --hostname ``` to no avail.

**Comment by vmatekole** [comment]
Still suffering from this issue — @pinpong did you manage to resolve this?

**Comment by geminoz** [comment]
Could this be just a typo? Look at how you wrote the tcp uri down:

tcp://14:14:14:14:15777'

**Comment by acha-bill** [comment]
Is `tcp://14:14:14:14:15777` a valid url?

**Comment by GalRogozinski** [comment]
@achabill 
If you can't reproduce this issue then please close
