### ISSUE TITLE
Out of memory Exception may occur when syncing a node from db

### ISSUE THREAD

**Issue by GalRogozinski** [iotaledger/iri#1273]
### Bug description
While syncing a node from a fairly recent db, I got an OOM exception

### IRI version
1.6.0

### Hardware Spec
Hetzner CX41

### Steps To Reproduce
1. Just start syncing from a fairly recent db. It doesn't always reproduce

### Errors
```
Exception in thread "Transaction Pruner" java.lang.OutOfMemoryError: Java heap space
01/11 09:11:25.948 [pool-17-thread-2] INFO  c.i.i.n.r.ReplicatorSourceProcessor - Creating sink for 172.29.0.3
01/11 09:11:36.581 [pool-16-thread-2] INFO  c.i.i.n.r.ReplicatorSinkProcessor - Opening sink 172.29.0.3
01/11 09:11:25.959 [pool-17-thread-2] INFO  c.i.i.n.r.ReplicatorSourceProcessor - ----- NETWORK INFO ----- Source 172.29.0.3 is connected
01/11 09:11:36.581 [pool-16-thread-2] INFO  c.i.i.n.r.ReplicatorSinkProcessor - Connecting sink 172.29.0.3
01/11 09:11:44.092 [pool-16-thread-3] INFO  c.i.i.n.r.ReplicatorSinkProcessor - Sink 172.29.0.3 already created
    at java.math.BigInteger.divideAndRemainderKnuth(BigInteger.java:2134)
    at java.math.BigInteger.divideAndRemainder(BigInteger.java:2126)
    at com.iota.iri.crypto.Kerl.tritsFromBigInt(Kerl.java:121)
    at com.iota.iri.crypto.Kerl.squeeze(Kerl.java:72)
    at com.iota.iri.crypto.ISSInPlace.digest(ISSInPlace.java:139)
    at com.iota.iri.BundleValidator.validate(BundleValidator.java:135)
01/11 09:12:41.915 [pool-14-thread-2] INFO  com.iota.iri.network.Node - toProcess = 1 , toBroadcast = 0 , toRequest = 52 , toReply = 0 / totalTransactions = 8217339
01/11 09:13:13.726 [pool-16-thread-2] INFO  c.i.i.n.r.ReplicatorSinkProcessor - ----- NETWORK INFO ----- Sink 172.29.0.3 is connected
01/11 09:13:21.556 [pool-14-thread-2] INFO  com.iota.iri.network.Node - toProcess = 1 , toBroadcast = 0 , toRequest = 52 , toReply = 0 / totalTransactions = 8217339
    at com.iota.iri.service.spentaddresses.impl.SpentAddressesServiceImpl.isBundleValid(SpentAddressesServiceImpl.java:140)
    at com.iota.iri.service.spentaddresses.impl.SpentAddressesServiceImpl.wasTransactionSpentFrom(SpentAddressesServiceImpl.java:132)
    at com.iota.iri.service.spentaddresses.impl.SpentAddressesServiceImpl.wasAddressSpentFrom(SpentAddressesServiceImpl.java:66)
    at com.iota.iri.service.transactionpruning.jobs.MilestonePrunerJob.lambda$getElementsToDelete$2(MilestonePrunerJob.java:275)
    at com.iota.iri.service.transactionpruning.jobs.MilestonePrunerJob$$Lambda$100/410025574.accept(Unknown Source)
01/11 09:13:35.647 [pool-14-thread-2] INFO  com.iota.iri.network.Node - toProcess = 1 , toBroadcast = 0 , toRequest = 52 , toReply = 0 / totalTransactions = 8217339
    at com.iota.iri.utils.dag.DAGHelper.traverseApprovees(DAGHelper.java:183)
    at com.iota.iri.utils.dag.DAGHelper.traverseApprovees(DAGHelper.java:212)
    at com.iota.iri.service.transactionpruning.jobs.MilestonePrunerJob.getElementsToDelete(MilestonePrunerJob.java:271)
    at com.iota.iri.service.transactionpruning.jobs.MilestonePrunerJob.cleanupMilestoneTransactions(MilestonePrunerJob.java:227)
    at com.iota.iri.service.transactionpruning.jobs.MilestonePrunerJob.process(MilestonePrunerJob.java:125)
    at com.iota.iri.service.transactionpruning.async.MilestonePrunerJobQueue.processJobs(MilestonePrunerJobQueue.java:115)
    at com.iota.iri.service.transactionpruning.async.AsyncTransactionPruner.processJobs(AsyncTransactionPruner.java:183)
    at com.iota.iri.service.transactionpruning.async.AsyncTransactionPruner.processJobsThread(AsyncTransactionPruner.java:277)
    at com.iota.iri.service.transactionpruning.async.AsyncTransactionPruner$$Lambda$44/439925336.run(Unknown Source)
01/11 09:17:28.138 [pool-17-thread-2] INFO  c.i.i.n.r.ReplicatorSinkPool - Sink 172.29.0.3 closed
01/11 09:22:23.167 [pool-17-thread-2] INFO  com.iota.iri.network.Neighbor - Source 172.29.0.3 closed
01/11 09:22:23.167 [pool-17-thread-3] INFO  c.i.i.n.r.ReplicatorSourceProcessor - Creating sink for 172.29.0.3
01/11 09:21:08.786 [pool-16-thread-2] INFO  c.i.i.n.r.ReplicatorSinkProcessor - ----- NETWORK INFO ----- Sink 172.29.0.3 got disconnected
01/11 09:22:23.176 [pool-17-thread-3] INFO  c.i.i.n.r.ReplicatorSourceProcessor - ----- NETWORK INFO ----- Source 172.29.0.3 is connected
    at com.iota.iri.utils.thread.ThreadUtils.lambda$spawnThread$0(ThreadUtils.java:76)
    at com.iota.iri.utils.thread.ThreadUtils$$Lambda$43/1513029997.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:748)
Exception in thread "XNIO-1 task-3" java.lang.OutOfMemoryError: Java heap space
01/11 09:11:44.092 [XNIO-1 I/O-5] ERROR org.xnio.listener - XNIO001007: A channel event listener threw an exception
java.lang.OutOfMemoryError: Java heap space
Exception in thread "Solid TX cascader" java.lang.OutOfMemoryError: Java heap space
01/11 09:17:28.138 [XNIO-1 I/O-1] ERROR org.xnio.listener - XNIO001007: A channel event listener threw an exception
java.lang.OutOfMemoryError: Java heap space
01/11 09:22:23.192 [Local Snapshots Monitor] ERROR c.i.i.s.s.i.LocalSnapshotManagerImpl - error while taking local snapshot
com.iota.iri.service.snapshot.SnapshotException: pl.touk.throwing.exception.WrappedException: Java heap space
    at com.iota.iri.service.snapshot.impl.SnapshotServiceImpl.persistLocalSnapshot(SnapshotServiceImpl.java:504) ~[iri-live.jar:na]
    at com.iota.iri.service.snapshot.impl.SnapshotServiceImpl.takeLocalSnapshot(SnapshotServiceImpl.java:226) ~[iri-live.jar:na]
    at com.iota.iri.service.snapshot.impl.LocalSnapshotManagerImpl.monitorThread(LocalSnapshotManagerImpl.java:130) [iri-live.jar:na]
    at com.iota.iri.service.snapshot.impl.LocalSnapshotManagerImpl.lambda$start$0(LocalSnapshotManagerImpl.java:97) [iri-live.jar:na]
    at com.iota.iri.utils.thread.ThreadUtils.lambda$spawnThread$0(ThreadUtils.java:76) ~[iri-live.jar:na]
    at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
Caused by: pl.touk.throwing.exception.WrappedException: Java heap space
    at pl.touk.throwing.ThrowingPredicate.lambda$uncheck$13(ThrowingPredicate.java:78) ~[iri-live.jar:na]
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[na:1.8.0_181]
    at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553) ~[na:1.8.0_181]
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_181]
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_181]
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_181]
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_181]
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_181]
    at com.iota.iri.service.spentaddresses.impl.SpentAddressesServiceImpl.persistSpentAddresses(SpentAddressesServiceImpl.java:99) ~[iri-live.jar:na]
    at com.iota.iri.service.snapshot.impl.SnapshotServiceImpl.persistLocalSnapshot(SnapshotServiceImpl.java:500) ~[iri-live.jar:na]
    ... 5 common frames omitted
Caused by: java.lang.OutOfMemoryError: Java heap space
01/11 09:22:23.213 [XNIO-1 task-5] ERROR io.undertow.request - UT005071: Undertow request failed HttpServerExchange{ POST / request {Accept=[*/*], Connection=[close], Content-Type=[application/json], Content-Length=[26], User-Agent=[node-XMLHttpRequest], X-IOTA-API-Version=[1], Host=[iri02.service:14266]} response {Content-Type=[application/json]}}
```

**Comment by alexkvak** [comment]
I have the same issue on v1.6.1-RELEASE
