### ISSUE TITLE
1.1.3.10 - Stopped and re-started the node

### ISSUE THREAD

**Issue by Nyrsta** [iotaledger/iri#129]
05/21 09:11:17.296 [Solid Milestone Tracker] ERROR com.iota.iri.Milestone - Error initializing snapshots. Skipping.
java.lang.NullPointerException: null
        at com.iota.iri.LedgerValidator.updateSnapshot(LedgerValidator.java:274) ~[iri-1.1.3.10.jar:na]
        at com.iota.iri.LedgerValidator.init(LedgerValidator.java:210) ~[iri-1.1.3.10.jar:na]
        at com.iota.iri.Milestone.lambda$init$1(Milestone.java:88) ~[iri-1.1.3.10.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]

**Comment by paulhandy** [comment]
Resolved with https://github.com/iotaledger/iri/commit/c00176963f86856a74380c9c6b5b74686010af56
