### ISSUE TITLE
Bug: Error Accessing Persistence Store 

### ISSUE THREAD

**Issue by DyrellC** [iotaledger/iri#1298]
### Bug description
Transaction pruner is spitting out an access error for the persistence storage, and the node dies after a time. 

### IRI version
1.6.0-RELEASE

### Hardware Spec
8GB/128GB VM droplet (Digital Ocean) 

### Steps To Reproduce
1. Run IRI with db that is still syncing 
2. Leave configuration as base config
3. Wait for node to process milestone candidates and run for a bit, collecting new milestones but not syncing fully
4. Watch the errors get spit out in rapid succession

### Expected behaviour
Transaction pruner should not have an issue persisting.

### Actual behaviour
Transaction pruner crashes node after failing to save to state.

### Errors
```
01/23 08:09:00.950 [pool-12-thread-4] ERROR com.iota.iri.network.Node - Error accessing persistence store.
java.lang.IllegalArgumentException: Illegal value provided for SubCode.
	at org.rocksdb.Status$SubCode.getSubCode(Status.java:109) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.Status.<init>(Status.java:30) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.RocksDB.write0(Native Method) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.RocksDB.write(RocksDB.java:602) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.saveBatch(RocksDBPersistenceProvider.java:286) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.storage.Tangle.saveBatch(Tangle.java:71) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.controllers.TransactionViewModel.store(TransactionViewModel.java:401) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.processReceivedData(Node.java:458) [iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.processReceivedDataFromQueue(Node.java:431) [iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.lambda$spawnProcessReceivedThread$8(Node.java:680) 01/23 08:34:07.584 [pool-12-thread-4] ERROR com.iota.iri.network.Node - Error accessing persistence store.
java.lang.IllegalArgumentException: Illegal value provided for SubCode.
	at org.rocksdb.Status$SubCode.getSubCode(Status.java:109) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.Status.<init>(Status.java:30) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.RocksDB.write0(Native Method) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.RocksDB.write(RocksDB.java:602) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.saveBatch(RocksDBPersistenceProvider.java:286) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.storage.Tangle.saveBatch(Tangle.java:71) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.controllers.TransactionViewModel.store(TransactionViewModel.java:401) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.processReceivedData(Node.java:458) [iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.processReceivedDataFromQueue(Node.java:431) [iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.lambda$spawnProcessReceivedThread$8(Node.java:680) [iri-1.6.0-RELEASE.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:257) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:747) ~[na:1.8.0_191]
01/23 08:34:07.587 [Transaction Pruner Persister] ERROR c.i.i.s.t.a.AsyncTransactionPruner - could not persist transaction pruner state
com.iota.iri.service.transactionpruning.TransactionPruningException: failed to write the state file
	at com.iota.iri.service.transactionpruning.async.AsyncTransactionPruner.saveStateNow(AsyncTransactionPruner.java:349) [iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.service.transactionpruning.async.AsyncTransactionPruner.persistThread(AsyncTransactionPruner.java:293) [iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.utils.thread.ThreadUtils.lambda$spawnThread$0(ThreadUtils.java:74) ~[iri-1.6.0-RELEASE.jar:na]
	at java.lang.Thread.run(Thread.java:747) ~[na:1.8.0_191]
Caused by: java.io.IOException: No space left on device
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[na:1.8.0_191]
	at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:60) ~[na:1.8.0_191]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[na:1.8.0_191]
	at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[na:1.8.0_191]
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:211) ~[na:1.8.0_191]
	at java.nio.channels.Channels.writeFullyImpl(Channels.java:78) ~[na:1.8.0_191]
	at java.nio.channels.Channels.writeFully(Channels.java:101) ~[na:1.8.0_191]
	at java.nio.channels.Channels.access$000(Channels.java:61) ~[na:1.8.0_191]
	at java.nio.channels.Channels$1.write(Channels.java:174) ~[na:1.8.0_191]
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221) ~[na:1.8.0_191]
	at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:316) ~[na:1.8.0_191]
	at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149) ~[na:1.8.0_191]
	at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233) ~[na:1.8.0_191]
	at java.io.BufferedWriter.close(BufferedWriter.java:266) ~[na:1.8.0_191]
	at java.nio.file.Files.write(Files.java:3357) ~[na:1.8.0_191]
	at java.nio.file.Files.write(Files.java:3397) ~[na:1.8.0_191]
	at com.iota.iri.service.transactionpruning.async.AsyncTransactionPruner.saveStateNow(AsyncTransactionPruner.java:329) [iri-1.6.0-RELEASE.jar:na]
	... 3 common frames omitted
01/23 08:34:07.629 [pool-12-thread-4] ERROR com.iota.iri.network.Node - Error accessing persistence store.
java.lang.IllegalArgumentException: Illegal value provided for SubCode.
	at org.rocksdb.Status$SubCode.getSubCode(Status.java:109) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.Status.<init>(Status.java:30) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.RocksDB.write0(Native Method) ~[iri-1.6.0-RELEASE.jar:na]
	at root@gec:~/node/iri/target# tail -100 nodelog.out
	at com.iota.iri.network.Node.processReceivedDataFromQueue(Node.java:431) [iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.lambda$spawnProcessReceivedThread$8(Node.java:680) [iri-1.6.0-RELEASE.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:257) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:747) ~[na:1.8.0_191]
01/23 08:09:00.947 [pool-12-thread-4] ERROR com.iota.iri.network.Node - Error accessing persistence store.
java.lang.IllegalArgumentException: Illegal value provided for SubCode.
	at org.rocksdb.Status$SubCode.getSubCode(Status.java:109) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.Status.<init>(Status.java:30) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.RocksDB.write0(Native Method) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.RocksDB.write(RocksDB.java:602) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.saveBatch(RocksDBPersistenceProvider.java:286) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.storage.Tangle.saveBatch(Tangle.java:71) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.controllers.TransactionViewModel.store(TransactionViewModel.java:401) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.processReceivedData(Node.java:458) [iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.processReceivedDataFromQueue(Node.java:431) [iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.lambda$spawnProcessReceivedThread$8(Node.java:680) [iri-1.6.0-RELEASE.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:257) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:747) ~[na:1.8.0_191]
01/23 08:09:00.948 [pool-12-thread-4] ERROR com.iota.iri.network.Node - Error accessing persistence store.
java.lang.IllegalArgumentException: Illegal value provided for SubCode.
	at org.rocksdb.Status$SubCode.getSubCode(Status.java:109) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.Status.<init>(Status.java:30) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.RocksDB.write0(Native Method) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.RocksDB.write(RocksDB.java:602) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.saveBatch(RocksDBPersistenceProvider.java:286) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.storage.Tangle.saveBatch(Tangle.java:71) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.controllers.TransactionViewModel.store(TransactionViewModel.java:401) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.processReceivedData(Node.java:458) [iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.processReceivedDataFromQueue(Node.java:431) [iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.lambda$spawnProcessReceivedThread$8(Node.java:680) [iri-1.6.0-RELEASE.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:257) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:747) ~[na:1.8.0_191]
01/23 08:09:00.950 [pool-12-thread-4] ERROR com.iota.iri.network.Node - Error accessing persistence store.
java.lang.IllegalArgumentException: Illegal value provided for SubCode.
	at org.rocksdb.Status$SubCode.getSubCode(Status.java:109) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.Status.<init>(Status.java:30) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.RocksDB.write0(Native Method) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.RocksDB.write(RocksDB.java:602) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.saveBatch(RocksDBPersistenceProvider.java:286) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.storage.Tangle.saveBatch(Tangle.java:71) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.controllers.TransactionViewModel.store(TransactionViewModel.java:401) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.processReceivedData(Node.java:458) [iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.processReceivedDataFromQueue(Node.java:431) [iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.lambda$spawnProcessReceivedThread$8(Node.java:680) 01/23 08:34:07.584 [pool-12-thread-4] ERROR com.iota.iri.network.Node - Error accessing persistence store.
java.lang.IllegalArgumentException: Illegal value provided for SubCode.
	at org.rocksdb.Status$SubCode.getSubCode(Status.java:109) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.Status.<init>(Status.java:30) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.RocksDB.write0(Native Method) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.RocksDB.write(RocksDB.java:602) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.saveBatch(RocksDBPersistenceProvider.java:286) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.storage.Tangle.saveBatch(Tangle.java:71) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.controllers.TransactionViewModel.store(TransactionViewModel.java:401) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.processReceivedData(Node.java:458) [iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.processReceivedDataFromQueue(Node.java:431) [iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.lambda$spawnProcessReceivedThread$8(Node.java:680) [iri-1.6.0-RELEASE.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:257) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:747) ~[na:1.8.0_191]
01/23 08:34:07.587 [Transaction Pruner Persister] ERROR c.i.i.s.t.a.AsyncTransactionPruner - could not persist transaction pruner state
com.iota.iri.service.transactionpruning.TransactionPruningException: failed to write the state file
	at com.iota.iri.service.transactionpruning.async.AsyncTransactionPruner.saveStateNow(AsyncTransactionPruner.java:349) [iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.service.transactionpruning.async.AsyncTransactionPruner.persistThread(AsyncTransactionPruner.java:293) [iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.utils.thread.ThreadUtils.lambda$spawnThread$0(ThreadUtils.java:74) ~[iri-1.6.0-RELEASE.jar:na]
	at java.lang.Thread.run(Thread.java:747) ~[na:1.8.0_191]
Caused by: java.io.IOException: No space left on device
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[na:1.8.0_191]
	at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:60) ~[na:1.8.0_191]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[na:1.8.0_191]
	at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[na:1.8.0_191]
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:211) ~[na:1.8.0_191]
	at java.nio.channels.Channels.writeFullyImpl(Channels.java:78) ~[na:1.8.0_191]
	at java.nio.channels.Channels.writeFully(Channels.java:101) ~[na:1.8.0_191]
	at java.nio.channels.Channels.access$000(Channels.java:61) ~[na:1.8.0_191]
	at java.nio.channels.Channels$1.write(Channels.java:174) ~[na:1.8.0_191]
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221) ~[na:1.8.0_191]
	at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:316) ~[na:1.8.0_191]
	at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149) ~[na:1.8.0_191]
	at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233) ~[na:1.8.0_191]
	at java.io.BufferedWriter.close(BufferedWriter.java:266) ~[na:1.8.0_191]
	at java.nio.file.Files.write(Files.java:3357) ~[na:1.8.0_191]
	at java.nio.file.Files.write(Files.java:3397) ~[na:1.8.0_191]
	at com.iota.iri.service.transactionpruning.async.AsyncTransactionPruner.saveStateNow(AsyncTransactionPruner.java:329) [iri-1.6.0-RELEASE.jar:na]
	... 3 common frames omitted
01/23 08:34:07.629 [pool-12-thread-4] ERROR com.iota.iri.network.Node - Error accessing persistence store.
java.lang.IllegalArgumentException: Illegal value provided for SubCode.
	at org.rocksdb.Status$SubCode.getSubCode(Status.java:109) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.Status.<init>(Status.java:30) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.RocksDB.write0(Native Method) ~[iri-1.6.0-RELEASE.jar:na]
	at root@gec:~/node/iri/target# ^C
root@gec:~/node/iri/target# tail -100 nodelog.out
	at com.iota.iri.network.Node.processReceivedDataFromQueue(Node.java:431) [iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.lambda$spawnProcessReceivedThread$8(Node.java:680) [iri-1.6.0-RELEASE.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:257) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:747) ~[na:1.8.0_191]
01/23 08:09:00.947 [pool-12-thread-4] ERROR com.iota.iri.network.Node - Error accessing persistence store.
java.lang.IllegalArgumentException: Illegal value provided for SubCode.
	at org.rocksdb.Status$SubCode.getSubCode(Status.java:109) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.Status.<init>(Status.java:30) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.RocksDB.write0(Native Method) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.RocksDB.write(RocksDB.java:602) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.saveBatch(RocksDBPersistenceProvider.java:286) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.storage.Tangle.saveBatch(Tangle.java:71) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.controllers.TransactionViewModel.store(TransactionViewModel.java:401) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.processReceivedData(Node.java:458) [iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.processReceivedDataFromQueue(Node.java:431) [iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.lambda$spawnProcessReceivedThread$8(Node.java:680) [iri-1.6.0-RELEASE.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:257) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:747) ~[na:1.8.0_191]
01/23 08:09:00.948 [pool-12-thread-4] ERROR com.iota.iri.network.Node - Error accessing persistence store.
java.lang.IllegalArgumentException: Illegal value provided for SubCode.
	at org.rocksdb.Status$SubCode.getSubCode(Status.java:109) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.Status.<init>(Status.java:30) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.RocksDB.write0(Native Method) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.RocksDB.write(RocksDB.java:602) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.saveBatch(RocksDBPersistenceProvider.java:286) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.storage.Tangle.saveBatch(Tangle.java:71) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.controllers.TransactionViewModel.store(TransactionViewModel.java:401) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.processReceivedData(Node.java:458) [iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.processReceivedDataFromQueue(Node.java:431) [iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.lambda$spawnProcessReceivedThread$8(Node.java:680) [iri-1.6.0-RELEASE.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:257) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:747) ~[na:1.8.0_191]
01/23 08:09:00.950 [pool-12-thread-4] ERROR com.iota.iri.network.Node - Error accessing persistence store.
java.lang.IllegalArgumentException: Illegal value provided for SubCode.
	at org.rocksdb.Status$SubCode.getSubCode(Status.java:109) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.Status.<init>(Status.java:30) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.RocksDB.write0(Native Method) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.RocksDB.write(RocksDB.java:602) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.saveBatch(RocksDBPersistenceProvider.java:286) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.storage.Tangle.saveBatch(Tangle.java:71) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.controllers.TransactionViewModel.store(TransactionViewModel.java:401) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.processReceivedData(Node.java:458) [iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.processReceivedDataFromQueue(Node.java:431) [iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.lambda$spawnProcessReceivedThread$8(Node.java:680) 01/23 08:34:07.584 [pool-12-thread-4] ERROR com.iota.iri.network.Node - Error accessing persistence store.
java.lang.IllegalArgumentException: Illegal value provided for SubCode.
	at org.rocksdb.Status$SubCode.getSubCode(Status.java:109) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.Status.<init>(Status.java:30) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.RocksDB.write0(Native Method) ~[iri-1.6.0-RELEASE.jar:na]
	at org.rocksdb.RocksDB.write(RocksDB.java:602) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.saveBatch(RocksDBPersistenceProvider.java:286) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.storage.Tangle.saveBatch(Tangle.java:71) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.controllers.TransactionViewModel.store(TransactionViewModel.java:401) ~[iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.processReceivedData(Node.java:458) [iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.processReceivedDataFromQueue(Node.java:431) [iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.network.Node.lambda$spawnProcessReceivedThread$8(Node.java:680) [iri-1.6.0-RELEASE.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:257) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:747) ~[na:1.8.0_191]
01/23 08:34:07.587 [Transaction Pruner Persister] ERROR c.i.i.s.t.a.AsyncTransactionPruner - could not persist transaction pruner state
com.iota.iri.service.transactionpruning.TransactionPruningException: failed to write the state file
	at com.iota.iri.service.transactionpruning.async.AsyncTransactionPruner.saveStateNow(AsyncTransactionPruner.java:349) [iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.service.transactionpruning.async.AsyncTransactionPruner.persistThread(AsyncTransactionPruner.java:293) [iri-1.6.0-RELEASE.jar:na]
	at com.iota.iri.utils.thread.ThreadUtils.lambda$spawnThread$0(ThreadUtils.java:74) ~[iri-1.6.0-RELEASE.jar:na]
	at java.lang.Thread.run(Thread.java:747) ~[na:1.8.0_191]
Caused by: java.io.IOException: No space left on device
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[na:1.8.0_191]
	at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:60) ~[na:1.8.0_191]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[na:1.8.0_191]
	at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[na:1.8.0_191]
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:211) ~[na:1.8.0_191]
	at java.nio.channels.Channels.writeFullyImpl(Channels.java:78) ~[na:1.8.0_191]
	at java.nio.channels.Channels.writeFully(Channels.java:101) ~[na:1.8.0_191]
	at java.nio.channels.Channels.access$000(Channels.java:61) ~[na:1.8.0_191]
	at java.nio.channels.Channels$1.write(Channels.java:174) ~[na:1.8.0_191]
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221) ~[na:1.8.0_191]
	at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:316) ~[na:1.8.0_191]
	at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149) ~[na:1.8.0_191]
	at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233) ~[na:1.8.0_191]
	at java.io.BufferedWriter.close(BufferedWriter.java:266) ~[na:1.8.0_191]
	at java.nio.file.Files.write(Files.java:3357) ~[na:1.8.0_191]
	at java.nio.file.Files.write(Files.java:3397) ~[na:1.8.0_191]
	at com.iota.iri.service.transactionpruning.async.AsyncTransactionPruner.saveStateNow(AsyncTransactionPruner.java:329) [iri-1.6.0-RELEASE.jar:na]
	... 3 common frames omitted
```

**Comment by DyrellC** [comment]
The node is falsely claiming that I have no more disk space available but that is not the case, there are still 40GB of space available

**Comment by nuriel77** [comment]
Just a wild guess here:
Could it be out of inodes? (`df -i`)
Or could there be a discrepancy between how you checked available storage to what is seen by Java?

**Comment by Cryptec** [comment]
i have the same Issue on my node. It happens since the update to IRI 1.6.0 and always at a public spam.

**Comment by JTSweet** [comment]
_The node is falsely claiming that I have no more disk space available but that is not the case, there are still 40GB of space available_

Check the size of the file created by the persistent storage, I recently worked on a issue where 75% of the disk space was used but the state store created by RocksDB (persistent storage) was 25gb which caused it to fail.  The resolution was to increase the disk storage space and ensure that there was adequate disk space free (50%) at all times to prevent this type of issue in the future in case RocksDB decided to compact multiple state stores at once.

**Comment by nuriel77** [comment]
Share
`df -h`
and
`df -i`

**Comment by GalRogozinski** [comment]
Since no comment from @DyrellC I am closing this issue since I am satisfied with @JTSweet's remark
