### ISSUE TITLE
Error while updating the solid milestone

### ISSUE THREAD

**Issue by grittibaenz** [iotaledger/iri#1299]
### Bug description
After updating IRI from version `iri-1.5.6-RELEASE` to `iri-1.6.0-RELEASE`, the application kept crashing with an OOM issue. I tried different JVM memory settings, which didn't solve the issue (_solution for the OOM issue see #other_).

After the 5th crash or so, the following message started appearing in the logs:
```
01/24 07:55:33.600 [Latest Solid Milestone Tracker] ERROR c.i.i.s.m.i.LatestSolidMilestoneTrackerImpl - error while updating the solid milestone
```

This error message keeps repeating every +/- 5 seconds and the solid milestone index does not update anymore.

A downgrade attempt to version `iri-1.5.6-RELEASE` did not solve this issue. IRI keeps throwing the error from above. I have a feeling that my database got corrupted somehow.

I kept the potentially corrupt database and I am happy to test any bug fixes or report additional details.

### IRI version
`iri-1.6.0-RELEASE`

### Hardware Spec
Linux virtual machine:
```
16 cores
16 GB memory
200 GB SSD
```

### Steps To Reproduce
1. Update IRI to version `iri-1.6.0-RELEASE`
2. Start IRI with the following memory settings:
```
/app/jdk/current/bin/java -XX:+CrashOnOutOfMemoryError -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses -XX:+CMSParallelRemarkEnabled -XX:+DisableAttachMechanism -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:MaxMetaspaceSize=30m -Xmx6G -Xms2G -Djava.net.preferIPv4Stack=true -jar /app/iri/bin/iri-1.5.6-RELEASE.jar -c /app/iri/conf/iri.ini -p 9000 --remote
```
3. Let it crash numerous times and "_hope_" to see the error message.

### Expected behaviour
An update to IRI version `iri-1.6.0-RELEASE` should not result in this error and a potential database corruption.

### Errors
```
01/24 07:55:33.600 [Latest Solid Milestone Tracker] ERROR c.i.i.s.m.i.LatestSolidMilestoneTrackerImpl - error while updating the solid milestone
```
Please find a complete log output here: https://paste.ee/p/Tve0R

### Other
As I have been told the OOM issue can be circumvented by adding the following configuration to the `iri.ini` file:
```
LOCAL_SNAPSHOTS_PRUNING_ENABLED = false
```

**Comment by GalRogozinski** [comment]
If you can paste the full log it will be great.
I want to see if it is different than #1273

**Comment by grittibaenz** [comment]
@GalRogozinski: please find the log output below:
```
iri@iota_iri:~ $ /app/jdk/current/bin/java -Xmx6G -Xms2G -Djava.net.preferIPv4Stack=true -jar /app/iri/bin/iri-1.6.0-RELEASE.jar -c /app/iri/conf/iri.ini -p 9000 --remote
Logging - property 'logging-level' set to: [INFO]
01/24 07:54:39.921 [main] INFO  com.iota.iri.IRI$IRILauncher - Configuration is created using iri.ini and command line args
01/24 07:54:39.923 [main] INFO  com.iota.iri.IRI$IRILauncher - parsed the following cmd args: [-c, /app/iri/conf/iri.ini, -p, 9000, --remote]
01/24 07:54:39.924 [main] INFO  com.iota.iri.IRI$IRILauncher - Welcome to IRI 1.6.0-RELEASE
01/24 07:54:45.852 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - Initializing Database on spent-addresses-db
01/24 07:54:45.962 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - RocksDB persistence provider initialized.
01/24 07:55:20.282 [main] INFO  c.i.i.s.m.i.LatestMilestoneTrackerImpl - Latest milestone has changed from #0 to #933210
01/24 07:55:23.889 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - Initializing Database on /data/iri/db
01/24 07:55:28.375 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - RocksDB persistence provider initialized.
01/24 07:55:28.379 [main] INFO  com.iota.iri.network.UDPReceiver - UDP replicator is accepting connections on udp port 14600
01/24 07:55:28.380 [UDP receiving thread] INFO  com.iota.iri.network.UDPReceiver - Spawning Receiver Thread
01/24 07:55:28.380 [main] INFO  c.i.i.network.replicator.Replicator - Started ReplicatorSourcePool
01/24 07:55:28.381 [Thread-2] INFO  c.i.i.n.r.ReplicatorSourcePool - TCP replicator is accepting connections on tcp port 15600
01/24 07:55:28.388 [main] INFO  com.iota.iri.network.Node - -> Adding neighbor : peer01.domain.tld/5.5.5.5:15600
01/24 07:55:28.390 [main] INFO  com.iota.iri.network.Node - -> Adding neighbor : peer01.domain.tld/1.1.1.1:14600
01/24 07:55:28.397 [main] INFO  com.iota.iri.network.Node - -> Adding neighbor : peer02.domain.tld/2.2.2.2:16100
01/24 07:55:28.405 [main] INFO  com.iota.iri.network.Node - -> Adding neighbor : peer03.domain.tld/3.3.3.3:15600
01/24 07:55:28.406 [main] INFO  com.iota.iri.network.Node - -> Adding neighbor : peer04.domain.tld/4.4.4.4:14600
01/24 07:55:28.407 [pool-12-thread-1] INFO  com.iota.iri.network.Node - Spawning Broadcaster Thread
01/24 07:55:28.408 [pool-12-thread-2] INFO  com.iota.iri.network.Node - Spawning Tips Requester Thread
01/24 07:55:28.408 [pool-12-thread-3] INFO  com.iota.iri.network.Node - Spawning Neighbor DNS Refresher Thread
01/24 07:55:28.408 [pool-12-thread-3] INFO  com.iota.iri.network.Node - Checking Neighbors' Ip...
01/24 07:55:28.409 [pool-12-thread-4] INFO  com.iota.iri.network.Node - Spawning Process Received Data Thread
01/24 07:55:28.410 [pool-12-thread-5] INFO  com.iota.iri.network.Node - Spawning Reply To Request Thread
01/24 07:55:28.425 [pool-12-thread-3] INFO  com.iota.iri.network.Node - DNS Checker: Validating DNS Address 'peer01.domain.tld' with '5.5.5.5'
01/24 07:55:28.425 [pool-12-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 0 , toReply = 0 / totalTransactions = 17481941
01/24 07:55:28.425 [pool-12-thread-3] INFO  com.iota.iri.network.Node - DNS Checker: Validating DNS Address 'peer01.domain.tld' with '1.1.1.1'
01/24 07:55:28.425 [pool-12-thread-3] INFO  com.iota.iri.network.Node - DNS Checker: Validating DNS Address 'peer02.domain.tld' with '2.2.2.2'
01/24 07:55:28.426 [pool-12-thread-3] INFO  com.iota.iri.network.Node - DNS Checker: Validating DNS Address 'peer03.domain.tld' with '3.3.3.3'
01/24 07:55:28.426 [pool-12-thread-3] INFO  com.iota.iri.network.Node - DNS Checker: Validating DNS Address 'peer04.domain.tld' with '4.4.4.4'
01/24 07:55:28.426 [main] INFO  c.i.i.s.m.i.LatestMilestoneTrackerImpl - Starting [Latest Milestone Tracker] (starts in 0ms / runs every 1000ms) ...
01/24 07:55:28.428 [main] INFO  c.i.i.s.m.i.LatestSolidMilestoneTrackerImpl - Starting [Latest Solid Milestone Tracker] (starts in 0ms / runs every 5000ms) ...
01/24 07:55:28.428 [main] INFO  c.i.i.s.m.i.LatestMilestoneTrackerImpl - [Latest Milestone Tracker] Started (execution #1) ...
01/24 07:55:28.434 [main] INFO  c.i.i.s.m.i.LatestSolidMilestoneTrackerImpl - [Latest Solid Milestone Tracker] Started (execution #1) ...
01/24 07:55:28.435 [main] INFO  c.i.i.s.m.i.SeenMilestonesRetrieverImpl - Starting [Seen Milestones Retriever] (starts in 0ms / runs every 1000ms) ...
01/24 07:55:28.437 [main] INFO  c.i.i.s.m.MilestoneSolidifier - Starting [Milestone Solidifier] (starts in 0ms / runs every 100ms) ...
01/24 07:55:28.437 [main] INFO  c.i.i.s.m.i.SeenMilestonesRetrieverImpl - [Seen Milestones Retriever] Started (execution #1) ...
01/24 07:55:28.440 [main] INFO  c.i.i.s.m.MilestoneSolidifier - [Milestone Solidifier] Started (execution #1) ...
01/24 07:55:28.441 [main] INFO  c.i.i.n.i.TransactionRequesterWorkerImpl - Starting [Transaction Requester] (starts in 0ms / runs every 100ms) ...
01/24 07:55:28.441 [Seen Milestones Retriever] INFO  c.i.i.s.m.i.SeenMilestonesRetrieverImpl - Requesting seen milestones ... [DONE]
01/24 07:55:28.442 [Seen Milestones Retriever] INFO  c.i.i.s.m.i.SeenMilestonesRetrieverImpl - Stopping [Seen Milestones Retriever] ...
01/24 07:55:28.442 [main] INFO  c.i.i.n.i.TransactionRequesterWorkerImpl - [Transaction Requester] Started (execution #1) ...
01/24 07:55:28.442 [main] INFO  c.iota.iri.utils.thread.ThreadUtils - Starting Thread: Local Snapshots Monitor ...
01/24 07:55:28.443 [main] INFO  c.i.i.s.m.i.SeenMilestonesRetrieverImpl - [Seen Milestones Retriever] Stopped (after #1 executions) ...
01/24 07:55:28.444 [Local Snapshots Monitor] INFO  c.iota.iri.utils.thread.ThreadUtils - Local Snapshots Monitor [STARTED]
01/24 07:55:28.445 [main] INFO  c.iota.iri.utils.thread.ThreadUtils - Starting Thread: Transaction Pruner ...
01/24 07:55:28.446 [Transaction Pruner] INFO  c.iota.iri.utils.thread.ThreadUtils - Transaction Pruner [STARTED]
01/24 07:55:28.446 [main] INFO  c.iota.iri.utils.thread.ThreadUtils - Starting Thread: Transaction Pruner Persister ...
01/24 07:55:28.457 [Transaction Pruner Persister] INFO  c.iota.iri.utils.thread.ThreadUtils - Transaction Pruner Persister [STARTED]
01/24 07:55:28.538 [main] INFO  org.xnio - XNIO version 3.3.8.Final
01/24 07:55:28.606 [main] INFO  org.xnio.nio - XNIO NIO Implementation Version 3.3.8.Final
01/24 07:55:30.581 [Latest Milestone Tracker] INFO  c.i.i.s.m.i.LatestMilestoneTrackerImpl - Processing milestone candidates (239253 remaining) ...
01/24 07:55:30.615 [Latest Milestone Tracker] INFO  c.i.i.s.m.i.LatestMilestoneTrackerImpl - Latest milestone has changed from #933210 to #980108
01/24 07:55:30.633 [main] INFO  com.iota.iri.IRI$IRILauncher - IOTA Node initialised correctly.
01/24 07:55:30.667 [Milestone Solidifier] INFO  c.i.i.s.m.MilestoneSolidifier - Solidifying milestone #977322 [5 / 19]
01/24 07:55:31.520 [pool-14-thread-2] INFO  c.i.i.n.r.ReplicatorSinkProcessor - Opening sink 2.2.2.2
01/24 07:55:31.520 [pool-14-thread-3] INFO  c.i.i.n.r.ReplicatorSinkProcessor - Opening sink 3.3.3.3
01/24 07:55:31.520 [pool-14-thread-1] INFO  c.i.i.n.r.ReplicatorSinkProcessor - Opening sink 5.5.5.5
01/24 07:55:31.521 [pool-14-thread-3] INFO  c.i.i.n.r.ReplicatorSinkProcessor - Connecting sink 3.3.3.3
01/24 07:55:31.521 [pool-14-thread-1] INFO  c.i.i.n.r.ReplicatorSinkProcessor - Connecting sink 5.5.5.5
01/24 07:55:31.521 [pool-14-thread-2] INFO  c.i.i.n.r.ReplicatorSinkProcessor - Connecting sink 2.2.2.2
01/24 07:55:31.541 [pool-14-thread-1] INFO  c.i.i.n.r.ReplicatorSinkProcessor - ----- NETWORK INFO ----- Sink 5.5.5.5 is connected
01/24 07:55:31.541 [pool-14-thread-2] INFO  c.i.i.n.r.ReplicatorSinkProcessor - ----- NETWORK INFO ----- Sink 2.2.2.2 is connected
01/24 07:55:31.541 [pool-14-thread-3] INFO  c.i.i.n.r.ReplicatorSinkProcessor - ----- NETWORK INFO ----- Sink 3.3.3.3 is connected
01/24 07:55:33.441 [Latest Solid Milestone Tracker] INFO  c.i.i.s.m.i.LatestSolidMilestoneTrackerImpl - Latest SOLID milestone index changed from #933210 to #976637
01/24 07:55:33.452 [Latest Solid Milestone Tracker] INFO  c.i.i.s.s.impl.SnapshotStateImpl - negative value for address KSNWNNLGLHIBVFMULCEXDQLXMGGVKLACPPDNKSQYLBPPHISXGCNDZHEGCTQII9PRMRB9TXTBZ9BZTOSGW: -181941
01/24 07:55:33.452 [Latest Solid Milestone Tracker] INFO  c.i.i.s.m.impl.MilestoneServiceImpl - resetting corrupted milestone #976638
01/24 07:55:33.463 [Latest Solid Milestone Tracker] INFO  c.i.i.s.s.impl.SnapshotStateImpl - negative value for address KSNWNNLGLHIBVFMULCEXDQLXMGGVKLACPPDNKSQYLBPPHISXGCNDZHEGCTQII9PRMRB9TXTBZ9BZTOSGW: -181941
01/24 07:55:33.464 [Latest Solid Milestone Tracker] INFO  c.i.i.s.m.impl.MilestoneServiceImpl - resetting corrupted milestone #976638
01/24 07:55:33.466 [Latest Solid Milestone Tracker] INFO  c.i.i.s.m.impl.MilestoneServiceImpl - resetting corrupted milestone #976637
01/24 07:55:33.512 [Latest Solid Milestone Tracker] INFO  c.i.i.s.s.impl.SnapshotStateImpl - negative value for address KSNWNNLGLHIBVFMULCEXDQLXMGGVKLACPPDNKSQYLBPPHISXGCNDZHEGCTQII9PRMRB9TXTBZ9BZTOSGW: -181953
01/24 07:55:33.600 [Latest Solid Milestone Tracker] ERROR c.i.i.s.m.i.LatestSolidMilestoneTrackerImpl - error while updating the solid milestone
com.iota.iri.service.milestone.MilestoneException: unexpected error while checking for new latest solid milestones
        at com.iota.iri.service.milestone.impl.LatestSolidMilestoneTrackerImpl.trackLatestSolidMilestone(LatestSolidMilestoneTrackerImpl.java:166) ~[iri-1.6.0-RELEASE.jar:na]
        at com.iota.iri.service.milestone.impl.LatestSolidMilestoneTrackerImpl.latestSolidMilestoneTrackerThread(LatestSolidMilestoneTrackerImpl.java:185) ~[iri-1.6.0-RELEASE.jar:na]
        at com.iota.iri.utils.thread.BoundedScheduledExecutorService.lambda$wrapTask$6(BoundedScheduledExecutorService.java:749) ~[iri-1.6.0-RELEASE.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_201]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_201]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_201]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_201]
Caused by: com.iota.iri.service.milestone.MilestoneException: failed to repair corrupted milestone with index #976637
        at com.iota.iri.service.milestone.impl.MilestoneServiceImpl.resetCorruptedMilestone(MilestoneServiceImpl.java:531) ~[iri-1.6.0-RELEASE.jar:na]
        at com.iota.iri.service.milestone.impl.MilestoneServiceImpl.resetCorruptedMilestone(MilestoneServiceImpl.java:159) ~[iri-1.6.0-RELEASE.jar:na]
        at com.iota.iri.service.milestone.impl.LatestSolidMilestoneTrackerImpl.repairCorruptedMilestone(LatestSolidMilestoneTrackerImpl.java:309) ~[iri-1.6.0-RELEASE.jar:na]
        at com.iota.iri.service.milestone.impl.LatestSolidMilestoneTrackerImpl.applySolidMilestoneToLedger(LatestSolidMilestoneTrackerImpl.java:207) ~[iri-1.6.0-RELEASE.jar:na]
        at com.iota.iri.service.milestone.impl.LatestSolidMilestoneTrackerImpl.trackLatestSolidMilestone(LatestSolidMilestoneTrackerImpl.java:156) ~[iri-1.6.0-RELEASE.jar:na]
        ... 9 common frames omitted
Caused by: com.iota.iri.service.snapshot.SnapshotException: failed to rollback last milestone
        at com.iota.iri.service.snapshot.impl.SnapshotServiceImpl.rollbackLastMilestone(SnapshotServiceImpl.java:386) ~[iri-1.6.0-RELEASE.jar:na]
        at com.iota.iri.service.snapshot.impl.SnapshotServiceImpl.rollBackMilestones(SnapshotServiceImpl.java:193) ~[iri-1.6.0-RELEASE.jar:na]
        at com.iota.iri.service.milestone.impl.MilestoneServiceImpl.resetCorruptedMilestone(MilestoneServiceImpl.java:524) ~[iri-1.6.0-RELEASE.jar:na]
        ... 13 common frames omitted
Caused by: com.iota.iri.service.snapshot.SnapshotException: failed to apply patch belonging to milestone #976637 (ZZYVLKZUWYZXJSSVMRYFOIADCJFADIR9PSOMMTOKKWQSYWJCJZQVBJVYWXRLKABZOM9JQKVPQSGOA9999)
        at com.iota.iri.service.snapshot.impl.SnapshotServiceImpl.rollbackLastMilestone(SnapshotServiceImpl.java:357) ~[iri-1.6.0-RELEASE.jar:na]
        ... 15 common frames omitted
01/24 07:55:33.668 [Milestone Solidifier] INFO  c.i.i.s.m.MilestoneSolidifier - Solidifying milestone #976788 [10 / 78]
01/24 07:55:36.662 [Latest Milestone Tracker] INFO  c.i.i.s.m.i.LatestMilestoneTrackerImpl - Processing milestone candidates (234253 remaining) ...
01/24 07:55:36.669 [Milestone Solidifier] INFO  c.i.i.s.m.MilestoneSolidifier - Solidifying milestone #976790 [10 / 78]
01/24 07:55:36.727 [pool-15-thread-1] INFO  c.i.i.n.r.ReplicatorSourceProcessor - ----- NETWORK INFO ----- Source 2.2.2.2 is connected
01/24 07:55:36.831 [pool-14-thread-2] ERROR c.i.i.n.r.ReplicatorSinkProcessor - ***** NETWORK ALERT ***** No sink to apiHost 2.2.2.2:16100, reason: Socket is closed
01/24 07:55:38.427 [pool-12-thread-2] INFO  com.iota.iri.network.Node - toProcess = 7 , toBroadcast = 0 , toRequest = 5 , toReply = 0 / totalTransactions = 17481995
01/24 07:55:38.531 [Local Snapshots Monitor] INFO  c.i.i.s.s.impl.SnapshotStateImpl - negative value for address KSNWNNLGLHIBVFMULCEXDQLXMGGVKLACPPDNKSQYLBPPHISXGCNDZHEGCTQII9PRMRB9TXTBZ9BZTOSGW: -181953
01/24 07:55:38.585 [Latest Milestone Tracker] INFO  c.i.i.s.m.i.LatestMilestoneTrackerImpl - Latest milestone has changed from #980108 to #980111
01/24 07:55:38.605 [Latest Solid Milestone Tracker] INFO  c.i.i.s.s.impl.SnapshotStateImpl - negative value for address KSNWNNLGLHIBVFMULCEXDQLXMGGVKLACPPDNKSQYLBPPHISXGCNDZHEGCTQII9PRMRB9TXTBZ9BZTOSGW: -181941
01/24 07:55:38.605 [Latest Solid Milestone Tracker] INFO  c.i.i.s.m.impl.MilestoneServiceImpl - resetting corrupted milestone #976638
01/24 07:55:38.607 [Latest Solid Milestone Tracker] INFO  c.i.i.s.m.impl.MilestoneServiceImpl - resetting corrupted milestone #976637
01/24 07:55:38.609 [Local Snapshots Monitor] ERROR c.i.i.s.s.i.LocalSnapshotManagerImpl - error while taking local snapshot
com.iota.iri.service.snapshot.SnapshotException: failed to rollback last milestone
        at com.iota.iri.service.snapshot.impl.SnapshotServiceImpl.rollbackLastMilestone(SnapshotServiceImpl.java:386) ~[iri-1.6.0-RELEASE.jar:na]
        at com.iota.iri.service.snapshot.impl.SnapshotServiceImpl.rollBackMilestones(SnapshotServiceImpl.java:193) ~[iri-1.6.0-RELEASE.jar:na]
        at com.iota.iri.service.snapshot.impl.SnapshotServiceImpl.generateSnapshot(SnapshotServiceImpl.java:261) ~[iri-1.6.0-RELEASE.jar:na]
        at com.iota.iri.service.snapshot.impl.SnapshotServiceImpl.takeLocalSnapshot(SnapshotServiceImpl.java:217) ~[iri-1.6.0-RELEASE.jar:na]
        at com.iota.iri.service.snapshot.impl.LocalSnapshotManagerImpl.monitorThread(LocalSnapshotManagerImpl.java:130) [iri-1.6.0-RELEASE.jar:na]
        at com.iota.iri.service.snapshot.impl.LocalSnapshotManagerImpl.lambda$start$0(LocalSnapshotManagerImpl.java:97) [iri-1.6.0-RELEASE.jar:na]
        at com.iota.iri.utils.thread.ThreadUtils.lambda$spawnThread$0(ThreadUtils.java:76) ~[iri-1.6.0-RELEASE.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_201]
Caused by: com.iota.iri.service.snapshot.SnapshotException: failed to apply patch belonging to milestone #976637 (ZZYVLKZUWYZXJSSVMRYFOIADCJFADIR9PSOMMTOKKWQSYWJCJZQVBJVYWXRLKABZOM9JQKVPQSGOA9999)
        at com.iota.iri.service.snapshot.impl.SnapshotServiceImpl.rollbackLastMilestone(SnapshotServiceImpl.java:357) ~[iri-1.6.0-RELEASE.jar:na]
        ... 7 common frames omitted
01/24 07:55:38.648 [Latest Solid Milestone Tracker] INFO  c.i.i.s.s.impl.SnapshotStateImpl - negative value for address KSNWNNLGLHIBVFMULCEXDQLXMGGVKLACPPDNKSQYLBPPHISXGCNDZHEGCTQII9PRMRB9TXTBZ9BZTOSGW: -181953
01/24 07:55:38.609 [Local Snapshots Monitor] ERROR c.i.i.s.s.i.LocalSnapshotManagerImpl - error while taking local snapshot
com.iota.iri.service.snapshot.SnapshotException: failed to rollback last milestone
        at com.iota.iri.service.snapshot.impl.SnapshotServiceImpl.rollbackLastMilestone(SnapshotServiceImpl.java:386) ~[iri-1.6.0-RELEASE.jar:na]
        at com.iota.iri.service.snapshot.impl.SnapshotServiceImpl.rollBackMilestones(SnapshotServiceImpl.java:193) ~[iri-1.6.0-RELEASE.jar:na]
        at com.iota.iri.service.snapshot.impl.SnapshotServiceImpl.generateSnapshot(SnapshotServiceImpl.java:261) ~[iri-1.6.0-RELEASE.jar:na]
        at com.iota.iri.service.snapshot.impl.SnapshotServiceImpl.takeLocalSnapshot(SnapshotServiceImpl.java:217) ~[iri-1.6.0-RELEASE.jar:na]
        at com.iota.iri.service.snapshot.impl.LocalSnapshotManagerImpl.monitorThread(LocalSnapshotManagerImpl.java:130) [iri-1.6.0-RELEASE.jar:na]
        at com.iota.iri.service.snapshot.impl.LocalSnapshotManagerImpl.lambda$start$0(LocalSnapshotManagerImpl.java:97) [iri-1.6.0-RELEASE.jar:na]
        at com.iota.iri.utils.thread.ThreadUtils.lambda$spawnThread$0(ThreadUtils.java:76) ~[iri-1.6.0-RELEASE.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_201]
Caused by: com.iota.iri.service.snapshot.SnapshotException: failed to apply patch belonging to milestone #976637 (ZZYVLKZUWYZXJSSVMRYFOIADCJFADIR9PSOMMTOKKWQSYWJCJZQVBJVYWXRLKABZOM9JQKVPQSGOA9999)
        at com.iota.iri.service.snapshot.impl.SnapshotServiceImpl.rollbackLastMilestone(SnapshotServiceImpl.java:357) ~[iri-1.6.0-RELEASE.jar:na]
        ... 7 common frames omitted
01/24 07:55:38.648 [Latest Solid Milestone Tracker] INFO  c.i.i.s.s.impl.SnapshotStateImpl - negative value for address KSNWNNLGLHIBVFMULCEXDQLXMGGVKLACPPDNKSQYLBPPHISXGCNDZHEGCTQII9PRMRB9TXTBZ9BZTOSGW: -181953
01/24 07:55:38.736 [Latest Solid Milestone Tracker] ERROR c.i.i.s.m.i.LatestSolidMilestoneTrackerImpl - error while updating the solid milestone
com.iota.iri.service.milestone.MilestoneException: unexpected error while checking for new latest solid milestones
        at com.iota.iri.service.milestone.impl.LatestSolidMilestoneTrackerImpl.trackLatestSolidMilestone(LatestSolidMilestoneTrackerImpl.java:166) ~[iri-1.6.0-RELEASE.jar:na]
        at com.iota.iri.service.milestone.impl.LatestSolidMilestoneTrackerImpl.latestSolidMilestoneTrackerThread(LatestSolidMilestoneTrackerImpl.java:185) ~[iri-1.6.0-RELEASE.jar:na]
        at com.iota.iri.utils.thread.BoundedScheduledExecutorService.lambda$wrapTask$6(BoundedScheduledExecutorService.java:749) ~[iri-1.6.0-RELEASE.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_201]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_201]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_201]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_201]
Caused by: com.iota.iri.service.milestone.MilestoneException: failed to repair corrupted milestone with index #976637
        at com.iota.iri.service.milestone.impl.MilestoneServiceImpl.resetCorruptedMilestone(MilestoneServiceImpl.java:531) ~[iri-1.6.0-RELEASE.jar:na]
        at com.iota.iri.service.milestone.impl.MilestoneServiceImpl.resetCorruptedMilestone(MilestoneServiceImpl.java:159) ~[iri-1.6.0-RELEASE.jar:na]
        at com.iota.iri.service.milestone.impl.LatestSolidMilestoneTrackerImpl.repairCorruptedMilestone(LatestSolidMilestoneTrackerImpl.java:309) ~[iri-1.6.0-RELEASE.jar:na]
        at com.iota.iri.service.milestone.impl.LatestSolidMilestoneTrackerImpl.applySolidMilestoneToLedger(LatestSolidMilestoneTrackerImpl.java:207) ~[iri-1.6.0-RELEASE.jar:na]
        at com.iota.iri.service.milestone.impl.LatestSolidMilestoneTrackerImpl.trackLatestSolidMilestone(LatestSolidMilestoneTrackerImpl.java:156) ~[iri-1.6.0-RELEASE.jar:na]
        ... 9 common frames omitted
Caused by: com.iota.iri.service.snapshot.SnapshotException: failed to rollback last milestone
        at com.iota.iri.service.snapshot.impl.SnapshotServiceImpl.rollbackLastMilestone(SnapshotServiceImpl.java:386) ~[iri-1.6.0-RELEASE.jar:na]
        at com.iota.iri.service.snapshot.impl.SnapshotServiceImpl.rollBackMilestones(SnapshotServiceImpl.java:193) ~[iri-1.6.0-RELEASE.jar:na]
        at com.iota.iri.service.milestone.impl.MilestoneServiceImpl.resetCorruptedMilestone(MilestoneServiceImpl.java:524) ~[iri-1.6.0-RELEASE.jar:na]
        ... 13 common frames omitted
Caused by: com.iota.iri.service.snapshot.SnapshotException: failed to apply patch belonging to milestone #976637 (ZZYVLKZUWYZXJSSVMRYFOIADCJFADIR9PSOMMTOKKWQSYWJCJZQVBJVYWXRLKABZOM9JQKVPQSGOA9999)
        at com.iota.iri.service.snapshot.impl.SnapshotServiceImpl.rollbackLastMilestone(SnapshotServiceImpl.java:357) ~[iri-1.6.0-RELEASE.jar:na]
        ... 15 common frames omitted
01/24 07:55:39.663 [Latest Milestone Tracker] INFO  c.i.i.s.m.i.LatestMilestoneTrackerImpl - Processing milestone candidates (229257 remaining) ...
01/24 07:55:39.669 [Milestone Solidifier] INFO  c.i.i.s.m.MilestoneSolidifier - Solidifying milestone #976791 [10 / 79]
```

**Comment by dwjorgeb** [comment]
Having the same issue on 1.8.2. How did you solve it @grittibaenz ?

**Comment by kwek20** [comment]
@dwjorgeb right now there is no fix for this yet, we are investigating it.
I recommend starting from a db from https://dbfiles.iota.org/?prefix=mainnet/iri/1.8.2/

Sorry for the inconvenience!
