### ISSUE TITLE
NumberFormatException: --max-peers => MAX_INT

### ISSUE THREAD

**Issue by pinpong** [iotaledger/iri#131]
```
Exception in thread "main" java.lang.NumberFormatException: For input string: "2147483648"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:587)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.iota.iri.conf.Configuration.integer(Configuration.java:126)
	at com.iota.iri.conf.Configuration.integer(Configuration.java:138)
	at com.iota.iri.Iota.<init>(Iota.java:49)
	at com.iota.iri.IRI.main(IRI.java:53)

**Comment by jakubcech** [comment]
Related to #724
