### ISSUE TITLE
 Command Line Options --send-limit 100.0.0

### ISSUE THREAD

**Issue by pinpong** [iotaledger/iri#132]
````
java.lang.NumberFormatException: multiple points
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1914) ~[na:1.8.0_91]
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[na:1.8.0_91]
	at java.lang.Double.parseDouble(Double.java:538) ~[na:1.8.0_91]
	at com.iota.iri.conf.Configuration.doubling(Configuration.java:122) ~[iri-1.1.3.10.jar:na]
	at com.iota.iri.network.Node.init(Node.java:112) ~[iri-1.1.3.10.jar:na]
	at com.iota.iri.Iota.init(Iota.java:84) ~[iri-1.1.3.10.jar:na]
	at com.iota.iri.IRI.main(IRI.java:86) ~[iri-1.1.3.10.jar:na]

**Comment by jakubcech** [comment]
Related to #724 - the message should probably be more informative
