### ISSUE TITLE
MalformedJsonException

### ISSUE THREAD

**Issue by pinpong** [iotaledger/iri#134]
```
[XNIO-1 task-7] ERROR com.iota.iri.service.API - API Exception:
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 2 column 89 path $.
        at com.google.gson.Gson.fromJson(Gson.java:902) ~[iri-1.1.3.10.jar:na]
        at com.google.gson.Gson.fromJson(Gson.java:852) ~[iri-1.1.3.10.jar:na]
        at com.google.gson.Gson.fromJson(Gson.java:801) ~[iri-1.1.3.10.jar:na]
        at com.google.gson.Gson.fromJson(Gson.java:773) ~[iri-1.1.3.10.jar:na]
        at com.iota.iri.service.API.process(API.java:155) [iri-1.1.3.10.jar:na]
        at com.iota.iri.service.API.processRequest(API.java:147) [iri-1.1.3.10.jar:na]
        at com.iota.iri.service.API.access$000(API.java:81) [iri-1.1.3.10.jar:na]
        at com.iota.iri.service.API$1.handleRequest(API.java:135) [iri-1.1.3.10.jar:na]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:208) [iri-1.1.3.10.jar:na]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809) [iri-1.1.3.10.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: com.google.gson.stream.MalformedJsonException: Expected ':' at line 2 column 89 path $.
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[iri-1.1.3.10.jar:na]
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:530) ~[iri-1.1.3.10.jar:na]
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:425) ~[iri-1.1.3.10.jar:na]
        at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:55) ~[iri-1.1.3.10.jar:na]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[iri-1.1.3.10.jar:na]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187) ~[iri-1.1.3.10.jar:na]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[iri-1.1.3.10.jar:na]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[iri-1.1.3.10.jar:na]
        ... 12 common frames omitted
[XNIO-1 task-8] INFO  com.iota.iri.service.TipsManager - Reason to stop: TransactionViewModel is a tip

**Comment by alfredch** [comment]
Malformed input, which command did you execute?

**Comment by pinpong** [comment]
Maybe i forgot somewhere a `;`. Can't remember.
