### ISSUE TITLE
1.1.3.10 Neighbor DNS Refresher Thread Exception

### ISSUE THREAD

**Issue by dhughesbc** [iotaledger/iri#136]
This exception started occurring continuously for one of my neighbors' domains. It was creating about 600MB of output / minute. Restarting the node fixed it.

```
05/22 18:01:04.300 [pool-2-thread-3] INFO  com.iota.iri.network.Node - CHANGED IP for <REMOVED FROM ISSUE REPORT>.ddns.net! Updating...
05/22 18:01:04.300 [pool-2-thread-3] ERROR com.iota.iri.network.Node - Neighbor DNS Refresher Thread Exception:
java.lang.IllegalArgumentException: port out of range:-1
	at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143) ~[na:1.8.0_131]
	at java.net.InetSocketAddress.<init>(InetSocketAddress.java:224) ~[na:1.8.0_131]
	at com.iota.iri.network.Node.removeNeighbor(Node.java:647) ~[iri-1.1.3.10.jar:na]
	at com.iota.iri.network.Node.lambda$null$6(Node.java:171) ~[iri-1.1.3.10.jar:na]
	at java.util.Optional.ifPresent(Optional.java:159) ~[na:1.8.0_131]
	at com.iota.iri.network.Node.lambda$null$7(Node.java:170) ~[iri-1.1.3.10.jar:na]
	at java.util.Optional.ifPresent(Optional.java:159) ~[na:1.8.0_131]
	at com.iota.iri.network.Node.lambda$null$8(Node.java:158) ~[iri-1.1.3.10.jar:na]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890) ~[na:1.8.0_131]
	at com.iota.iri.network.Node.lambda$spawnNeighborDNSRefresherThread$9(Node.java:156) ~[iri-1.1.3.10.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
```

**Comment by mettenian** [comment]
Same error here and node crashed:

05/23 06:24:20.547 [pool-2-thread-3] ERROR com.iota.iri.network.Node - Neighbor DNS Refresher Thread Exception:
java.lang.IllegalArgumentException: port out of range:-1
        at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143) ~[na:1.8.0_131]
        at java.net.InetSocketAddress.<init>(InetSocketAddress.java:224) ~[na:1.8.0_131]
        at com.iota.iri.network.Node.removeNeighbor(Node.java:647) ~[iri-1.1.3.10.jar:na]
        at com.iota.iri.network.Node.lambda$null$6(Node.java:171) ~[iri-1.1.3.10.jar:na]
        at java.util.Optional.ifPresent(Optional.java:159) ~[na:1.8.0_131]
        at com.iota.iri.network.Node.lambda$null$7(Node.java:170) ~[iri-1.1.3.10.jar:na]
        at java.util.Optional.ifPresent(Optional.java:159) ~[na:1.8.0_131]
        at com.iota.iri.network.Node.lambda$null$8(Node.java:158) ~[iri-1.1.3.10.jar:na]
        at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890) ~[na:1.8.0_131]
        at com.iota.iri.network.Node.lambda$spawnNeighborDNSRefresherThread$9(Node.java:156) ~[iri-1.1.3.10.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fb888033b42, pid=15003, tid=0x00007fb7eb9f9700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x6d1b42]  jni_SetByteArrayRegion+0xc2
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /root/hs_err_pid15003.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Aborted

**Comment by alon-e** [comment]
fixed, https://github.com/iotaledger/iri/commit/0da313a889b68feef080f5b57e1cf17756b29f1f
awaiting release
