### ISSUE TITLE
Error while taking local snapshot

### ISSUE THREAD

**Issue by grittibaenz** [iotaledger/iri#1386]
### Bug description
After updating IRI from version `iri-1.5.6-RELEASE` to `iri-1.6.1-RELEASE`, the application kept logging `error while taking local snapshot`.
- To which directory is IRI trying to write this snapshot?

This error message keeps repeating every ~5 minutes after IRI is trying to generate solid entry points:
```
03/20 13:29:46.983 [Local Snapshots Monitor] INFO  c.i.i.s.s.impl.SnapshotServiceImpl - Taking local snapshot [analyzing old solid entry points]: 0.00% ...
03/20 13:29:46.983 [Local Snapshots Monitor] INFO  c.i.i.s.s.impl.SnapshotServiceImpl - Taking local snapshot [analyzing old solid entry points]: 100.00% ... [DONE]
03/20 13:29:46.983 [Local Snapshots Monitor] INFO  c.i.i.s.s.impl.SnapshotServiceImpl - Taking local snapshot [generating solid entry points]: 0.00% ...
03/20 13:29:52.472 [Local Snapshots Monitor] INFO  c.i.i.s.s.impl.SnapshotServiceImpl - Taking local snapshot [generating solid entry points]: 1.00% ...
03/20 13:29:58.752 [Local Snapshots Monitor] INFO  c.i.i.s.s.impl.SnapshotServiceImpl - Taking local snapshot [generating solid entry points]: 2.00% ...
03/20 13:30:01.754 [Local Snapshots Monitor] INFO  c.i.i.s.s.impl.SnapshotServiceImpl - Taking local snapshot [generating solid entry points]: 13.00% ...

<...>

03/20 13:35:31.833 [Local Snapshots Monitor] INFO  c.i.i.s.s.impl.SnapshotServiceImpl - Taking local snapshot [generating solid entry points]: 92.00% ...
03/20 13:35:34.678 [Local Snapshots Monitor] INFO  c.i.i.s.s.impl.SnapshotServiceImpl - Taking local snapshot [generating solid entry points]: 100.00% ... [DONE]
03/20 13:35:34.678 [Local Snapshots Monitor] INFO  c.i.i.s.s.impl.SnapshotServiceImpl - Taking local snapshot [processing seen milestones]: 0.00% ...
03/20 13:35:34.679 [Local Snapshots Monitor] INFO  c.i.i.s.s.impl.SnapshotServiceImpl - Taking local snapshot [processing seen milestones]: 100.00% ... [DONE]
03/20 13:35:34.679 [Local Snapshots Monitor] ERROR c.i.i.s.s.i.LocalSnapshotManagerImpl - error while taking local snapshot
com.iota.iri.service.snapshot.SnapshotException: failed to write the snapshot state file at mainnet.snapshot.state.tmp
        at com.iota.iri.service.snapshot.impl.SnapshotProviderImpl.writeSnapshotStateToDisk(SnapshotProviderImpl.java:396) ~[iri-1.6.1.jar:na]
        at com.iota.iri.service.snapshot.impl.SnapshotProviderImpl.writeSnapshotToDisk(SnapshotProviderImpl.java:140) ~[iri-1.6.1.jar:na]
        at com.iota.iri.service.snapshot.impl.SnapshotServiceImpl.persistLocalSnapshot(SnapshotServiceImpl.java:499) ~[iri-1.6.1.jar:na]
        at com.iota.iri.service.snapshot.impl.SnapshotServiceImpl.takeLocalSnapshot(SnapshotServiceImpl.java:226) ~[iri-1.6.1.jar:na]
        at com.iota.iri.service.snapshot.impl.LocalSnapshotManagerImpl.monitorThread(LocalSnapshotManagerImpl.java:140) [iri-1.6.1.jar:na]
        at com.iota.iri.service.snapshot.impl.LocalSnapshotManagerImpl.lambda$start$0(LocalSnapshotManagerImpl.java:110) [iri-1.6.1.jar:na]
        at com.iota.iri.utils.thread.ThreadUtils.lambda$spawnThread$0(ThreadUtils.java:76) ~[iri-1.6.1.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_201]
Caused by: java.nio.file.AccessDeniedException: mainnet.snapshot.state.tmp
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[na:1.8.0_201]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.8.0_201]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.8.0_201]
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[na:1.8.0_201]
        at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434) ~[na:1.8.0_201]
        at java.nio.file.Files.newOutputStream(Files.java:216) ~[na:1.8.0_201]
        at java.nio.file.Files.write(Files.java:3351) ~[na:1.8.0_201]
        at java.nio.file.Files.write(Files.java:3397) ~[na:1.8.0_201]
        at com.iota.iri.service.snapshot.impl.SnapshotProviderImpl.writeSnapshotStateToDisk(SnapshotProviderImpl.java:386) ~[iri-1.6.1.jar:na]
        ... 7 common frames omitted
```
After hours of running IRI it stopped working properly and now logs `resetting corrupted milestone`:
```
03/20 20:34:24.964 [Local Snapshots Monitor] INFO  c.i.i.s.s.impl.SnapshotServiceImpl - Taking local snapshot [generating solid entry points]: 94.00% ...
03/20 20:34:25.513 [Milestone Solidifier] INFO  c.i.i.s.m.MilestoneSolidifier - Solidifying milestone #934494 [3 / 3]
03/20 20:34:27.173 [pool-12-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 2199 , toReply = 0 / totalTransactions = 54836164
03/20 20:34:28.514 [Milestone Solidifier] INFO  c.i.i.s.m.MilestoneSolidifier - Solidifying milestone #933790 [3 / 3]
03/20 20:34:31.514 [Milestone Solidifier] INFO  c.i.i.s.m.MilestoneSolidifier - Solidifying milestone #933467 [3 / 3]
03/20 20:34:33.726 [Latest Milestone Tracker] INFO  c.i.i.s.m.i.LatestMilestoneTrackerImpl - Latest milestone has changed from #1029337 to #1029338
03/20 20:34:34.514 [Milestone Solidifier] INFO  c.i.i.s.m.MilestoneSolidifier - Solidifying milestone #934494 [3 / 3]
03/20 20:34:37.109 [Latest Solid Milestone Tracker] INFO  c.i.i.s.s.impl.SnapshotStateImpl - negative value for address HONFEITYSVHUKXWV9OMWPURUNGTXEZCKNLIJMVYFU9TPQAJGLVLDAHEUHBYIPQXYRWYMYYUJWZHDFM9AB: -16000000
03/20 20:34:37.109 [Latest Solid Milestone Tracker] INFO  c.i.i.s.m.impl.MilestoneServiceImpl - resetting corrupted milestone #1029338
03/20 20:34:37.174 [pool-12-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 2199 , toReply = 0 / totalTransactions = 54835817
03/20 20:34:37.514 [Milestone Solidifier] INFO  c.i.i.s.m.MilestoneSolidifier - Solidifying milestone #933790 [3 / 3]
03/20 20:34:38.030 [Latest Solid Milestone Tracker] INFO  c.i.i.s.s.impl.SnapshotStateImpl - negative value for address HONFEITYSVHUKXWV9OMWPURUNGTXEZCKNLIJMVYFU9TPQAJGLVLDAHEUHBYIPQXYRWYMYYUJWZHDFM9AB: -16000000
03/20 20:34:38.030 [Latest Solid Milestone Tracker] INFO  c.i.i.s.m.impl.MilestoneServiceImpl - resetting corrupted milestone #1029338
03/20 20:34:38.263 [Latest Solid Milestone Tracker] INFO  c.i.i.s.m.impl.MilestoneServiceImpl - resetting corrupted milestone #1029337
03/20 20:34:38.328 [Latest Solid Milestone Tracker] INFO  c.i.i.s.m.i.LatestSolidMilestoneTrackerImpl - Latest SOLID milestone index changed from #1029337 to #1029336
03/20 20:34:39.068 [Latest Solid Milestone Tracker] INFO  c.i.i.s.s.impl.SnapshotStateImpl - negative value for address HONFEITYSVHUKXWV9OMWPURUNGTXEZCKNLIJMVYFU9TPQAJGLVLDAHEUHBYIPQXYRWYMYYUJWZHDFM9AB: -16000000
03/20 20:34:39.068 [Latest Solid Milestone Tracker] INFO  c.i.i.s.m.impl.MilestoneServiceImpl - resetting corrupted milestone #1029338
03/20 20:34:39.304 [Latest Solid Milestone Tracker] INFO  c.i.i.s.m.impl.MilestoneServiceImpl - resetting corrupted milestone #1029337
03/20 20:34:39.362 [Latest Solid Milestone Tracker] INFO  c.i.i.s.m.impl.MilestoneServiceImpl - resetting corrupted milestone #1029336
03/20 20:34:39.645 [pool-14-thread-10] ERROR c.i.i.n.r.ReplicatorSinkProcessor - ***** NETWORK ALERT ***** No sink to apiHost 88.99.93.196:16100, reason: Socket is closed
03/20 20:34:40.284 [Latest Solid Milestone Tracker] INFO  c.i.i.s.s.impl.SnapshotStateImpl - negative value for address HONFEITYSVHUKXWV9OMWPURUNGTXEZCKNLIJMVYFU9TPQAJGLVLDAHEUHBYIPQXYRWYMYYUJWZHDFM9AB: -16000000
03/20 20:34:40.284 [Latest Solid Milestone Tracker] INFO  c.i.i.s.m.impl.MilestoneServiceImpl - resetting corrupted milestone #1029338
03/20 20:34:40.511 [Latest Solid Milestone Tracker] INFO  c.i.i.s.m.impl.MilestoneServiceImpl - resetting corrupted milestone #1029337
03/20 20:34:40.514 [Milestone Solidifier] INFO  c.i.i.s.m.MilestoneSolidifier - Solidifying milestone #933467 [3 / 3]
03/20 20:34:40.572 [Latest Solid Milestone Tracker] INFO  c.i.i.s.m.impl.MilestoneServiceImpl - resetting corrupted milestone #1029336
03/20 20:34:40.657 [Latest Solid Milestone Tracker] INFO  c.i.i.s.m.impl.MilestoneServiceImpl - resetting corrupted milestone #1029335
03/20 20:34:41.329 [Latest Solid Milestone Tracker] INFO  c.i.i.s.m.i.LatestSolidMilestoneTrackerImpl - Latest SOLID milestone index changed from #1029336 to #1029337
```

### IRI version
`iri-1.6.1-RELEASE`

### Hardware Spec
IRI is running inside of a Docker container on-top of a Linux virtual machine.
```
16 cores
16 GB memory
500 GB SSD
```

### Steps To Reproduce
1. Update IRI to version `iri-1.6.1-RELEASE`
2. Start IRI with the following memory settings:
```
/app/jdk/current/bin/java -XX:+CrashOnOutOfMemoryError -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses -XX:+CMSParallelRemarkEnabled -XX:+DisableAttachMechanism -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:MaxMetaspaceSize=30m -Xmx6G -Xms2G -Djava.net.preferIPv4Stack=true -jar /app/iri/bin/iri-1.6.1-RELEASE.jar -c /app/iri/conf/iri.ini -p 9000 --remote
```
3. Wait and "_hope_" to see the error message.

### Expected behaviour
An update to IRI version `iri-1.6.1-RELEASE` should not result in this error and a potential database corruption.

### Other
Please find the configuration below:
```
[IRI]
PORT = 14265
UDP_RECEIVER_PORT = 14600
TCP_RECEIVER_PORT = 15600
API_HOST = 0.0.0.0
IXI_DIR = /app/iri/ixi
HEADLESS = true
DEBUG = false
TESTNET = false
DB_PATH = /data/iri/db
DB_LOG_PATH = /data/iri/log
SPENT_ADDRESSES_DB_PATH = /data/iri/spent-addresses-db
SPENT_ADDRESSES_DB_LOG_PATH = /data/iri/spent-addresses-log
RESCAN_DB = false
ZMQ_ENABLED = true
ZMQ_PORT = 5556

REMOTE_LIMIT_API = "removeNeighbors, addNeighbors, getNeighbors, setApiRateLimit"

LOCAL_SNAPSHOTS_ENABLED = true
LOCAL_SNAPSHOTS_PRUNING_ENABLED = true
LOCAL_SNAPSHOTS_DEPTH = 100
LOCAL_SNAPSHOTS_PRUNING_DELAY = 40000
LOCAL_SNAPSHOTS_INTERVAL_SYNCED = 10
LOCAL_SNAPSHOTS_INTERVAL_UNSYNCED = 1000

#NEIGHBORS =
```

#### Updating milestones
![image](https://user-images.githubusercontent.com/4578443/54738439-9525f500-4bb4-11e9-8e99-a9335023d6a0.png)

**Comment by GalRogozinski** [comment]
`Caused by: java.nio.file.AccessDeniedException: mainnet.snapshot.state.tmp`
You have to give permission or mount a volume to docker.
It is not a bug though

@jakubcech we may need to update documentations with docker

**Comment by grittibaenz** [comment]
IRI has permissions to write to the following directories:
`DB_PATH, DB_LOG_PATH, SPENT_ADDRESSES_DB_PATH, SPENT_ADDRESSES_DB_LOG_PATH`

We bind mount the following directory into the Docker container:
`"Binds": ["/data/iri/:/data/iri/:rw"]`

It used to work with these settings until version `1.5.6`. Is there any other location IRI is writing to?

**Comment by grittibaenz** [comment]
Are there any other locations IRI is writing to? Am I missing an important configuration in my `iri.ini`?

Thank you for your help.

**Comment by jakubcech** [comment]
Is it failing on any other file than `mainnet.snapshot.state.tmp` for you now? If not, then use the configuration flag `LOCAL_SNAPSHOTS_BASE_PATH`. This is where the snapshot files are written to, they will default to the base path (where you run the .jar), but you may want to configure it to write to a different directory seeing how you set things up. 

You can specify a directory for the snapshot files to be added to by doing the following: /, which results in folderpath/<filename.snapshot.meta.>

You can see the description in the docs at the very bottom of the page:
https://docs.iota.org/docs/iri/0.1/references/iri-configuration-options

**Comment by grittibaenz** [comment]
@jakubcech: many thanks for pointing out this parameter. I somehow missed it when going through the `--help` command.

It would be perfectly mentioned there as well:
```
/app/jdk/current/bin/java -jar /app/iri/bin/iri-1.6.1.jar --help

    --local-snapshots-base-path
      Path to the snapshot files (without file extensions).
```

Apologies for causing extra work on your end. I will test the configuration today and close the ticket right afterwards.

Many thanks again!

**Comment by grittibaenz** [comment]
Again many thanks for your help. The setting works as expected.

**Comment by jakubcech** [comment]
Thanks @grittibaenz!
