### ISSUE TITLE
IllegalArgumentException: port out of range:-1

### ISSUE THREAD

**Issue by pinpong** [iotaledger/iri#142]
````
[pool-2-thread-3] ERROR com.iota.iri.network.Node - Neighbor DNS Refresher Thread Exception:
java.lang.IllegalArgumentException: port out of range:-1
at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143) ~[na:1.8.0_131]
at java.net.InetSocketAddress.<init>(InetSocketAddress.java:224) ~[na:1.8.0_131]
at com.iota.iri.network.Node.removeNeighbor(Node.java:651) ~[IRI.jar:na]
at com.iota.iri.network.Node.lambda$null$6(Node.java:171) ~[IRI.jar:na]
at java.util.Optional.ifPresent(Optional.java:159) ~[na:1.8.0_131]
at com.iota.iri.network.Node.lambda$null$7(Node.java:170) ~[IRI.jar:na]
at java.util.Optional.ifPresent(Optional.java:159) ~[na:1.8.0_131]
at com.iota.iri.network.Node.lambda$null$8(Node.java:158) ~[IRI.jar:na]
at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890) ~at com.iota.iri.network.Node.lambda$spawnNeighborDNSRefresherThread$9(Node.java:156) ~[IRI.jar:na]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_131]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_131]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]

**Comment by alfredch** [comment]
Similar or same as #136

**Comment by alon-e** [comment]
Duplicate
