### ISSUE TITLE
API Exception: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by pinpong** [iotaledger/iri#143]
```[XNIO-1 task-14] ERROR com.iota.iri.service.API - API Exception: 
java.lang.ArrayIndexOutOfBoundsException: null
	at java.lang.System.arraycopy(Native Method) ~[na:1.8.0_91]
	at com.iota.iri.model.Hash.<init>(Hash.java:35) ~[IRI.jar:na]
	at com.iota.iri.model.Hash.<init>(Hash.java:40) ~[IRI.jar:na]
	at com.iota.iri.model.Hash.<init>(Hash.java:44) ~[IRI.jar:na]
	at com.iota.iri.service.API.findTransactionStatement(API.java:567) [IRI.jar:na]
	at com.iota.iri.service.API.process(API.java:228) [IRI.jar:na]
	at com.iota.iri.service.API.processRequest(API.java:147) [IRI.jar:na]
	at com.iota.iri.service.API.access$000(API.java:81) [IRI.jar:na]
	at com.iota.iri.service.API$1.handleRequest(API.java:135) [IRI.jar:na]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:208) [IRI.jar:na]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809) [IRI.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]

**Comment by jakubcech** [comment]
Shouldn't happen anymore, reopen if it still does
