### ISSUE TITLE
API exception in GUI 2.2.3

### ISSUE THREAD

**Issue by willowfoot** [iotaledger/iri#147]
Got a API Exception that flashed on screen trying to log in:

05/31 18:09:33.462 [XNIO-1 task-21] ERROR com.iota.iri.service.API - API Exception: 
java.lang.NullPointerException: null
	at com.iota.iri.service.API.exhaustiveSearchWithinIndex(API.java:518) [iri.jar:na]
	at com.iota.iri.service.API.getNewInclusionStateStatement(API.java:503) [iri.jar:na]
	at com.iota.iri.service.API.process(API.java:265) [iri.jar:na]
	at com.iota.iri.service.API.processRequest(API.java:147) [iri.jar:na]
	at com.iota.iri.service.API.access$000(API.java:81) [iri.jar:na]
	at com.iota.iri.service.API$1.handleRequest(API.java:135) [iri.jar:na]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:208) [iri.jar:na]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809) [iri.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]

**Comment by willowfoot** [comment]
same error happened with 2.2.4 ...

**Comment by yillkid** [comment]
Same as dev branch:
 [XNIO-1 task-24] ERROR com.iota.iri.service.API - API Exception: 
java.lang.NullPointerException: null
	at com.iota.iri.service.API.exhaustiveSearchWithinIndex(API.java:555) [iri-1.2.4.jar:na]
	at com.iota.iri.service.API.getNewInclusionStateStatement(API.java:540) [iri-1.2.4.jar:na]
	at com.iota.iri.service.API.process(API.java:279) [iri-1.2.4.jar:na]

**Comment by jakubcech** [comment]
Resolved
