### ISSUE TITLE
API Exception | IRI 1.1.2 mainnet

### ISSUE THREAD

**Issue by mettenian** [iotaledger/iri#15]
14:14:09.069 [XNIO-1 task-49] ERROR com.iota.iri.service.API - API Exception:
java.lang.ArrayIndexOutOfBoundsException: -1586328724
       at com.iota.iri.service.storage.StorageAddresses.addressPointer(StorageAddresses.java:80)
       at com.iota.iri.service.API.findTransactionStatement(API.java:349)
       at com.iota.iri.service.API.process(API.java:140)
       at com.iota.iri.service.API.processRequest(API.java:105)
       at com.iota.iri.service.API.access$000(API.java:71)
       at com.iota.iri.service.API$1.handleRequest(API.java:92)
       at io.undertow.server.Connectors.executeRootHandler(Connectors.java:208)
       at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
       at java.lang.Thread.run(Unknown Source)

**Comment by domschiener** [comment]
@mettenian can you share the full API call that you made?

**Comment by alfredch** [comment]
Here is the command:
{ command: 'getInclusionStates',
  transactions: [ 'HZC9AIBMYJVTAJJYSQQDLVULMKFQQMWLDDULK9CJNTWUO9ZUXZSJLFG9PSPLC9KDSFNMGQIRCXJLX9999' ],
  tips: [ '9ILBHPYUKXWIQTILZBXJSBOTNFKIIXUIWWDON9NMVQLYNTJU9VRKB9XTVRHRGMRUPOQRMRSIDFY999999' ] }

RETURN MESSAGE:
{"error":"The subtangle is not solid","duration":73}

**Comment by alfredch** [comment]
One of the problems is possible: after an IRI re-start, the 'latest solid subtangle index' is not updated immediately by a network message.
In the time between start and update, IRI should take this into account and return a friendly information instead of lengthy exception and misleading error message.

**Comment by davassi** [comment]
fixed in dev branch
