### ISSUE TITLE
node crashed | 1.1.4.1

### ISSUE THREAD

**Issue by mettenian** [iotaledger/iri#151]
06/03 03:10:43.581 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 84 , toBroadcast = 2 , toRequest = 184 , toReply = 0 / totalTransactions = 1337730
06/03 03:10:58.887 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 84 , toBroadcast = 2 , toRequest = 184 , toReply = 0 / totalTransactions = 1337730
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f811ce9cb42, pid=18862, tid=0x00007f8086af3700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x6d1b42]  jni_SetByteArrayRegion+0xc2
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /root/hs_err_pid18862.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Aborted

**Comment by rajivshah3** [comment]
I had the same issue:
`Exception in thread "Solid Milestone Tracker" 06/04 21:12:47.839 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 35 , toBroadcast = 0 , toRequest = 9756 , toReply = 0 / totalTransactions = 1129145
java.lang.OutOfMemoryError: Java heap space
	at com.iota.iri.model.Transaction.read(Transaction.java:43)
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.get(RocksDBPersistenceProvider.java:186)
	at com.iota.iri.storage.Tangle.load(Tangle.java:41)
	at com.iota.iri.controllers.TransactionViewModel.fromHash(TransactionViewModel.java:89)
	at com.iota.iri.TransactionValidator.checkSolidity(TransactionValidator.java:111)
	at com.iota.iri.Milestone.updateLatestSolidSubtangleMilestone(Milestone.java:175)
	at com.iota.iri.Milestone.lambda$init$1(Milestone.java:98)
	at com.iota.iri.Milestone$$Lambda$11/1264413185.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fe0d6fb3b42, pid=18472, tid=0x00007fe0a1b35700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x6d1b42]  jni_SetByteArrayRegion+0xc2
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/ubuntu/iri/target/hs_err_pid18472.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
`

**Comment by rajivshah3** [comment]
I had the same issue:

> 
Exception

 in thread "Solid Milestone Tracker" 06/04 21:12:47.839 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 35 , toBroadcast = 0 , toRequest = 9756 , toReply = 0 / totalTransactions = 1129145
java.lang.OutOfMemoryError: Java heap space
	at com.iota.iri.model.Transaction.read(Transaction.java:43)
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.get(RocksDBPersistenceProvider.java:186)
	at com.iota.iri.storage.Tangle.load(Tangle.java:41)
	at com.iota.iri.controllers.TransactionViewModel.fromHash(TransactionViewModel.java:89)
	at com.iota.iri.TransactionValidator.checkSolidity(TransactionValidator.java:111)
	at com.iota.iri.Milestone.updateLatestSolidSubtangleMilestone(Milestone.java:175)
	at com.iota.iri.Milestone.lambda$init$1(Milestone.java:98)
	at com.iota.iri.Milestone$$Lambda$11/1264413185.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fe0d6fb3b42, pid=18472, tid=0x00007fe0a1b35700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x6d1b42]  jni_SetByteArrayRegion+0xc2
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/ubuntu/iri/target/hs_err_pid18472.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

**Comment by rajivshah3** [comment]
Exception in thread "Solid Milestone Tracker" 06/04 21:12:47.839 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 35 , toBroadcast = 0 , toRequest = 9756 , toReply = 0 / totalTransactions = 1129145
java.lang.OutOfMemoryError: Java heap space
	at com.iota.iri.model.Transaction.read(Transaction.java:43)
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.get(RocksDBPersistenceProvider.java:186)
	at com.iota.iri.storage.Tangle.load(Tangle.java:41)
	at com.iota.iri.controllers.TransactionViewModel.fromHash(TransactionViewModel.java:89)
	at com.iota.iri.TransactionValidator.checkSolidity(TransactionValidator.java:111)
	at com.iota.iri.Milestone.updateLatestSolidSubtangleMilestone(Milestone.java:175)
	at com.iota.iri.Milestone.lambda$init$1(Milestone.java:98)
	at com.iota.iri.Milestone$$Lambda$11/1264413185.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fe0d6fb3b42, pid=18472, tid=0x00007fe0a1b35700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x6d1b42]  jni_SetByteArrayRegion+0xc2
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/ubuntu/iri/target/hs_err_pid18472.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```
