### ISSUE TITLE
node crashed | 1.1.4.2

### ISSUE THREAD

**Issue by mettenian** [iotaledger/iri#155]
`06/05 13:17:38.141 [Solid Milestone Tracker] INFO  com.iota.iri.Milestone - Latest SOLID SUBTANGLE milestone has changed from #58380 to #58381
06/05 13:17:48.741 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 54 , toBroadcast = 0 , toRequest = 4 , toReply = 982 / totalTransactions = 2382234
Exception in thread "Latest Milestone Tracker" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at com.iota.iri.model.Hash.fullRead(Hash.java:119)
        at com.iota.iri.model.Hash.<init>(Hash.java:24)
        at com.iota.iri.model.Hashes.read(Hashes.java:28)
        at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.get(RocksDBPersistenceProvider.java:186)
        at com.iota.iri.storage.Tangle.load(Tangle.java:41)
        at com.iota.iri.controllers.AddressViewModel.load(AddressViewModel.java:30)
        at com.iota.iri.Milestone.findNewMilestones(Milestone.java:196)
        at com.iota.iri.Milestone.updateLatestMilestone(Milestone.java:120)
        at com.iota.iri.Milestone.lambda$init$0(Milestone.java:68)
        at com.iota.iri.Milestone$$Lambda$10/23211803.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:748)
06/05 13:17:59.387 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 79 , toBroadcast = 0 , toRequest = 4 , toReply = 983 / totalTransactions = 2382291
06/05 13:18:09.721 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 11 , toBroadcast = 0 , toRequest = 2 , toReply = 866 / totalTransactions = 2382350
06/05 13:18:13.858 [XNIO-1 task-13] INFO  com.iota.iri.service.TipsManager - Reason to stop: !checkSolidity
06/05 13:18:13.858 [XNIO-1 task-13] INFO  com.iota.iri.service.TipsManager - Tx traversed to find tip: 11
06/05 13:18:21.012 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 47 , toBroadcast = 0 , toRequest = 0 , toReply = 977 / totalTransactions = 2382389
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f929598cb42, pid=8909, tid=0x00007f9241138700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x6d1b42]  jni_SetByteArrayRegion+0xc2
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /root/hs_err_pid8909.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Aborted
`

**Comment by alfredch** [comment]
Could you please complete the issue report with this information so that we can categorize it better:
- OS?
- Java heap size configured in the startup command
- Total system RAM
- Type of storage device.

**Comment by mettenian** [comment]
```
06/06 02:23:51.404 [Latest Milestone Tracker] INFO  com.iota.iri.Milestone - Latest milestone has changed from #59182 to #59183
06/06 02:23:52.700 [Solid Milestone Tracker] INFO  com.iota.iri.Milestone - Latest SOLID SUBTANGLE milestone has changed from #59182 to #59183
06/06 02:23:54.605 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 0 , toReply = 0 / totalTransactions = 2601007
06/06 02:24:05.139 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 1 , toBroadcast = 0 , toRequest = 0 , toReply = 1 / totalTransactions = 2601057
06/06 02:24:15.339 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 6 , toBroadcast = 0 , toRequest = 0 , toReply = 8 / totalTransactions = 2601103
06/06 02:24:25.556 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 1 , toBroadcast = 0 , toRequest = 0 , toReply = 1 / totalTransactions = 2601135
06/06 02:24:35.576 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 32 , toBroadcast = 0 , toRequest = 0 , toReply = 35 / totalTransactions = 2601174
06/06 02:24:51.503 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 14 , toBroadcast = 0 , toRequest = 0 , toReply = 35 / totalTransactions = 2601181
06/06 02:25:12.056 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 16 , toBroadcast = 0 , toRequest = 0 , toReply = 37 / totalTransactions = 2601181
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fe95793db42, pid=27929, tid=0x00007fe8f38f8700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x6d1b42]  jni_SetByteArrayRegion+0xc2
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /root/hs_err_pid27929.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Aborted

```

**Comment by mettenian** [comment]
CPU vCores: 4
Maxx-RAM (if available): 8 GB
RAM (at all times): 4 GB
HP 3PAR Storage (SSD/HDD): 500 GB

**Comment by mettenian** [comment]
first crash no heap size
second -Xms2g -Xmx2g
now testing with -Xms3g -Xmx3g

**Comment by alfredch** [comment]
Will be interesting to see if 3g helps!

**Comment by mettenian** [comment]
1.1.4.3 with -Xms3g -Xmx3g is stable for me

**Comment by mettenian** [comment]
1.2.0, no heap size, so far stable
