### ISSUE TITLE
IPv6 node addresses cause an error

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/iri#160]
The following happened when someone gave me an IPv6 address:
```
06/07 16:50:16.704 [XNIO-1 task-11] INFO  com.iota.iri.service.API - Removing neighbor: udp://IPv4-1:12000
06/07 16:50:16.711 [XNIO-1 task-11] INFO  com.iota.iri.service.API - Removing neighbor: udp://IPv4-2:19780
06/07 16:50:16.713 [XNIO-1 task-11] INFO  com.iota.iri.service.API - Removing neighbor: udp://IPv4-3:14600
06/07 16:50:16.713 [XNIO-1 task-11] INFO  com.iota.iri.service.API - Removing neighbor: udp://IPv4-4:14265
06/07 16:50:17.032 [XNIO-1 task-12] ERROR com.iota.iri.service.API - API Exception: 
java.lang.IllegalArgumentException: hostname can't be null
	at java.net.InetSocketAddress.checkHost(InetSocketAddress.java:149) ~[na:1.8.0_131]
	at java.net.InetSocketAddress.<init>(InetSocketAddress.java:216) ~[na:1.8.0_131]
	at com.iota.iri.service.API.addNeighborsStatement(API.java:775) [iri-1.1.4.3.jar:na]
	at com.iota.iri.service.API.process(API.java:183) [iri-1.1.4.3.jar:na]
	at com.iota.iri.service.API.processRequest(API.java:149) [iri-1.1.4.3.jar:na]
	at com.iota.iri.service.API.access$000(API.java:81) [iri-1.1.4.3.jar:na]
	at com.iota.iri.service.API$1.handleRequest(API.java:137) [iri-1.1.4.3.jar:na]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:208) [iri-1.1.4.3.jar:na]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809) [iri-1.1.4.3.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
```
(Addresses changed to protect user security)
The address was entered using the API, entered exactly as the user gave it to me (udp://0000:0aa0:0000:0:a00a:a000:0aa0:00a0:14200). I tried to fix it by importing the Inet6Address class and then using getHostAddress() to convert it to a string with proper [] brackets but didn't know what to do next.

**Comment by paulhandy** [comment]
You need to use brackets around the ipv6 address, as in udp://[0000:0aa0:..:0]:14200
