### ISSUE TITLE
Do not save redundant transaction data in the DB

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1626]
### Description
Currently we store the transactions in their full size, even though most of the transactions don't really make use of all the field data. Similar to what we do in networking with compaction and expansion. 

### Motivation
Significantly save database space.

### Requirements
1. Truncate Tx before persisting
2. Expand Tx when loading

# Implementation Details
1. Reuse `Protocol` logic (`expandTx`, `truncateTx`).
2. Change `Transaction` class: `read()` and `bytes()`

**Comment by GalRogozinski** [comment]
Note that if we use an old version of IRI on a DB that was created with a version supporting this feature, we may run into an error. This is because the old IRI will try to copy more bytes then available:

```
java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.$$YJP$$arraycopy(Native Method)
	at java.lang.System.arraycopy(System.java)
	at com.iota.iri.model.persistables.Transaction.read(Transaction.java:103)
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.get(RocksDBPersistenceProvider.java:155)
	at com.iota.iri.storage.Tangle.load(Tangle.java:88)
	at com.iota.iri.controllers.TransactionViewModel.fromHash(TransactionViewModel.java:132)
	at com.iota.iri.controllers.TransactionViewModel.getTrunkTransaction(TransactionViewModel.java:305)
	at com.iota.iri.BundleValidator.loadTransactionsFromTangle(BundleValidator.java:399)
	at com.iota.iri.BundleValidator.validate(BundleValidator.java:159)
	at com.iota.iri.BundleValidator.validate(BundleValidator.java:113)
	at com.iota.iri.service.milestone.impl.MilestoneServiceImpl.validateMilestone(MilestoneServiceImpl.java:165
```
