### ISSUE TITLE
Crashed test WalkValidatorImplTest

### ISSUE THREAD

**Issue by DieegoPeri** [iotaledger/iri#1650]
The issue tracker is only for reporting bugs or submitting feature requests.
If you need technical assistance for running a node please consult the #fullnode channel on Discord (https://discord.iota.org) or https://forum.helloiota.com/Technology/Help.
If you have general questions on IOTA you can go to https://iota.stackexchange.com/, https://helloiota.com/, or browse Discord channels (https://discord.iota.org).

### Bug description
mvn clean compile && mvn package fails.

### IRI version
2.1.8
[This](https://github.com/f-ben/iri/blob/release-v1.8.2/pom.xml) pom.xml

### Hardware Spec
Raspberry Pi 4 4GB RAM.
Raspbian Buster Lite.
Java 8 (openjdk 8) 64 bits, ARM.
Running from SSH.

### Steps To Reproduce
1. Installed Java 8 with sudo apt install openjdk-8-jdk openjdk-8-jre
2. Followed [this](https://pastebin.com/bs5mGan4) guide for cloning rocksdb and iri, and installing it.
3. Run the last command (mvn clean compile && mvn package)

### Expected behaviour
Should build.

### Actual behaviour
Got an error during the building.

### Errors
[WARNING] Some problems were encountered while building the effective model for com.iota:iri:jar:1.8.2
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: net.openhft:zero-allocation-hashing:jar -> version ${zero-allocation-hashing.version} vs 0.8 @ line 256, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
.
.
.
Building process...
.
.
.
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:39 min
[INFO] Finished at: 2019-10-30T22:20:07Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project iri: There are test failures.
[ERROR]
[ERROR] Please refer to /home/pi/iri/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/pi/iri && /usr/lib/jvm/java-8-openjdk-armhf/jre/bin/java -javaagent:/home/pi/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/home/pi/iri/target/jacoco.exec -jar /home/pi/iri/target/surefire/surefirebooter5761060097784388473.jar /home/pi/iri/target/surefire 2019-10-30T22-18-42_870-jvmRun1 surefire5305988117582168717tmp surefire_08799561699579072193tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 134
[ERROR] Crashed tests:
[ERROR] com.iota.iri.service.tipselection.impl.WalkValidatorImplTest
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/pi/iri && /usr/lib/jvm/java-8-openjdk-armhf/jre/bin/java -javaagent:/home/pi/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/home/pi/iri/target/jacoco.exec -jar /home/pi/iri/target/surefire/surefirebooter5761060097784388473.jar /home/pi/iri/target/surefire 2019-10-30T22-18-42_870-jvmRun1 surefire5305988117582168717tmp surefire_08799561699579072193tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 134
[ERROR] Crashed tests:
[ERROR] com.iota.iri.service.tipselection.impl.WalkValidatorImplTest
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:671)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:278)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:244)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1149)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:978)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:854)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by lucianosilvi** [comment]
No news about this issue?  I'm also trying the same process, having different issues, also looking for a resolution

**Comment by GalRogozinski** [comment]
What version of maven are you guys using?

I suppose you can do `mvn clean package -DskipTests` as a hack...
The tests pass in our CI system so I am less worried

**Comment by lucianosilvi** [comment]
Maven 3.6 here.
I used that flag, but then, when trying to run the target I got:
 

> $ java -jar iri-1.8.2.jar 
> Logging - property 'logging-level' set to: [INFO]
> 11/19 10:30:50.172 [main] INFO  IRI$IRILauncher:192 - Configuration is created using command line args only
> 11/19 10:30:50.184 [main] INFO  IRI$IRILauncher:193 - parsed the following cmd args: []
> 11/19 10:30:50.190 [main] INFO  IRI$IRILauncher:122 - Welcome to IRI 1.8.2
> 11/19 10:32:05.521 [main] INFO  RocksDBPersistenceProvider:126 - Initializing Database on spent-addresses-db
> Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni5874159728039879283.so: /tmp/librocksdbjni5874159728039879283.so: cannot open shared object file: No such file or directory (Possible cause: can't load IA 32-bit .so on a ARM-bit platform)
> 	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
> 	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
> 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
> 	at java.lang.Runtime.load0(Runtime.java:809)
> 	at java.lang.System.load(System.java:1086)
> 	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:79)
> 	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:57)
> 	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:63)
> 	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:34)
> 	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.initDB(RocksDBPersistenceProvider.java:471)
> 	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.init(RocksDBPersistenceProvider.java:127)
> 	at com.iota.iri.service.spentaddresses.impl.SpentAddressesProviderImpl.init(SpentAddressesProviderImpl.java:58)
> 	at com.iota.iri.Iota.initDependencies(Iota.java:154)
> 	at com.iota.iri.Iota.init(Iota.java:173)
> 	at com.iota.iri.IRI$IRILauncher.main(IRI.java:135)
> 	at com.iota.iri.IRI.main(IRI.java:64)
>
