### ISSUE TITLE
Adding faulty neighbors no feedback and repeating errors in logs

### ISSUE THREAD

**Issue by nuriel77** [iotaledger/iri#1678]
### Bug description
Adding a neighbor with a faulty (e.g. out-of-range) port causes an exception (seen in IRI logs) and messages keep appearing about port out of range.

```
curl http://localhost:14265 -XPOST -H 'Content-Type: application/json' -H 'X-IOTA-API-Version: 1' -d '{"command": "addNeighbors", "uris": ["tcp://google.com:90000"]}'
{"addedNeighbors":1,"duration":6}
```
IRI Logs:

```
Dec 01 20:51:43 snap docker[10915]: Exception in thread "Neighbor Router" java.lang.IllegalArgumentException: port out of range:90000
Dec 01 20:51:43 snap docker[10915]:         at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143)
Dec 01 20:51:43 snap docker[10915]:         at java.net.InetSocketAddress.<init>(InetSocketAddress.java:224)
Dec 01 20:51:43 snap docker[10915]:         at com.iota.iri.network.NeighborRouterImpl.lambda$connectToWantedNeighbors$2(NeighborRouterImpl.java:614)
Dec 01 20:51:43 snap docker[10915]:         at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
Dec 01 20:51:43 snap docker[10915]:         at java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:404)
Dec 01 20:51:43 snap docker[10915]:         at com.iota.iri.network.NeighborRouterImpl.connectToWantedNeighbors(NeighborRouterImpl.java:613)
Dec 01 20:51:43 snap docker[10915]:         at com.iota.iri.network.NeighborRouterImpl.route(NeighborRouterImpl.java:178)
Dec 01 20:51:43 snap docker[10915]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Dec 01 20:51:43 snap docker[10915]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Dec 01 20:51:43 snap docker[10915]:         at java.lang.Thread.run(Thread.java:748)
Dec 01 20:51:44 snap docker[10915]: 12/01 19:51:44.123 [XNIO-1 task-2] ERROR API:291 - Unexpected API Exception: port out of range:90000
Dec 01 20:51:44 snap docker[10915]: 12/01 19:51:44.747 [XNIO-1 task-3] ERROR API:291 - Unexpected API Exception: port out of range:90000
Dec 01 20:51:49 snap docker[10915]: 12/01 19:51:49.129 [XNIO-1 task-12] ERROR API:291 - Unexpected API Exception: port out of range:90000
```
After a while you will notice these errors just clutter the logs and don't stop:
```
Dec 01 20:55:50 snap docker[10915]: 12/01 19:55:50.007 [XNIO-1 task-15] ERROR API:291 - Unexpected API Exception: port out of range:90000
Dec 01 20:55:54 snap docker[10915]: 12/01 19:55:54.121 [XNIO-1 task-7] ERROR API:291 - Unexpected API Exception: port out of range:90000
Dec 01 20:55:55 snap docker[10915]: 12/01 19:55:55.017 [XNIO-1 task-5] ERROR API:291 - Unexpected API Exception: port out of range:90000
Dec 01 20:55:59 snap docker[10915]: 12/01 19:55:59.123 [XNIO-1 task-12] ERROR API:291 - Unexpected API Exception: port out of range:90000
```

### IRI version
What version are you running?
1.8.2-RELEASE

### Hardware Spec
VPS

### Steps To Reproduce
As shown above, add a neighbor with a port out of range (>65535)

Only way to clear this seems by restarting IRI

### Expected behaviour
Reject the faulty neighbor with a message (maybe 400 bad request?)

### Actual behaviour
IRI reported neighbor added, and the rest I've explained above (+examples from the logs)

### Errors
Shown above.

**Comment by GalRogozinski** [comment]
Added max port validation of 65535
