### ISSUE TITLE
ECMAException

### ISSUE THREAD

**Issue by pinpong** [iotaledger/iri#169]
Found this in the logfile

```
java[8301]: jdk.nashorn.internal.runtime.ECMAException: TypeError: Cannot read property "index" from undefined
java[8301]:         at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57) ~[nashorn.jar:na]
java[8301]:         at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213) ~[nashorn.jar:na]
java[8301]:         at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185) ~[nashorn.jar:na]
java[8301]:         at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172) ~[nashorn.jar:na]
java[8301]:         at jdk.nashorn.internal.runtime.Undefined.get(Undefined.java:157) ~[nashorn.jar:na]
java[8301]:         at jdk.nashorn.internal.scripts.Script$Recompilation$1$225A$\^eval\_.getSnapshot(<eval>:9) ~[na:na]
java[8301]:         at com.iota.iri.service.CallableRequest$$NashornJavaAdapter.call(Unknown Source) ~[na:na]
 java[8301]:         at com.iota.iri.IXI.processCommand(IXI.java:124) ~[IRI.jar:na]
java[8301]:         at com.iota.iri.service.API.process(API.java:367) [IRI.jar:na]
java[8301]:         at com.iota.iri.service.API.processRequest(API.java:154) [IRI.jar:na]
java[8301]:         at com.iota.iri.service.API.access$000(API.java:80) [IRI.jar:na]
java[8301]:         at com.iota.iri.service.API$1.handleRequest(API.java:142) [IRI.jar:na]
java[8301]:         at io.undertow.server.Connectors.executeRootHandler(Connectors.java:208) [IRI.jar:na]
java[8301]:         at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809) [IRI.jar:na]
java[8301]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
java[8301]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
java[8301]:         at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

**Comment by paulhandy** [comment]
I wonder what the api call was. Or do you have an IXI installed?

**Comment by pinpong** [comment]
I would say the command was 
```
curl http://localhost:14265 -X POST -H 'Content-Type: application/json'   -d '{"command": "Snapshot.getState"}'

**Comment by paulhandy** [comment]
Alright, this is an issue for Snapshot.IXI, then.
