### ISSUE TITLE
IndexOutOfBoundsException in testnet

### ISSUE THREAD

**Issue by alfredch** [iotaledger/iri#17]
After 10 hours of usage incl. spamming, suddenly this (even after the restart)
11:51:04.957 [main] INFO com.iota.iri.IRI - Welcome to IRI Testnet 1.1.2
11:51:04.989 [main] INFO com.iota.iri.IRI - Headless feature is WIP...
11:51:04.992 [main] DEBUG com.iota.iri.conf.Configuration - Setting HEADLESS with true
11:51:04.992 [main] DEBUG com.iota.iri.conf.Configuration - Setting API_PORT with 14265
11:51:04.992 [main] DEBUG com.iota.iri.conf.Configuration - Setting NEIGHBORS with udp://138.68.90.186:14265 udp://82.241.71.230:14265 udp://ahtest.ddns.net:14265 udp://178.5.125.120:14265 udp://66.11.119.77:14265
11:51:05.524 [pool-1-thread-1] INFO com.iota.iri.service.Node - Spawing Receiver Thread
11:51:05.529 [pool-1-thread-3] INFO com.iota.iri.service.Node - Spawning Tips Requester Thread
11:51:05.530 [pool-1-thread-2] INFO com.iota.iri.service.Node - Spawning Broadcaster Thread
11:51:05.669 [main] DEBUG org.jboss.logging - Logging Provider: org.jboss.logging.Slf4jLoggerProvider
11:51:05.672 [main] DEBUG io.undertow - starting undertow server io.undertow.Undertow@4ec6a292
11:51:05.687 [main] INFO org.xnio - XNIO version 3.3.6.Final
11:51:05.720 [main] INFO org.xnio.nio - XNIO NIO Implementation Version 3.3.6.Final
11:51:06.269 [XNIO-1 I/O-2] DEBUG org.xnio.nio - Started channel thread 'XNIO-1 I/O-2', selector sun.nio.ch.EPollSelectorImpl@edaf287
11:51:06.271 [XNIO-1 Accept] DEBUG org.xnio.nio - Started channel thread 'XNIO-1 Accept', selector sun.nio.ch.EPollSelectorImpl@2e9e99fe
11:51:06.276 [XNIO-1 I/O-1] DEBUG org.xnio.nio - Started channel thread 'XNIO-1 I/O-1', selector sun.nio.ch.EPollSelectorImpl@883e25a
11:51:06.278 [main] DEBUG io.undertow - Configuring listener with protocol HTTP for interface localhost and port 14265
11:51:06.951 [XNIO-1 I/O-2] DEBUG io.undertow.request - Matched default handler path /
11:51:07.147 [pool-1-thread-2] INFO com.iota.iri.service.storage.Storage - Transactions to request = 0 / 4868 (377 ms / 0%)
11:51:07.181 [XNIO-1 task-1] ERROR com.iota.iri.service.API - API Exception:
java.lang.IndexOutOfBoundsException: -8192
        at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:253)
        at com.iota.iri.service.storage.Storage.setAnalyzedTransactionFlag(Storage.java:147)
        at com.iota.iri.service.API.getInclusionStateStatement(API.java:320)
        at com.iota.iri.service.API.process(API.java:157)
        at com.iota.iri.service.API.processRequest(API.java:108)
        at com.iota.iri.service.API.access$000(API.java:74)
        at com.iota.iri.service.API$1.handleRequest(API.java:95)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:208)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
11:51:07.238 [XNIO-1 task-1] DEBUG com.iota.iri.service.API - Sent 36 bytes back in the response.

**Comment by davassi** [comment]
@alfredch This regression has been currently fixed in 'dev' branch.
