### ISSUE TITLE
Error while shuting down IRI

### ISSUE THREAD

**Issue by GalRogozinski** [iotaledger/iri#1742]
### Bug description
While shutting down IRI errors were thrown and it is unclear whether all data was properly saved to db...
The `hs_err_pid1.log` wasn't created because I had a fromer log that I didn't delete on my machine.
If the problem will be recreated the contents of the file will be uploaded in a comment

### IRI version
`iotacafe/iri-dev:c9c74c2-e5c639c8` this is the commit that is supposed to spawn off the 1.9.0 branch

### Hardware Spec
Hetzner CX51

### Steps To Reproduce
1.  Sync nodes from a not too recent snapshot
2. Wait for syncing to be stuck
3. Shut down IRI

### Expected behaviour
No errors
### Actual behaviour
Errors

### Errors
```
02/04 14:01:49.721 [Local Snapshots Monitor] INFO  ThreadUtils:78 - Local Snapshots Monitor [STOPPED]
02/04 14:01:49.726 [pool-12-thread-3] INFO  TransactionProcessingPipelineImpl:158 - validation-stage shutdown
java.lang.InterruptedException
02/04 14:01:49.728 [pool-12-thread-6] INFO  TransactionProcessingPipelineImpl:158 - broadcast-stage shutdown
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.ArrayBlockingQueue.put(ArrayBlockingQueue.java:353)
	at com.iota.iri.crypto.batched.BatchedBCTCurl.submitHashingRequest(BatchedBCTCurl.java:58)
	at com.iota.iri.network.pipeline.HashingStage.process(HashingStage.java:33)
	at com.iota.iri.network.pipeline.TransactionProcessingPipelineImpl.hashAndValidate(TransactionProcessingPipelineImpl.java:221)
	at com.iota.iri.network.pipeline.TransactionProcessingPipelineImpl.lambda$addStage$0(TransactionProcessingPipelineImpl.java:134)
	at java.lang.Thread.run(Thread.java:748)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.ArrayBlockingQueue.put(ArrayBlockingQueue.java:353)
	at com.iota.iri.network.pipeline.TransactionProcessingPipelineImpl.process(TransactionProcessingPipelineImpl.java:186)
	at com.iota.iri.network.neighbor.impl.NeighborImpl.handleMessage(NeighborImpl.java:157)
	at com.iota.iri.network.neighbor.impl.NeighborImpl.read(NeighborImpl.java:105)
	at com.iota.iri.network.neighbor.impl.NeighborImpl.read(NeighborImpl.java:102)
	at com.iota.iri.network.NeighborRouterImpl.handleRead(NeighborRouterImpl.java:400)
	at com.iota.iri.network.NeighborRouterImpl.route(NeighborRouterImpl.java:215)
02/04 14:02:18.046 [pool-12-thread-4] INFO  TransactionProcessingPipelineImpl:158 - reply-stage shutdown
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
02/04 14:02:18.048 [pool-12-thread-5] INFO  TransactionProcessingPipelineImpl:158 - received-stage shutdown
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
02/04 14:01:49.729 [pool-12-thread-1] ERROR TransactionProcessingPipelineImpl:218 - unable to put processing context into hashing stage. reason: null
02/04 14:02:18.053 [Neighbor Router] INFO  NeighborRouterImpl:240 - neighbor router stopped
02/04 14:02:38.397 [Shutdown Hook] INFO  Tangle:78 - Releasing all caches...


02/04 14:05:32.432 [Shutdown Hook] INFO  Tangle:81 - Shutting down Tangle Persistence Providers... 
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f795b779aea, pid=1, tid=0x00007f79409ce700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_181-b13) (build 1.8.0_181-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.181-b13 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [librocksdbjni9051936110232332458.so+0x24baea]  rocksdb::DBImpl::GetImpl(rocksdb::ReadOptions const&, rocksdb::ColumnFamilyHandle*, rocksdb::Slice const&, rocksdb::PinnableSlice*, bool*, rocksdb::ReadCallback*, bool*)+0x1ca
#
# Core dump written. Default location: /iri/data/core or core.1
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid1.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

[error occurred during error reporting , id 0xb]
```

**Comment by GalRogozinski** [comment]
From `hs_err_pid1.log` it looks like a fail in RocksDb

```

Stack: [0x00007f4aa41c9000,0x00007f4aa42ca000],  sp=0x00007f4aa42c7638,  free space=1017k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x0000000629aa96b0
C  [librocksdbjni8566610877048518835.so+0x24c3bf]  rocksdb::DBImpl::Get(rocksdb::ReadOptions const&, rocksdb::ColumnFamilyHandle*, rocksdb::Slice const&, rocksdb::PinnableSlice*)+0x16f
C  [librocksdbjni8566610877048518835.so+0x1bde06]  rocksdb::DB::Get(rocksdb::ReadOptions const&, rocksdb::ColumnFamilyHandle*, rocksdb::Slice const&, std::string*)+0x146
C  [librocksdbjni8566610877048518835.so+0x1b4175]  rocksdb_get_helper(JNIEnv_*, rocksdb::DB*, rocksdb::ReadOptions const&, rocksdb::ColumnFamilyHandle*, _jbyteArray*, int, int)+0xd5
C  [librocksdbjni8566610877048518835.so+0x1b4402]  Java_org_rocksdb_RocksDB_get__J_3BIIJ+0x62
J 2149  org.rocksdb.RocksDB.$$YJP$$get(J[BIIJ)[B (0 bytes) @ 0x00007f4b474febe5 [0x00007f4b474feb00+0xe5]
J 4498 C2 com.iota.iri.storage.Tangle.load(Ljava/lang/Class;Lcom/iota/iri/storage/Indexable;)Lcom/iota/iri/storage/Persistable; (312 bytes) @ 0x00007f4b47929da0 [0x00007f4b47929a40+0x360]
J 6240 C2 com.iota.iri.controllers.TransactionViewModel.fromHash(Lcom/iota/iri/storage/Tangle;Lcom/iota/iri/model/Hash;)Lcom/iota/iri/controllers/TransactionViewModel; (237 bytes) @ 0x00007f4b47e0b150 [0x00007f4b47e0ae40+0x310]
J 6244 C2 com.iota.iri.controllers.TransactionViewModel.updateHeights(Lcom/iota/iri/storage/Tangle;Lcom/iota/iri/service/snapshot/Snapshot;)V (549 bytes) @ 0x00007f4b47e19ccc [0x00007f4b47e19500+0x7cc]
J 6249 C2 com.iota.iri.controllers.TransactionViewModel.updateSolidTransactions(Lcom/iota/iri/storage/Tangle;Lcom/iota/iri/service/snapshot/Snapshot;Ljava/util/Set;)V (152 bytes) @ 0x00007f4b47e118f4 [0x00007f4b47e11800+0xf4]
J 6183 C2 com.iota.iri.TransactionValidator.checkSolidity(Lcom/iota/iri/model/Hash;I)Z (598 bytes) @ 0x00007f4b47dcd288 [0x00007f4b47dcc320+0xf68]
J 6125 C2 com.iota.iri.service.milestone.impl.MilestoneSolidifierImpl.isSolid(Ljava/util/Map$Entry;)Z (443 bytes) @ 0x00007f4b47da3f48 [0x00007f4b47da3160+0xde8]
J 5554 C1 com.iota.iri.service.milestone.impl.MilestoneSolidifierImpl.processSolidificationQueue()V (335 bytes) @ 0x00007f4b47c66c94 [0x00007f4b47c65fc0+0xcd4]
J 6062 C1 com.iota.iri.service.milestone.impl.MilestoneSolidifierImpl.milestoneSolidificationThread()V (66 bytes) @ 0x00007f4b47633d44 [0x00007f4b47633bc0+0x184]
J 6061 C1 com.iota.iri.service.milestone.impl.MilestoneSolidifierImpl$$Lambda$53.run()V (31 bytes) @ 0x00007f4b476343d4 [0x00007f4b47634300+0xd4]
j  com.iota.iri.utils.thread.BoundedScheduledExecutorService.lambda$wrapTask$6(Lcom/iota/iri/utils/thread/TaskDetails;Ljava/lang/Runnable;Ljava/util/concurrent/Future;)V+102
j  com.iota.iri.utils.thread.BoundedScheduledExecutorService$$Lambda$49.run()V+29
J 6402 C1 java.util.concurrent.Executors$RunnableAdapter.call()Ljava/lang/Object; (47 bytes) @ 0x00007f4b47da9b0c [0x00007f4b47da9960+0x1ac]
j  java.util.concurrent.FutureTask.runAndReset()Z+100
j  java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Ljava/util/concurrent/ScheduledThreadPoolExecutor$ScheduledFutureTask;)Z+24
j  java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run()V+100
j  java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V+243
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+28
j  java.lang.Thread.run()V+49
v  ~StubRoutines::call_stub
V  [libjvm.so+0x697a76]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0x1056
V  [libjvm.so+0x697f81]  JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*)+0x321
V  [libjvm.so+0x698427]  JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Thread*)+0x47
V  [libjvm.so+0x71789e]  thread_entry(JavaThread*, Thread*)+0x7e
V  [libjvm.so+0xa813f3]  JavaThread::thread_main_inner()+0x103
V  [libjvm.so+0xa8153c]  JavaThread::run()+0x11c
V  [libjvm.so+0x930198]  java_start(Thread*)+0x108
C  [libpthread.so.0+0x76db]  start_thread+0xdb

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 2149  org.rocksdb.RocksDB.$$YJP$$get(J[BIIJ)[B (0 bytes) @ 0x00007f4b474feb63 [0x00007f4b474feb00+0x63]
J 4498 C2 com.iota.iri.storage.Tangle.load(Ljava/lang/Class;Lcom/iota/iri/storage/Indexable;)Lcom/iota/iri/storage/Persistable; (312 bytes) @ 0x00007f4b47929da0 [0x00007f4b47929a40+0x360]
J 6240 C2 com.iota.iri.controllers.TransactionViewModel.fromHash(Lcom/iota/iri/storage/Tangle;Lcom/iota/iri/model/Hash;)Lcom/iota/iri/controllers/TransactionViewModel; (237 bytes) @ 0x00007f4b47e0b150 [0x00007f4b47e0ae40+0x310]
J 6244 C2 com.iota.iri.controllers.TransactionViewModel.updateHeights(Lcom/iota/iri/storage/Tangle;Lcom/iota/iri/service/snapshot/Snapshot;)V (549 bytes) @ 0x00007f4b47e19ccc [0x00007f4b47e19500+0x7cc]
J 6249 C2 com.iota.iri.controllers.TransactionViewModel.updateSolidTransactions(Lcom/iota/iri/storage/Tangle;Lcom/iota/iri/service/snapshot/Snapshot;Ljava/util/Set;)V (152 bytes) @ 0x00007f4b47e118f4 [0x00007f4b47e11800+0xf4]
J 6183 C2 com.iota.iri.TransactionValidator.checkSolidity(Lcom/iota/iri/model/Hash;I)Z (598 bytes) @ 0x00007f4b47dcd288 [0x00007f4b47dcc320+0xf68]
J 6125 C2 com.iota.iri.service.milestone.impl.MilestoneSolidifierImpl.isSolid(Ljava/util/Map$Entry;)Z (443 bytes) @ 0x00007f4b47da3f48 [0x00007f4b47da3160+0xde8]
J 5554 C1 com.iota.iri.service.milestone.impl.MilestoneSolidifierImpl.processSolidificationQueue()V (335 bytes) @ 0x00007f4b47c66c94 [0x00007f4b47c65fc0+0xcd4]
J 6062 C1 com.iota.iri.service.milestone.impl.MilestoneSolidifierImpl.milestoneSolidificationThread()V (66 bytes) @ 0x00007f4b47633d44 [0x00007f4b47633bc0+0x184]
J 6061 C1 com.iota.iri.service.milestone.impl.MilestoneSolidifierImpl$$Lambda$53.run()V (31 bytes) @ 0x00007f4b476343d4 [0x00007f4b47634300+0xd4]
j  com.iota.iri.utils.thread.BoundedScheduledExecutorService.lambda$wrapTask$6(Lcom/iota/iri/utils/thread/TaskDetails;Ljava/lang/Runnable;Ljava/util/concurrent/Future;)V+102
j  com.iota.iri.utils.thread.BoundedScheduledExecutorService$$Lambda$49.run()V+29
J 6402 C1 java.util.concurrent.Executors$RunnableAdapter.call()Ljava/lang/Object; (47 bytes) @ 0x00007f4b47da9b0c [0x00007f4b47da9960+0x1ac]
j  java.util.concurrent.FutureTask.runAndReset()Z+100
j  java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Ljava/util/concurrent/ScheduledThreadPoolExecutor$ScheduledFutureTask;)Z+24
j  java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run()V+100
j  java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V+243
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+28
j  java.lang.Thread.run()V+49
v  ~StubRoutines::call_stub
```

**Comment by GalRogozinski** [comment]
It has happened again...
We need to pay attention that besides the array blocking problem there is probably a problem that we are encountering when we release from cache

**Comment by GalRogozinski** [comment]
Linking to the branch that should fix this https://github.com/GalRogozinski/iri/commit/f65e29b23f89a8422aa5949d5d189080507c68b6

Will tend to merging it properly later
