### ISSUE TITLE
Use neighbors according to hearthbeat

### ISSUE THREAD

**Issue by kwek20** [iotaledger/iri#1798]

**Comment by tylerw1369** [comment]
This is what my node shows if i disable snapshot. 

ar 16 09:02:38 tyler-node IRI[32571]:         ... 14 common frames omitted
Mar 16 09:02:43 tyler-node IRI[32571]: 03/16 09:02:43.408 [Tips Requester] INFO  TipsRequesterImpl:86 - toProcess = 0 , toBroadcast = 0 , toRequest = 0 , toReply = 0 / totalTransactions = 43359603
Mar 16 09:02:43 tyler-node IRI[32571]: 03/16 09:02:43.586 [Latest Solid Milestone Tracker] INFO  LatestSolidMilestoneTrackerImpl:392 - Latest SOLID milestone index changed from #1348004 to #1348005
Mar 16 09:02:44 tyler-node IRI[32571]: 03/16 09:02:44.185 [Latest Solid Milestone Tracker] INFO  MilestoneServiceImpl:534 - resetting corrupted milestone #1348009
Mar 16 09:02:44 tyler-node IRI[32571]: 03/16 09:02:44.232 [Latest Solid Milestone Tracker] INFO  MilestoneServiceImpl:534 - resetting corrupted milestone #1348008
Mar 16 09:02:44 tyler-node IRI[32571]: 03/16 09:02:44.334 [Latest Solid Milestone Tracker] INFO  MilestoneServiceImpl:534 - resetting corrupted milestone #1348007
Mar 16 09:02:44 tyler-node IRI[32571]: 03/16 09:02:44.465 [Latest Solid Milestone Tracker] INFO  MilestoneServiceImpl:534 - resetting corrupted milestone #1348006
Mar 16 09:02:44 tyler-node IRI[32571]: 03/16 09:02:44.629 [Latest Solid Milestone Tracker] INFO  MilestoneServiceImpl:534 - resetting corrupted milestone #1348005
Mar 16 09:02:44 tyler-node IRI[32571]: 03/16 09:02:44.748 [Latest Solid Milestone Tracker] INFO  MilestoneServiceImpl:534 - resetting corrupted milestone #1348004
Mar 16 09:02:44 tyler-node IRI[32571]: 03/16 09:02:44.958 [Latest Solid Milestone Tracker] ERROR LatestSolidMilestoneTrackerImpl:465 - error while updating the solid milestone
Mar 16 09:02:44 tyler-node IRI[32571]: com.iota.iri.service.milestone.MilestoneException: unexpected error while checking for new latest solid milestones
Mar 16 09:02:44 tyler-node IRI[32571]:         at com.iota.iri.service.milestone.impl.LatestSolidMilestoneTrackerImpl.trackLatestSolidMilestone(LatestSolidMilestoneTrackerImpl.java:183) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
Mar 16 09:02:44 tyler-node IRI[32571]:         at com.iota.iri.service.milestone.impl.LatestSolidMilestoneTrackerImpl.latestSolidMilestoneTrackerThread(LatestSolidMilestoneTrackerImpl.java:207) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
Mar 16 09:02:44 tyler-node IRI[32571]:         at com.iota.iri.utils.thread.BoundedScheduledExecutorService.lambda$wrapTask$6(BoundedScheduledExecutorService.java:585) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
Mar 16 09:02:44 tyler-node IRI[32571]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
Mar 16 09:02:44 tyler-node IRI[32571]:         at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
Mar 16 09:02:44 tyler-node IRI[32571]:         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
Mar 16 09:02:44 tyler-node IRI[32571]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
Mar 16 09:02:44 tyler-node IRI[32571]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
Mar 16 09:02:44 tyler-node IRI[32571]:         at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
Mar 16 09:02:44 tyler-node IRI[32571]: Caused by: com.iota.iri.service.milestone.MilestoneException: failed to repair corrupted milestone with index #1348004
Mar 16 09:02:44 tyler-node IRI[32571]:         at com.iota.iri.service.milestone.impl.MilestoneServiceImpl.resetCorruptedMilestone(MilestoneServiceImpl.java:546) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
Mar 16 09:02:44 tyler-node IRI[32571]:         at com.iota.iri.service.milestone.impl.MilestoneServiceImpl.resetCorruptedMilestone(MilestoneServiceImpl.java:148) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
Mar 16 09:02:44 tyler-node IRI[32571]:         at com.iota.iri.service.milestone.impl.LatestSolidMilestoneTrackerImpl.repairCorruptedMilestone(LatestSolidMilestoneTrackerImpl.java:382) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
Mar 16 09:02:44 tyler-node IRI[32571]:         at com.iota.iri.service.milestone.impl.LatestSolidMilestoneTrackerImpl.applySolidMilestoneToLedger(LatestSolidMilestoneTrackerImpl.java:233) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
Mar 16 09:02:44 tyler-node IRI[32571]:         at com.iota.iri.service.milestone.impl.LatestSolidMilestoneTrackerImpl.trackLatestSolidMilestone(LatestSolidMilestoneTrackerImpl.java:170) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
Mar 16 09:02:44 tyler-node IRI[32571]:         ... 8 common frames omitted
Mar 16 09:02:44 tyler-node IRI[32571]: Caused by: com.iota.iri.service.snapshot.SnapshotException: failed to rollback last milestone
Mar 16 09:02:44 tyler-node IRI[32571]:         at com.iota.iri.service.snapshot.impl.SnapshotServiceImpl.rollbackLastMilestone(SnapshotServiceImpl.java:375) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
Mar 16 09:02:44 tyler-node IRI[32571]:         at com.iota.iri.service.snapshot.impl.SnapshotServiceImpl.rollBackMilestones(SnapshotServiceImpl.java:180) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
Mar 16 09:02:44 tyler-node IRI[32571]:         at com.iota.iri.service.milestone.impl.MilestoneServiceImpl.resetCorruptedMilestone(MilestoneServiceImpl.java:539) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
Mar 16 09:02:44 tyler-node IRI[32571]:         ... 12 common frames omitted
Mar 16 09:02:44 tyler-node IRI[32571]: Caused by: com.iota.iri.service.snapshot.SnapshotException: failed to apply patch belonging to milestone #1348004 (CEBFZ9UXHMJY9ONOMIGOQHVWSTUIZWBSXELF9GBFGKHZOCHWIVRINQ9BKKOUTHESM9YTQAMDHKXU99999)
Mar 16 09:02:44 tyler-node IRI[32571]:         at com.iota.iri.service.snapshot.impl.SnapshotServiceImpl.rollbackLastMilestone(SnapshotServiceImpl.java:346) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
Mar 16 09:02:44 tyler-node IRI[32571]:         ... 14 common frames omitted

**Comment by tylerw1369** [comment]
wrong one sorry

**Comment by GalRogozinski** [comment]
Broadcast it every minute or check what hornet does
