### ISSUE TITLE
Requesting command getTransactionsToApprove IndexOutOfBoundsException

### ISSUE THREAD

**Issue by pinpong** [iotaledger/iri#21]
12:10:27.036 [XNIO-1 task-20] INFO  com.iota.iri.service.API - -> Requesting command getTransactionsToApprove
12:10:27.052 [XNIO-1 task-20] ERROR com.iota.iri.service.API - API Exception:
java.lang.IndexOutOfBoundsException: null
at java.nio.Buffer.checkIndex(Buffer.java:540)
at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:253)
at com.iota.iri.service.storage.Storage.setAnalyzedTransactionFlag(Storage.java:147)
at com.iota.iri.service.TipsManager.transactionToApprove(TipsManager.java:81)
at com.iota.iri.service.API.getTransactionToApproveStatement(API.java:254)
at com.iota.iri.service.API.process(API.java:186)
at com.iota.iri.service.API.processRequest(API.java:105)
at com.iota.iri.service.API.access$000(API.java:71)
at com.iota.iri.service.API$1.handleRequest(API.java:92)
at io.undertow.server.Connectors.executeRootHandler(Connectors.java:208)
at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

**Comment by davassi** [comment]
@pinpong seems working. 

curl http://node.iotawallet.info:14265 \
                     -X POST \
                     -H 'Content-Type: application/json' \
                     -d '{"command": "getTransactionsToApprove", "depth": 2}'
{"trunkTransaction":"QBUCIUJBFJOVRPNDARNBEPFPRDADMRIMSOVJRDFLYZQSADECSAJFBPB9NGCTXRRROTBUHMWSAKD999999","branchTransaction":"XUYBQMWFUCZ9DHAYU9LCAYJTSGAJDJTSAPXMHVZXZWXRZVHPOEVEEYQLALYKTFULQOCPRRVMJXT999999","duration":27460}

do you have this error often?
