### ISSUE TITLE
TipsManager: Error during solidity scan

### ISSUE THREAD

**Issue by marcel-burkhard** [iotaledger/iri#231]
I encountered an error when running a fullnode and was asked by Alon Elmaliah to open an issue here.

This was the error message:
```
07/17 00:27:50.059 [Tip Solidity Rescan] ERROR com.iota.iri.service.TipsManager - Error during solidity scan : {}
java.util.ConcurrentModificationException: null
        at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719) ~[na:1.8.0_131]
        at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742) ~[na:1.8.0_131]
        at com.iota.iri.controllers.TipsViewModel.getRandomNonSolidTipHash(TipsViewModel.java:85) ~[iri-1.2.4.jar:na]
        at com.iota.iri.service.TipsManager.scanTipsForSolidity(TipsManager.java:76) ~[iri-1.2.4.jar:na]
        at com.iota.iri.service.TipsManager.lambda$init$0(TipsManager.java:59) ~[iri-1.2.4.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
```
I was not out of memory, enough space on disk et cetera. Fully synced according to #botbox in Slack at that time.

If there is any additional information you'd like me to provide don't hesitate to ask!

**Comment by marcel-burkhard** [comment]
I used OpenJDK.

**Comment by meinharrd** [comment]
i just had the same error when restarting my node.

```
$ java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by marcel-burkhard** [comment]
I hade the same error now with Oracle JDK

```
07/24 12:34:40.551 [Tip Solidity Rescan] ERROR com.iota.iri.service.TipsManager - Error during solidity scan : {}
java.util.ConcurrentModificationException: null
        at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719) ~[na:1.8.0_141]
        at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742) ~[na:1.8.0_141]
        at com.iota.iri.controllers.TipsViewModel.getRandomNonSolidTipHash(TipsViewModel.java:85) ~[iri-1.2.4.jar:na]
        at com.iota.iri.service.TipsManager.scanTipsForSolidity(TipsManager.java:76) ~[iri-1.2.4.jar:na]
        at com.iota.iri.service.TipsManager.lambda$init$0(TipsManager.java:59) ~[iri-1.2.4.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_141]
```
Seconds before IXI initialised
