### ISSUE TITLE
getTransactionsToApprove: API Exception

### ISSUE THREAD

**Issue by domschiener** [iotaledger/iri#26]
Before the milestone has been successfully updated (e.g. `6000` -> `8878`), calling getTransactionsToApprove leads to an api exception and nothing returned to the caller. Considering that updating the milestone takes several minutes on certain occasions, this will lead to some unexpected behavior in the wallets.

This is with the latest 1.1.2.1 from dev branch.

```
11:18:50.663 [XNIO-1 task-1] INFO  com.iota.iri.service.API - -> Requesting command getTransactionsToApprove
11:18:50.685 [XNIO-1 task-1] INFO  com.iota.iri.service.TipsManager - Confirmed transactions = 1
11:18:51.032 [XNIO-1 task-1] INFO  com.iota.iri.service.TipsManager - 89860 tails need to be analyzed
11:19:35.807 [XNIO-1 task-1] ERROR com.iota.iri.service.API - API Exception: 
java.lang.IndexOutOfBoundsException: null
	at java.nio.Buffer.checkIndex(Buffer.java:540) ~[na:1.8.0_111]
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:253) ~[na:1.8.0_111]
	at com.iota.iri.service.storage.StorageScratchpad.setAnalyzedTransactionFlag(StorageScratchpad.java:119) ~[iri-1.1.2.1.jar:na]
	at com.iota.iri.service.TipsManager.transactionToApprove(TipsManager.java:199) ~[iri-1.1.2.1.jar:na]
	at com.iota.iri.service.API.getTransactionToApproveStatement(API.java:255) [iri-1.1.2.1.jar:na]
	at com.iota.iri.service.API.process(API.java:187) [iri-1.1.2.1.jar:na]
	at com.iota.iri.service.API.processRequest(API.java:106) [iri-1.1.2.1.jar:na]
	at com.iota.iri.service.API.access$000(API.java:72) [iri-1.1.2.1.jar:na]
	at com.iota.iri.service.API$1.handleRequest(API.java:93) [iri-1.1.2.1.jar:na]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:208) [iri-1.1.2.1.jar:na]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809) [iri-1.1.2.1.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
```

**Comment by davassi** [comment]
Ok, as a temporary fix I will return a nicer user message if the milestone updated process has not being even started. Need to find a proper condition to identify when the milestone has been fully sync.

**Comment by davassi** [comment]
@domschiener fix committed on dev
