### ISSUE TITLE
Exception in Thread - Latest Milestone Tracker

### ISSUE THREAD

**Issue by tuddman** [iotaledger/iri#278]
```
Exception in thread "Latest Milestone Tracker" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.HashMap.newNode(HashMap.java:1742)
	at java.util.HashMap.putVal(HashMap.java:630)
	at java.util.HashMap.put(HashMap.java:611)
	at java.util.HashSet.add(HashSet.java:219)
	at com.iota.iri.model.Hashes.read(Hashes.java:28)
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.get(RocksDBPersistenceProvider.java:189)
	at com.iota.iri.storage.Tangle.load(Tangle.java:40)
	at com.iota.iri.controllers.AddressViewModel.load(AddressViewModel.java:32)
	at com.iota.iri.Milestone.lambda$init$3(Milestone.java:75)
	at com.iota.iri.Milestone$$Lambda$11/1218864105.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
08/26 15:15:08.988 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 5 , toReply = 0 / totalTransactions = 923605
Exception in thread "Tip Solidity Rescan" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.iota.iri.model.Hash.trits(Hash.java:85)
	at com.iota.iri.model.Hash.trailingZeros(Hash.java:76)
	at com.iota.iri.controllers.TransactionViewModel.<init>(TransactionViewModel.java:99)
	at com.iota.iri.controllers.TransactionViewModel.fromHash(TransactionViewModel.java:89)
	at com.iota.iri.TransactionValidator.checkSolidity(TransactionValidator.java:122)
	at com.iota.iri.service.TipsManager.scanTipsForSolidity(TipsManager.java:82)
	at com.iota.iri.service.TipsManager.lambda$init$0(TipsManager.java:59)
	at com.iota.iri.service.TipsManager$$Lambda$14/47971575.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by paulhandy** [comment]
Please report JVM version and memory settings arguments ( i,e. `-Xms4g -Xmx512m` )

**Comment by tuddman** [comment]
`vm_info: Java HotSpot(TM) 64-Bit Server VM (25.144-b01) for linux-amd64 JRE (1.8.0_144-b01)`

no JVM memory settings arguments passed in.     Is this 'solved' by passing those in? If so, whats the minimum recommended?

**Comment by paulhandy** [comment]
I'd recommend using Oracle JRE, and these memory settings if your device has the capacity ☝️

**Comment by tuddman** [comment]
am using the Oracle JRE. I've set `Xms2g` will see how it goes

**Comment by alfredch** [comment]
Be aware that the embedded database needs an additional 1-2GB (in addition to the Java heap space).

**Comment by tuddman** [comment]
thanks @alfredch 
there's some SO discussion [here](https://stackoverflow.com/questions/5839359/java-lang-outofmemoryerror-gc-overhead-limit-exceeded) as well on other ways to reduce the memory footprint of `HashMap` collections.

would be nice to see at some point the _minimum recommended specs_ for running a full node.

**Comment by alfredch** [comment]
Apart from ram - the disk I/O speed matters. RocksDB is designed for SSD disks. Any attempt to run without SSD will show failures either of the type 'JVM crash' or milestone lagging.

**Comment by tuddman** [comment]
Closing this issue, as can be resolved with 'throw more RAM at it'

As this project is ostensibly targeting (limited) devices, _every_ effort should be made to reduce the memory footprint wherever and whenever possible.
