### ISSUE TITLE
RocksDB error accessing persistence store

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/iri#351]
This error keeps scrolling by after about 30-60 min of running the node:
```
11/13 20:19:35.899 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 887 , toReply = 0 / totalTransactions = 904133
RocksDBExceptionJni::ThrowNew/StatusJni - Error: unexpected exception!
11/13 20:19:36.008 [pool-2-thread-4] ERROR com.iota.iri.network.Node - Error accessing persistence store.
java.lang.IllegalArgumentException: Illegal value provided for SubCode.
        at org.rocksdb.Status$SubCode.getSubCode(Status.java:109) ~[iri-1.4.1.2.jar:na]
        at org.rocksdb.Status.<init>(Status.java:30) ~[iri-1.4.1.2.jar:na]
        at org.rocksdb.RocksDB.write0(Native Method) ~[iri-1.4.1.2.jar:na]
        at org.rocksdb.RocksDB.write(RocksDB.java:602) ~[iri-1.4.1.2.jar:na]
        at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.saveBatch(RocksDBPersistenceProvider.java:345) ~[iri-1.4.1.2.jar:na]
        at com.iota.iri.storage.Tangle.saveBatch(Tangle.java:53) ~[iri-1.4.1.2.jar:na]
        at com.iota.iri.controllers.TransactionViewModel.store(TransactionViewModel.java:204) ~[iri-1.4.1.2.jar:na]
        at com.iota.iri.network.Node.processReceivedData(Node.java:404) [iri-1.4.1.2.jar:na]
        at com.iota.iri.network.Node.processReceivedDataFromQueue(Node.java:379) [iri-1.4.1.2.jar:na]
        at com.iota.iri.network.Node.lambda$spawnProcessReceivedThread$13(Node.java:587) [iri-1.4.1.2.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
```
Here's my JRE and OS info:
```
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```
```
Linux 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by rajivshah3** [comment]
I realized my disk was full 🤦‍♂️
