### ISSUE TITLE
GC overhead limit exceeded crash

### ISSUE THREAD

**Issue by kgreenek** [iotaledger/iri#352]
When running the testnet version of IRI (v1.4.1.1), I notice that all CPUs become pegged at 100%, and then after a couple minutes, I see the following crash. It looks like a potential memory leak.

My machine is a desktop PC, which has 15GB of ram and a beefy processor, running Ubuntu 17.10.

```bash
11/14 10:13:03.116 [Latest Milestone Tracker] INFO  com.iota.iri.Milestone - Latest milestone has changed from #408420 to #408421
11/14 10:13:08.066 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 0 , toReply = 0 / totalTransactions = 2077438
11/14 10:13:23.067 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 0 , toReply = 0 / totalTransactions = 2077449
11/14 10:13:34.361 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 0 , toReply = 1 / totalTransactions = 2077456
11/14 10:13:56.168 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 0 , toReply = 0 / totalTransactions = 2077459
Exception in thread "Latest Milestone Tracker" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.LinkedHashMap.newNode(LinkedHashMap.java:256)
	at java.util.HashMap.putVal(HashMap.java:631)
	at java.util.HashMap.put(HashMap.java:612)
	at java.util.HashSet.add(HashSet.java:220)
	at com.iota.iri.model.Hashes.read(Hashes.java:29)
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.get(RocksDBPersistenceProvider.java:189)
	at com.iota.iri.storage.Tangle.load(Tangle.java:40)
	at com.iota.iri.controllers.AddressViewModel.load(AddressViewModel.java:32)
	at com.iota.iri.Milestone.lambda$init$0(Milestone.java:80)
	at com.iota.iri.Milestone$$Lambda$11/58940486.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
11/14 10:14:05.651 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 0 , toReply = 0 / totalTransactions = 2077465
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f9b8be88033, pid=3795, tid=0x00007f9b5862e700
#
# JRE version: OpenJDK Runtime Environment (8.0_151-b12) (build 1.8.0_151-8u151-b12-0ubuntu0.17.10.2-b12)
# Java VM: OpenJDK 64-Bit Server VM (25.151-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x695033]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /media/ubuntu/hdd1/iota-testnet/hs_err_pid3795.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Aborted (core dumped)
```

**Comment by alon-e** [comment]
It is recommended to use Oracle Java & not OpenJDK for IRI, as the GC impl. is better suited for this task.
please report back if the issue persists.

**Comment by soenkegissel** [comment]
For me this issue persists. I am using oracle jdk 8 update 151.
I have 2 core processor and 4gb RAM.

**Comment by th0br0** [comment]
What parameters are you running IRI with? (i.e. which `-Xmx` and which `-Xms`)

**Comment by hapklaar** [comment]
Just had this error myself. Using Oracle java 8 update 144 on Windows 2012R2 with iri 1.4.1.1

My startup is "java -Xmx4g -Xms256m -jar iri-1.4.1.1.jar --config config1.txt"

**Comment by hapklaar** [comment]
This error is now happening multiple times a day. Even after updating java to update 152.

**Comment by kgreenek** [comment]
I was running with no special parameters except the testnet flag

**Comment by hapklaar** [comment]
Did a --revalidate this morning, and node has been running smooth since. SOLID finally has caught up as well.
