### ISSUE TITLE
RejectedExecutionException while shutdown IRI

### ISSUE THREAD

**Issue by pinpong** [iotaledger/iri#363]
```
java[3544]: Exception in thread "XNIO-1 task-18" java.util.concurrent.RejectedExecutionException: XNIO007007: Thread is terminating
java[3544]:         at org.xnio.nio.WorkerThread.executeAfter(WorkerThread.java:615)
java[3544]:         at io.undertow.util.DateUtils.getCurrentDateTime(DateUtils.java:251)
java[3544]:         at io.undertow.util.DateUtils.addDateHeaderIfRequired(DateUtils.java:235)
java[3544]:         at io.undertow.server.protocol.http.HttpTransferEncoding.createSinkConduit(HttpTransferEncoding.java:203)
java[3544]:         at io.undertow.server.protocol.http.HttpServerConnection.getSinkConduit(HttpServerConnection.java:209)
java[3544]:         at io.undertow.server.HttpServerExchange.getResponseChannel(HttpServerExchange.java:1285)
java[3544]:         at io.undertow.server.HttpServerExchange.closeAndFlushResponse(HttpServerExchange.java:1670)
java[3544]:         at io.undertow.server.HttpServerExchange.endExchange(HttpServerExchange.java:1651)
java[3544]:         at io.undertow.server.Connectors.executeRootHandler(Connectors.java:236)
java[3544]:         at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809)
java[3544]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java[3544]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java[3544]:         at java.lang.Thread.run(Thread.java:748)
java[3544]: 11/23 16:53:49.652 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 1 , toReply = 0 / totalTransactions = 4058147
[3544]: 11/23 16:53:50.282 [pool-2-thread-4] INFO  com.iota.iri.network.Node - Shutting down Process Received Data Thread
[3544]: 11/23 16:53:50.286 [pool-2-thread-5] INFO  com.iota.iri.network.Node - Shutting down Reply To Request Thread
[3544]: 11/23 16:53:50.286 [pool-2-thread-1] INFO  com.iota.iri.network.Node - Shutting down Broadcaster Thread
[3544]: 11/23 16:53:50.761 [pool-2-thread-3] INFO  com.iota.iri.network.Node - Shutting down Neighbor DNS Refresher Thread
java[3544]: 11/23 16:53:54.683 [pool-2-thread-2] INFO  com.iota.iri.network.Node - Shutting down Requester Thread
java[3544]: 11/23 16:53:54.972 [UDP receiving thread] INFO  com.iota.iri.network.UDPReceiver - Shutting down spawning Receiver Thread
java[3544]: 11/23 16:53:55.865 [Shutdown Hook] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers...
java[3544]: #
java[3544]: # A fatal error has been detected by the Java Runtime Environment:
java[3544]: #
java[3544]: #  SIGSEGV (0xb) at pc=0x00007f9f43a85634, pid=3544, tid=0x00007f9efacec700
java[3544]: #
java[3544]: # JRE version: OpenJDK Runtime Environment (8.0_131-b11) (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
java[3544]: # Java VM: OpenJDK 64-Bit Server VM (25.131-b11 mixed mode linux-amd64 compressed oops)
java[3544]: # Problematic frame:
java[3544]: # Cpure virtual method called
java[3544]: terminate called without an active exception


```

**Comment by nayanmshah** [comment]
How did you try to shutdown? It seems like a task was triggered just when you shutdown the node resulting in it unable to process it and throwing the exception.
