### ISSUE TITLE
1.4.1.2 Java 9.0.1 Windows 10 x64 crash

### ISSUE THREAD

**Issue by 0xc0deface** [iotaledger/iri#364]
Trying to run in Windows 10 x64 with Java 9.0.1 crashes with the error

```
11/23 17:48:08.298 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.4.1.2
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException
        at com.iota.iri.IRI.main(IRI.java:55)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.ValidationException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more

```

im running with:
`java -jar iri-1.4.1.1.jar -c iota.ini`

and my ini file is this:

```
[IRI]
PORT = 14266
TCP_RECEIVER_PORT = 14265
NEIGHBORS = ...peers...
IXI_DIR = ixi
HEADLESS = true
DEBUG = true
DB_PATH = db
```

If I run 1.4.1.1 it does not crash. Also if I run from via bash on the unix subsystem the same command works.

**Comment by alon-e** [comment]
see #344

**Comment by 0xc0deface** [comment]
work around works, thanks!
