### ISSUE TITLE
Error while syncing

### ISSUE THREAD

**Issue by pinpong** [iotaledger/iri#367]
```
java[6881]: 11/27 16:17:09.627 [r] ERROR com.iota.iri.Milestone - Error during Solid Milestone updating
java[6881]: org.rocksdb.RocksDBException: While open a file for appending: mainnetdb/014786.log: To many open files
java[6881]:         at org.rocksdb.RocksDB.put(Native Method) ~[IRI.jar:na]
java[6881]:         at org.rocksdb.RocksDB.put(RocksDB.java:472) ~[IRI.jar:na]
java[6881]:         at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.update(RocksDBPersistenceProvider.java:381) ~[IRI.jar:na]
java[6881]:         at com.iota.iri.storage.Tangle.update(Tangle.java:92) ~[IRI.jar:na]
java[6881]:         at com.iota.iri.controllers.TransactionViewModel.update(TransactionViewModel.java:124) ~[IRI.jar:na]
java[6881]:         at com.iota.iri.controllers.TransactionViewModel.setValidity(TransactionViewModel.java:305) ~[IRI.jar:na]
java[6881]:         at com.iota.iri.BundleValidator.validate(BundleValidator.java:99) ~[IRI.jar:na]
java[6881]:         at com.iota.iri.LedgerValidator.getLatestDiff(LedgerValidator.java:92) ~[IRI.jar:na]
java[6881]:         at com.iota.iri.LedgerValidator.updateSnapshot(LedgerValidator.java:257) ~[IRI.jar:na]
java[6881]:         at com.iota.iri.Milestone.updateLatestSolidSubtangleMilestone(Milestone.java:209) ~[IRI.jar:na]
java[6881]:         at com.iota.iri.Milestone.lambda$init$1(Milestone.java:132) ~[IRI.jar:na]
java[6881]:         at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]

**Comment by pemontto** [comment]
Check out your limits with `ulimit -a`. Increase it with `ulimit -n 65535`. Put it in `/etc/security/limits.conf` to make it permanent

**Comment by GhostTyper** [comment]
I operate the open node node.lukaseder.de which is one of the nodes with the highest load out there. I'm using standard limits, so my -u is 1024 which also is the standard in most linux distros out there.

For me this error posted by pinpong never occurred. So I doubt cranking up -u will solve his porblem.

You need to post additional infos. Are there other services running under that user or on the system? etc.

**Comment by jakubcech** [comment]
@pinpong , @GhostTyper , @pemontto can you please provide steps for reproducing this? Thanks!
