### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by pinpong** [iotaledger/iri#368]
```
java[32069]: 11/27 16:31:45.151 [XNIO-1 task-13] ERROR com.iota.iri.service.API - API Exception:
java[32069]: java.lang.NullPointerException: null
java[32069]:         at com.iota.iri.service.API.tiveSearchWithinIndex(API.java:540) [IRI.jar:na]
java[32069]:         at com.iota.iri.service.API.getNewInclusionStateStatement(API.java:525) [IRI.jar:na]
java[32069]:         at com.iota.iri.service.API.process(API.java:235) [IRI.jar:na]
java[32069]:         at com.iota.iri.service.API.processRequest(API.java:172) [IRI.jar:na]
java[32069]:         at com.iota.iri.service.API.access$000(API.java:82) [IRI.jar:na]
java[32069]:         at com.iota.iri.service.API$1.handleRequest(API.java:153) [IRI.jar:na]
java[32069]:         at io.undertow.server.Connectors.executeRootHandler(Connectors.java:208) [IRI.jar:na]
java[32069]:         at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809) [IRI.jar:na]
java[32069]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_131]
java[32069]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_131]
java[32069]:         at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

```

**Comment by gubatron** [comment]
This line seems to be the offending one:
```java
private boolean exhaustiveSearchWithinIndex(Queue<Hash> nonAnalyzedTransactions, Set<Hash> analyzedTips, List<Hash> transactions, int[] inclusionStates, int count, int index) throws Exception {
        Hash pointer;
        MAIN_LOOP:
        while ((pointer = nonAnalyzedTransactions.poll()) != null) {  // <<< NPEing here
```

`exhaustiveSearchWithinIndex` is only used here:

```java
private AbstractResponse getNewInclusionStateStatement(final List<String> trans, final List<String> tps) throws Exception {
...
        for(Map.Entry<Integer, Set<Hash>> entry: sameIndexTransactions.entrySet()) {
            // right below `nonAnalyzedTransactionsMap` doesn't have that transaction
            if(!exhaustiveSearchWithinIndex(nonAnalyzedTransactionsMap.get(entry.getKey()), analyzedTips, transactions, inclusionStates, entry.getValue().size(), entry.getKey())) {
                return ErrorResponse.create("The subtangle is not solid");
            }
        }
```

what should happen when one of those `sameIndexTransactions` is not within the `nonAnalyzedTransactionsMap`, which would be the case in which `nonAnalyzedTransactionsMap.get(entry.getKey())` is returning `null`?
