### ISSUE TITLE
Crash on attempting to --rescan

### ISSUE THREAD

**Issue by pRizz** [iotaledger/iri#371]
It seems like there are actually two crashes happening here: one in the rocksdb framework and another in the iri implementation when attempting to shut down. This occurs when attempting to start the node with the `--rescan` flag.

```11/29 04:26:28.838 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - Initializing Database Backend...
11/29 04:26:30.900 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - RocksDB persistence provider initialized.
11/29 04:26:36.533 [main] INFO  com.iota.iri.Iota - Clearing cache: 10000 Addresses
11/29 04:26:39.634 [main] INFO  com.iota.iri.Iota - Clearing cache: 20000 Addresses
11/29 04:27:28.387 [main] ERROR com.iota.iri.IRI - Exception during IOTA node initialisation:
java.lang.NegativeArraySizeException: null
        at org.rocksdb.RocksIterator.value0(Native Method) ~[iri.jar:na]
        at org.rocksdb.RocksIterator.value(RocksIterator.java:50) ~[iri.jar:na]
        at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.next(RocksDBPersistenceProvider.java:261) ~[iri.jar:na]
        at com.iota.iri.storage.Tangle.next(Tangle.java:158) ~[iri.jar:na]
        at com.iota.iri.controllers.AddressViewModel.next(AddressViewModel.java:68) ~[iri.jar:na]
        at com.iota.iri.Iota.rescan_db(Iota.java:124) ~[iri.jar:na]
        at com.iota.iri.Iota.init(Iota.java:98) ~[iri.jar:na]
        at com.iota.iri.IRI.main(IRI.java:86) ~[iri.jar:na]
11/29 04:27:28.388 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...
11/29 04:27:34.389 [Shutdown Hook] ERROR com.iota.iri.IRI - Exception occurred shutting down IOTA node:
java.lang.NullPointerException: null
        at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:76) ~[iri.jar:na]
        at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:30) ~[iri.jar:na]
        at com.iota.iri.Iota.shutdown(Iota.java:178) ~[iri.jar:na]
        at com.iota.iri.IRI.lambda$shutdownHook$0(IRI.java:253) ~[iri.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_144]```

**Comment by LiQio** [comment]
Same here fully synced node - everything looking good
But DB folder is 34GB so I decide to shutdown and restart with --rescan option
OS: Windows 2016, IRI-1.4.1.2
`12/01 13:51:15.312 [main] INFO  com.iota.iri.IRI - Remote access enabled. Binding API socket to listen any interface.
12/01 13:51:15.312 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.4.1.2
12/01 13:51:19.230 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - Initializing Database Backend...
12/01 13:51:19.849 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - RocksDB persistence provider initialized.
12/01 13:51:24.755 [main] ERROR com.iota.iri.IRI - Exception during IOTA node initialisation:
java.lang.NegativeArraySizeException: null
        at org.rocksdb.RocksIterator.value0(Native Method) ~[iri-1.4.1.2.jar:na]
        at org.rocksdb.RocksIterator.value(RocksIterator.java:50) ~[iri-1.4.1.2.jar:na]
        at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.first(RocksDBPersistenceProvider.java:306) ~[iri-1.4.1.2.jar:na]
        at com.iota.iri.storage.Tangle.getFirst(Tangle.java:178) ~[iri-1.4.1.2.jar:na]
        at com.iota.iri.controllers.AddressViewModel.first(AddressViewModel.java:60) ~[iri-1.4.1.2.jar:na]
        at com.iota.iri.Iota.rescan_db(Iota.java:119) ~[iri-1.4.1.2.jar:na]
        at com.iota.iri.Iota.init(Iota.java:98) ~[iri-1.4.1.2.jar:na]
        at com.iota.iri.IRI.main(IRI.java:86) ~[iri-1.4.1.2.jar:na]
12/01 13:51:24.755 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...
12/01 13:51:30.769 [Shutdown Hook] ERROR com.iota.iri.IRI - Exception occurred shutting down IOTA node:
java.lang.NullPointerException: null
        at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:76) ~[iri-1.4.1.2.jar:na]
        at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:30) ~[iri-1.4.1.2.jar:na]
        at com.iota.iri.Iota.shutdown(Iota.java:178) ~[iri-1.4.1.2.jar:na]
        at com.iota.iri.IRI.lambda$shutdownHook$0(IRI.java:253) ~[iri-1.4.1.2.jar:na]
        at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_151]`

**Comment by AronVanAmmers** [comment]
Getting this too, first with 1.4.1.2 and still after update to 1.4.1.4. Any progress?

**Comment by AronVanAmmers** [comment]
I started from scratch with 1.4.1.4:

- delete iri data folder
- start iri

It started syncing from 243000 again. After a while the latest solid milestone didn't increase anymore. Therefore I stopped and started. Updated for a while again, then got stuck. Stopped and started. Now getting the NegativeArraySizeException again. Database is at 17GB.

I'm running iri in Docker using an image based on `ubuntu:16.04`. This has worked well up to now with previous versions (besides needing an occasional rescan/start from scratch).

```
12/22 10:18:40.991 [main] INFO  com.iota.iri.IRI - Remote access enabled. Binding API socket to listen any interface.
12/22 10:18:40.992 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.4.1.4
12/22 10:18:44.445 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - Initializing Database Backend...
12/22 10:18:44.519 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - RocksDB persistence provider initialized.
12/22 10:19:14.197 [main] ERROR com.iota.iri.IRI - Exception during IOTA node initialisation:
java.lang.NegativeArraySizeException: null
        at org.rocksdb.RocksIterator.value0(Native Method) ~[iri-1.4.1.4.jar:na]
        at org.rocksdb.RocksIterator.value(RocksIterator.java:50) ~[iri-1.4.1.4.jar:na]
        at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.first(RocksDBPersistenceProvider.java:310) ~[iri-1.4.1.4.jar:na]
        at com.iota.iri.storage.Tangle.getFirst(Tangle.java:178) ~[iri-1.4.1.4.jar:na]
        at com.iota.iri.controllers.AddressViewModel.first(AddressViewModel.java:60) ~[iri-1.4.1.4.jar:na]
        at com.iota.iri.Iota.rescan_db(Iota.java:117) ~[iri-1.4.1.4.jar:na]
        at com.iota.iri.Iota.init(Iota.java:96) ~[iri-1.4.1.4.jar:na]
        at com.iota.iri.IRI.main(IRI.java:86) ~[iri-1.4.1.4.jar:na]
12/22 10:19:14.198 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...
12/22 10:19:20.198 [Shutdown Hook] ERROR com.iota.iri.IRI - Exception occurred shutting down IOTA node:
java.lang.NullPointerException: null
        at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:76) ~[iri-1.4.1.4.jar:na]
        at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:30) ~[iri-1.4.1.4.jar:na]
        at com.iota.iri.Iota.shutdown(Iota.java:176) ~[iri-1.4.1.4.jar:na]
        at com.iota.iri.IRI.lambda$shutdownHook$0(IRI.java:259) ~[iri-1.4.1.4.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
```
