### ISSUE TITLE
A basic Java error on Mac

### ISSUE THREAD

**Issue by reppolice** [iotaledger/iri#377]
Sorry if this is somehow obvious, for all I know I have a properly working JDK, but starting the wallet after manually creating the iri directing and moving iri.jar there I get

12/02 12:09:35.962 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.4.1.2
Exception in thread "main" 
java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException
	at com.iota.iri.IRI.main(IRI.java:55)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.ValidationException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 1 more
Process exited with status `1`

Any ideas? Thanks!

**Comment by nimearo** [comment]
Perhaps #364 can help

**Comment by nayanmshah** [comment]
This should be fixed after https://github.com/iotaledger/iri/pull/379 is merged. I have added the required maven dependency and tested with both jdk 1.8 and 1.9.
