### ISSUE TITLE
headless iri and fullnode wallet dies when syncing in endless loop

### ISSUE THREAD

**Issue by rnagler** [iotaledger/iri#381]
10:24
- Transaction processing runtime exception
java.lang.NullPointerException: null
    at com.iota.iri.network.TCPNeighbor.matches(TCPNeighbor.java:103) ~[iri.jar:na]
    at com.iota.iri.network.Node.preProcessReceivedData(Node.java:245) ~[iri.jar:na]
    at com.iota.iri.network.replicator.ReplicatorSourceProcessor.run(ReplicatorSourceProcessor.java:167) ~[iri.jar:na]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_152]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_152]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_152]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_152]
    at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]
12/03 22:20:59.582 [pool-5-thread-12] ERROR c.i.i.n.r.ReplicatorSourceProcessor
...
and so on

My impression after 3 days  of syncing is, that manual search for neighbors may lead to isles of neighbors with redundant transaction exchange. All new nodes go https://iotatangle.slack.com and sync with nodes that also have just arrived there. Mixing with full synced nodes would be necessary, but if you have a full node you dont want to change your neighbors. So a lot of useless work is done - maybe it hlps the tangle, but the effort to become a fully synced node seems to be very high

**Comment by alon-e** [comment]
this is more of a discussion about the IOTA network than specific implementation details. 
Common IOTA discussion boards:

- [https://forum.helloiota.com/](https://forum.helloiota.com/)
- [https://iota.stackexchange.com](https://iota.stackexchange.com)
- [https://www.reddit.com/r/Iota/](https://www.reddit.com/r/Iota/)
- [discord](https://bit.ly/iota-invite)
