### ISSUE TITLE
Can't find dependent libraries on Win7 64bit

### ISSUE THREAD

**Issue by sshadow** [iotaledger/iri#390]
The following is my output. It looks like it isn't creating the files at all. 

PS C:\iota> java -jar iri-1.4.1.2.jar -p 14265 -c iri.ini
12/05 17:48:06.256 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.4.1.2
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\xxx\AppData\Local\Temp\librocksdbjni7420186249303
400653.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.load0(Unknown Source)
        at java.lang.System.load(Unknown Source)
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
        at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
        at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
        at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
        at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.<init>(RocksDBPersistenceProvider.java:28)
        at com.iota.iri.Iota.initializeTangle(Iota.java:203)
        at com.iota.iri.Iota.init(Iota.java:94)
        at com.iota.iri.IRI.main(IRI.java:86)
12/05 17:48:19.218 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...
12/05 17:48:25.254 [Shutdown Hook] ERROR com.iota.iri.IRI - Exception occurred shutting down IOTA node:
java.lang.NullPointerException: null
        at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:76) ~[iri-1.4.1.2.jar
:na]
        at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:30) ~[iri-1.4.1.2.jar:na]
        at com.iota.iri.Iota.shutdown(Iota.java:178) ~[iri-1.4.1.2.jar:na]
        at com.iota.iri.IRI.lambda$shutdownHook$0(IRI.java:253) ~[iri-1.4.1.2.jar:na]
        at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_151]
PS C:\iota>

**Comment by onemoreitguy** [comment]
I got that problem too.
It seems that the rocksdbjni:5.7.3 has some undocumented dependency with visual C++ 2015/2017 runtimes or an Window OS security update... I generates an violation error.
Recompiling with v5.3.6 will allow you to run, but I don't recommended because I assume that can cause problem with unsupported database transactions.

**Comment by frankbenoit** [comment]
fyi, in RocksDB there is this [issue](https://github.com/facebook/rocksdb/issues/3307).

**Comment by alon-e** [comment]
consolidating with #350 - possible workaround: https://github.com/iotaledger/wallet/issues/773#issuecomment-352172896
