### ISSUE TITLE
cannot start iri on FreeBSD

### ISSUE THREAD

**Issue by xatru42** [iotaledger/iri#396]
Used stock Freebsd 64-bit 11.1.

Using native openjdk18 from ports fails with:

% java -jar iri-1.4.1.3.jar -p 14265
12/09 19:11:50.120 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.4.1.3
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.<init>(RocksDBPersistenceProvider.java:28)
	at com.iota.iri.Iota.initializeTangle(Iota.java:203)
	at com.iota.iri.Iota.init(Iota.java:94)
	at com.iota.iri.IRI.main(IRI.java:86)
Caused by: java.lang.UnsupportedOperationException: Cannot determine JNI library name for ARCH='amd64' OS='freebsd' name='rocksdb'
	at org.rocksdb.util.Environment.getJniLibraryName(Environment.java:66)
	at org.rocksdb.NativeLibraryLoader.<clinit>(NativeLibraryLoader.java:19)
	... 6 more
12/09 19:11:51.853 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...
12/09 19:11:57.861 [Shutdown Hook] ERROR com.iota.iri.IRI - Exception occurred shutting down IOTA node:
java.lang.NullPointerException: null
	at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:76) ~[iri-1.4.1.3.jar:na]
	at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:30) ~[iri-1.4.1.3.jar:na]
	at com.iota.iri.Iota.shutdown(Iota.java:178) ~[iri-1.4.1.3.jar:na]
	at com.iota.iri.IRI.lambda$shutdownHook$0(IRI.java:253) ~[iri-1.4.1.3.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_152]

trying to use the linux-orcale-jdk18 starts little further but dies then also:

% java -jar iri-1.4.1.3.jar -p 14265
12/09 19:09:48.092 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.4.1.3
Java HotSpot(TM) Server VM warning: You have loaded library /usr/lib/libz.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
12/09 19:09:50.482 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - Initializing Database Backend...
12/09 19:09:50.855 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - RocksDB persistence provider initialized.
12/09 19:09:50.860 [main] INFO  com.iota.iri.network.UDPReceiver - UDP replicator is accepting connections on udp port 14600
12/09 19:09:50.860 [UDP receiving thread] INFO  com.iota.iri.network.UDPReceiver - Spawning Receiver Thread
12/09 19:09:50.860 [UDP receiving thread] INFO  com.iota.iri.network.UDPReceiver - Receiver thread processed/dropped ratio: 0/0
12/09 19:09:50.860 [main] INFO  c.i.i.network.replicator.Replicator - Started ReplicatorSourcePool
12/09 19:09:50.932 [Thread-2] INFO  c.i.i.n.r.ReplicatorSourcePool - TCP replicator is accepting connections on tcp port 15600
12/09 19:09:50.936 [pool-2-thread-1] INFO  com.iota.iri.network.Node - Spawning Broadcaster Thread
12/09 19:09:50.937 [pool-2-thread-2] INFO  com.iota.iri.network.Node - Spawning Tips Requester Thread
12/09 19:09:50.937 [pool-2-thread-3] INFO  com.iota.iri.network.Node - Spawning Neighbor DNS Refresher Thread
12/09 19:09:50.937 [pool-2-thread-3] INFO  com.iota.iri.network.Node - Checking Neighbors' Ip...
12/09 19:09:50.937 [pool-2-thread-4] INFO  com.iota.iri.network.Node - Spawning Process Received Data Thread
12/09 19:09:50.938 [pool-2-thread-5] INFO  com.iota.iri.network.Node - Spawning Reply To Request Thread
12/09 19:09:50.938 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 0 , toReply = 0 / totalTransactions = 0
12/09 19:09:51.471 [main] ERROR com.iota.iri.IRI - Exception during IOTA node initialisation:
java.io.IOException: Function not implemented
	at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64) ~[na:1.8.0_152]
	at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47) ~[na:1.8.0_152]
	at com.iota.iri.IXI.init(IXI.java:60) ~[iri-1.4.1.3.jar:na]
	at com.iota.iri.IRI.main(IRI.java:88) ~[iri-1.4.1.3.jar:na]
12/09 19:09:51.471 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...
12/09 19:09:51.610 [pool-2-thread-1] INFO  com.iota.iri.network.Node - Shutting down Broadcaster Thread
12/09 19:09:51.610 [pool-2-thread-5] INFO  com.iota.iri.network.Node - Shutting down Reply To Request Thread
12/09 19:09:51.611 [pool-2-thread-4] INFO  com.iota.iri.network.Node - Shutting down Process Received Data Thread
12/09 19:09:51.940 [pool-2-thread-3] INFO  com.iota.iri.network.Node - Shutting down Neighbor DNS Refresher Thread

did anyone get iri working under FreeBSD ? for me it would be a requirement to run a full node.

**Comment by zitlo** [comment]
I had this problem aswell so Im running now ubuntu on bhyve..........

**Comment by vsatmydynipnet** [comment]
Same here, normally FreeBSD, in this case Debian Stretch

**Comment by zitlo** [comment]
It would be very nice to run iri in a freebsd jail...

**Comment by goligo** [comment]
To run IRI on FreeBSD you need to make a custom build of RocksDB (build target "rocksdbjava"), and patch IRI pom.xml with updated hash for the enforcer plugin.
You can find a fork of RocksDB with the necessary patches here:
https://github.com/goligo/rocksdb/tree/5.7.3-freebsd

**Comment by goligo** [comment]
RocksDB just submitted a change for official FreeBSD support. https://github.com/facebook/rocksdb/commit/a53c571d2d69e212922c92f275258ede328652ab

**Comment by goligo** [comment]
FreeBSD support for RocksDB has been released with 5.12, so upgrading IRI to use version 5.12 or later would do the trick and make IRI run on FreeBSD.

**Comment by legacycode** [comment]
The [RocksDB JNI](https://mvnrepository.com/artifact/org.rocksdb/rocksdbjni) from [mvnrepository](https://mvnrepository.com/) does not include the librocksdbjni-freebsd64.so. I created a branch and updated the RocksDB to version 5.17.2 with following result on FreeBSD 11.2:

`Logging - property 'logging-level' set to: [INFO]
11/28 21:31:54.218 [main] INFO  com.iota.iri.IRI$IRILauncher - Configuration is created using command line args only
11/28 21:31:54.224 [main] INFO  com.iota.iri.IRI$IRILauncher - parsed the following cmd args: [-p, 14800, --testnet]
11/28 21:31:54.228 [main] INFO  com.iota.iri.IRI$IRILauncher - Welcome to IRI Testnet 1.5.5
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.<init>(RocksDBPersistenceProvider.java:36)
        at com.iota.iri.Iota.initializeTangle(Iota.java:189)
        at com.iota.iri.Iota.init(Iota.java:122)
        at com.iota.iri.IRI$IRILauncher.main(IRI.java:119)
        at com.iota.iri.IRI.main(IRI.java:60)
Caused by: java.lang.RuntimeException: librocksdbjni-freebsd64.so was not found inside JAR.
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJarToTemp(NativeLibraryLoader.java:110)
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
        at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
        at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
        at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
        ... 5 more
11/28 21:31:56.708 [Shutdown Hook] INFO  com.iota.iri.IRI$IRILauncher - Shutting down IOTA node, please hold tight...
11/28 21:32:02.799 [Shutdown Hook] ERROR com.iota.iri.IRI$IRILauncher - Exception occurred shutting down IOTA node:
java.lang.NullPointerException: null
        at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:73) ~[iri-1.5.5.jar:na]
        at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:47) ~[iri-1.5.5.jar:na]
        at com.iota.iri.Iota.shutdown(Iota.java:177) ~[iri-1.5.5.jar:na]
        at com.iota.iri.IRI$IRILauncher.lambda$shutdownHook$0(IRI.java:140) ~[iri-1.5.5.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
`

I am not sure, how we can solve this issue in iri. Maybe a change request to the rocksdb team is the better way to get it in the dependency rocksdbjni jar file.
