### ISSUE TITLE
iri crashes with ERROR com.iota.iri.network.Node - Error accessing persistence store.

### ISSUE THREAD

**Issue by brenzi** [iotaledger/iri#398]
```
Dec 10 21:02:29 vps477593 java[3812]: 12/10 21:02:29.825 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 11 , toReply = 0 / totalTransactions = 5823457
Dec 10 21:02:39 vps477593 java[3812]: 12/10 21:02:39.862 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 0 , toReply = 0 / totalTransactions = 5823636
Dec 10 21:02:49 vps477593 java[3812]: 12/10 21:02:49.873 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 1 , toBroadcast = 0 , toRequest = 0 , toReply = 1 / totalTransactions = 5823678
Dec 10 21:02:50 vps477593 java[3812]: RocksDBExceptionJni::ThrowNew/StatusJni - Error: unexpected exception!
Dec 10 21:02:50 vps477593 java[3812]: 12/10 21:02:50.507 [pool-2-thread-4] ERROR com.iota.iri.network.Node - Error accessing persistence store.
Dec 10 21:02:50 vps477593 java[3812]: java.lang.IllegalArgumentException: Illegal value provided for SubCode.
Dec 10 21:02:50 vps477593 java[3812]:         at org.rocksdb.Status$SubCode.getSubCode(Status.java:109) ~[iri-1.4.1.2.jar:na]
Dec 10 21:02:50 vps477593 java[3812]:         at org.rocksdb.Status.<init>(Status.java:30) ~[iri-1.4.1.2.jar:na]
Dec 10 21:02:50 vps477593 java[3812]:         at org.rocksdb.RocksDB.write0(Native Method) ~[iri-1.4.1.2.jar:na]
Dec 10 21:02:50 vps477593 java[3812]:         at org.rocksdb.RocksDB.write(RocksDB.java:602) ~[iri-1.4.1.2.jar:na]
Dec 10 21:02:50 vps477593 java[3812]:         at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.saveBatch(RocksDBPersistenceProvider.java:345) ~[iri-1.4.1.2.jar:na]
Dec 10 21:02:50 vps477593 java[3812]:         at com.iota.iri.storage.Tangle.saveBatch(Tangle.java:53) ~[iri-1.4.1.2.jar:na]
Dec 10 21:02:50 vps477593 java[3812]:         at com.iota.iri.controllers.TransactionViewModel.store(TransactionViewModel.java:204) ~[iri-1.4.1.2.jar:na]
Dec 10 21:02:50 vps477593 java[3812]:         at com.iota.iri.network.Node.processReceivedData(Node.java:404) [iri-1.4.1.2.jar:na]
Dec 10 21:02:50 vps477593 java[3812]:         at com.iota.iri.network.Node.processReceivedDataFromQueue(Node.java:379) [iri-1.4.1.2.jar:na]
Dec 10 21:02:50 vps477593 java[3812]:         at com.iota.iri.network.Node.lambda$spawnProcessReceivedThread$13(Node.java:587) [iri-1.4.1.2.jar:na]
Dec 10 21:02:50 vps477593 java[3812]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_151]
Dec 10 21:02:50 vps477593 java[3812]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_151]
Dec 10 21:02:50 vps477593 java[3812]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
Dec 10 21:02:50 vps477593 java[3812]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
Dec 10 21:02:50 vps477593 java[3812]:         at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]

```

running on a vps with 4GB RAM running ubuntu 16.04 server

**Comment by alon-e** [comment]
Do you have enough free disc space?

**Comment by brenzi** [comment]
ooops. that was it. thanks.
Not exactly a self-explanatory error message ;-)

**Comment by glumb** [comment]
I ran into the same issue caused by over 100 `core.<number>` files in the iri directory. Each 257MB.
