### ISSUE TITLE
mvn package failed | Test phase error | Issue while initializing rocksdb 

### ISSUE THREAD

**Issue by manishbansal8843** [iotaledger/iri#400]
Hi All,

I am trying to run mvn package (mvn clean compile is success). I am gettting below error during test phase.

```Running com.iota.iri.BundleValidatorTest
12/12 23:59:39.626 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.575 sec <<< FAILURE!
com.iota.iri.BundleValidatorTest  Time elapsed: 0.574 sec  <<< ERROR!

java.lang.ExceptionInInitializerError
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.<init>(RocksDBPersistenceProvider.java:29)
	at com.iota.iri.BundleValidatorTest.setUp(BundleValidatorTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.UnsupportedOperationException: Cannot determine JNI library name for ARCH='x86' OS='windows 8.1' name='rocksdb'
	at org.rocksdb.util.Environment.getJniLibraryName(Environment.java:66)
	at org.rocksdb.NativeLibraryLoader.<clinit>(NativeLibraryLoader.java:19)
	... 26 more
```

Java version: 1.8
Os: windows 8.1 64 bit

**Comment by manishbansal8843** [comment]
Issue got resolved by installing jdk 1.8. It seems like rocksdb does not have support for windows 32 bit. In my case, it was trying to load 64 bit rocksdb dll via 32 bit jvm. After updating jvm, issue got resolved and build is success.
