### ISSUE TITLE
iri 1.4.1.4 won't run on Windows, just like 1.4.1.2

### ISSUE THREAD

**Issue by hapklaar** [iotaledger/iri#414]
`D:\IOTA>java -Xmx5g -Xms512m -jar iri-1.4.1.4.jar --config config1.txt
12/19 11:53:49.104 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.4.1.4
12/19 11:53:55.347 [main] INFO  com.iota.iri.IRI - You have set the debug flag. To enable debug output, you need to uncomment the DEBUG appender in the source tree at iri/src/main/resources/logback.xml and re-p
ackage iri.jar
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\Administrator\AppData\Local\Temp\2\librocksdbjni7575071225281676756.dll: A dynamic link library (DLL) initialization routine failed
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.load0(Unknown Source)
        at java.lang.System.load(Unknown Source)
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
        at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
        at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
        at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
        at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.<init>(RocksDBPersistenceProvider.java:28)
        at com.iota.iri.Iota.initializeTangle(Iota.java:201)
        at com.iota.iri.Iota.init(Iota.java:92)
        at com.iota.iri.IRI.main(IRI.java:86)
12/19 11:54:51.863 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...
12/19 11:54:57.894 [Shutdown Hook] ERROR com.iota.iri.IRI - Exception occurred shutting down IOTA node:
java.lang.NullPointerException: null
        at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:76) ~[iri-1.4.1.4.jar:na]
        at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:30) ~[iri-1.4.1.4.jar:na]
        at com.iota.iri.Iota.shutdown(Iota.java:176) ~[iri-1.4.1.4.jar:na]
        at com.iota.iri.IRI.lambda$shutdownHook$0(IRI.java:259) ~[iri-1.4.1.4.jar:na]
        at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_152]`

**Comment by MiyazawaK** [comment]
[https://github.com/iotaledger/iri/issues/350#issuecomment-348781909](https://github.com/iotaledger/iri/issues/350#issuecomment-348781909)

worked for me in IRI 1.4.1.3, but I don't know if its safe to use...

**Comment by rnagler** [comment]
that's the same problem and temp solution as in
https://github.com/iotaledger/wallet/issues/817

**Comment by solracor** [comment]
thenanox comentou on 4 May • 
Eu tenho verificado em torno de rocksdb e este bug é algo relacionado à CPU física que você tem no seu computador. Se você tem processadores Intel = Haswell (4xxx) provavelmente funciona para você. Caso você esteja usando uma CPU anterior, ela não funcionará com 5.7.3 rocksdbjni.

Isso acontece por causa da maneira como o rocksdb constrói para o windows o pacote rocksdbjni. Em algum ponto após o 5.3.6 eles começaram a incluir o sinalizador AVX2 na construção, que é uma extensão das instruções da CPU para Haswell => CPUs (mais aqui também para usuários da AMD https://en.wikipedia.org/wiki/Advanced_Vector_Extensions# Advanced_Vector_Extensions_2 )

O problema em rocksdb é aqui: 
facebook / rocksdb # 3307

Soluções:

Uma solução para o IRI é usar a dependência 5.3.6 do pom.xml para rocksdbjni, mas não sei se o IRI usa alguma funcionalidade do 5.7.3. Esta solução será de compatibilidade com versões anteriores para usuários antigos de cpu.

A outra solução é criar uma compilação iota a partir de fontes usando estas instruções https://github.com/facebook/rocksdb/wiki/Building-on-Windows e fazer upload para o mvnrepository para que todos possam usá-la. (ethereum tem este https://mvnrepository.com/artifact/org.ethereum/rocksdbjni )
