### ISSUE TITLE
Ubuntu 16 - Node will not stay up

### ISSUE THREAD

**Issue by SatoshiReport** [iotaledger/iri#415]
Here is my startup log.  I can provide other info as required.

`12/19 13:34:02.527 [main] INFO  com.iota.iri.IRI - Remote access enabled. Binding API socket to listen any interface.
12/19 13:34:02.535 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.4.1.4
12/19 13:34:24.402 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - Initializing Database Backend...
12/19 13:34:26.291 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - RocksDB persistence provider initialized.
12/19 13:34:26.318 [main] INFO  com.iota.iri.network.UDPReceiver - UDP replicator is accepting connections on udp port 14700
12/19 13:34:26.342 [UDP receiving thread] INFO  com.iota.iri.network.UDPReceiver - Spawning Receiver Thread
12/19 13:34:26.342 [UDP receiving thread] INFO  com.iota.iri.network.UDPReceiver - Receiver thread processed/dropped ratio: 0/0
12/19 13:34:26.347 [main] INFO  c.i.i.network.replicator.Replicator - Started ReplicatorSourcePool
12/19 13:34:26.369 [main] ERROR com.iota.iri.IRI - Exception during IOTA node initialisation:
java.lang.NullPointerException: null
        at com.iota.iri.network.Node.isUriValid(Node.java:685) ~[iri-1.4.1.4.jar:na]
        at com.iota.iri.network.Node.lambda$parseNeighborsConfig$17(Node.java:718) ~[iri-1.4.1.4.jar:na]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[na:1.8.0_151]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_151]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_151]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_151]
        at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175) ~[na:1.8.0_151]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:1.8.0_151]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_151]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_151]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:1.8.0_151]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:1.8.0_151]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_151]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[na:1.8.0_151]
        at com.iota.iri.network.Node.parseNeighborsConfig(Node.java:723) ~[iri-1.4.1.4.jar:na]
        at com.iota.iri.network.Node.init(Node.java:132) ~[iri-1.4.1.4.jar:na]
        at com.iota.iri.Iota.init(Iota.java:111) ~[iri-1.4.1.4.jar:na]
        at com.iota.iri.IRI.main(IRI.java:86) ~[iri-1.4.1.4.jar:na]
12/19 13:34:26.380 [Thread-2] INFO  c.i.i.n.r.ReplicatorSourcePool - TCP replicator is accepting connections on tcp port 14700
12/19 13:34:26.417 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...
12/19 13:34:33.881 [UDP receiving thread] INFO  com.iota.iri.network.UDPReceiver - Shutting down spawning Receiver Thread
12/19 13:34:34.299 [Shutdown Hook] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers...
`

**Comment by Blogshot** [comment]
Relevant error message:
```
13:34:26.369 [main] ERROR com.iota.iri.IRI - Exception during IOTA node initialisation: java.lang.NullPointerException: null at com.iota.iri.network.Node.isUriValid(Node.java:685) 
~[iri-1.4.1.4.jar:na] at com.iota.iri.network.Node.lambda$parseNeighborsConfig$17(Node.java:718) 
~[iri-1.4.1.4.jar:na] at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) 
~[na:1.8.0_151] at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) 
~[na:1.8.0_151] at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) 
~[na:1.8.0_151] at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) 
~[na:1.8.0_151] at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175) 
~[na:1.8.0_151] at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) 
~[na:1.8.0_151] at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) 
~[na:1.8.0_151] at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) 
~[na:1.8.0_151] at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) 
~[na:1.8.0_151] at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) 
~[na:1.8.0_151] at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) 
~[na:1.8.0_151] at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) 
~[na:1.8.0_151] at com.iota.iri.network.Node.parseNeighborsConfig(Node.java:723) 
~[iri-1.4.1.4.jar:na] at com.iota.iri.network.Node.init(Node.java:132) 
~[iri-1.4.1.4.jar:na] at com.iota.iri.Iota.init(Iota.java:111) 
~[iri-1.4.1.4.jar:na] at com.iota.iri.IRI.main(IRI.java:86) 
```

To me it looks like the URI of one of your neighbors isn't correctly formatted.
(see `parseNeighborsConfig` and `java.lang.NullPointerException: null at com.iota.iri.network.Node.isUriValid`)

Please look into your NEIGHBOR-Parameter.

**Comment by H3npi** [comment]
This PR should help here a little more:
https://github.com/iotaledger/iri/pull/419

**Comment by SatoshiReport** [comment]
Thanks!
