### ISSUE TITLE
Try to run Full Node on windows 

### ISSUE THREAD

**Issue by mountainbrother** [iotaledger/iri#420]
I will support the network and by a windows server in a cloudcenter:
install x64 and try to start:

Can someone help me?

12/20 16:25:14.619 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.4.1.4
Exception in thread "main" 
java.lang.UnsatisfiedLinkError: C:\Users\aatadmin\AppData\Local\Temp\2\librocksdbjni5529758410206625651.dll: Eine DLL-Initialisierungsroutine ist fehlgeschlagen
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.<init>(RocksDBPersistenceProvider.java:28)
	at com.iota.iri.Iota.initializeTangle(Iota.java:201)
	at com.iota.iri.Iota.init(Iota.java:92)
	at com.iota.iri.IRI.main(IRI.java:86)
12/20 16:25:20.430 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...
12/20 16:25:26.436 [Shutdown Hook] ERROR com.iota.iri.IRI - Exception occurred shutting down IOTA node: 
java.lang.NullPointerException: null
	at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:76) ~[iri.jar:na]
	at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:30) ~[iri.jar:na]
	at com.iota.iri.Iota.shutdown(Iota.java:176) ~[iri.jar:na]
	at com.iota.iri.IRI.lambda$shutdownHook$0(IRI.java:259) ~[iri.jar:na]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_151]
Process exited with status 1

**Comment by MiyazawaK** [comment]
Same as [https://github.com/iotaledger/iri/issues/350#issuecomment-348781909](https://github.com/iotaledger/iri/issues/350#issuecomment-348781909)

again, not sure if its safe to use in production

**Comment by swdevMPaul** [comment]
Greetings.
Now if one needs to run IOTA Wallet on Windows. Please help to resolve next.

If I install and run the IOTA Wallet on Windows  - 2 exceptions (errors) one in Exception in thread "main" 
java.lang.UnsatisfiedLinkError: C:\Users\User\AppData\Local\Temp\librocksdbjni7861117433009785088.dll: A dynamic link library (DLL) initialization routine failed and one in java.lang.NullPointerException: null
	at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown

The next is in

java.lang.NullPointerException: null
	at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:76) ~[iri.jar:na]

It is version 2.5.6. I think with other versions it will be the same issue.
 
I get the same error when I build the iri with maven (mvn clean compile passess ok, in mvn package there is the problem):

Tests in error:
  com.iota.iri.BundleValidatorTest: C:\Users\User\AppData\Local\Temp\librocksdbjni16850478755329069913.dll: A dynamic link library (DLL) initialization routine failed
  quietGetTail(com.iota.iri.controllers.BundleViewModelTest): Could not initialize class org.rocksdb.RocksDB
  fromHash(com.iota.iri.controllers.BundleViewModelTest): Could not initialize class org.rocksdb.RocksDB
  getTail(com.iota.iri.controllers.BundleViewModelTest): Could not initialize class org.rocksdb.RocksDB
  quietFromHash(com.iota.iri.controllers.BundleViewModelTest): Could not initialize class org.rocksdb.RocksDB
  getTransactionViewModels(com.iota.iri.controllers.BundleViewModelTest): Could not initialize class org.rocksdb.RocksDB
  initSnapshot(com.iota.iri.controllers.MilestoneViewModelTest): Could not initialize class org.rocksdb.RocksDB
  nextGreaterThan(com.iota.iri.controllers.MilestoneViewModelTest): Could not initialize class org.rocksdb.RocksDB
  previous(com.iota.iri.controllers.MilestoneViewModelTest): Could not initialize class org.rocksdb.RocksDB
  latest(com.iota.iri.controllers.MilestoneViewModelTest): Could not initialize class org.rocksdb.RocksDB
  getMilestone(com.iota.iri.controllers.MilestoneViewModelTest): Could not initialize class org.rocksdb.RocksDB
  latestSnapshot(com.iota.iri.controllers.MilestoneViewModelTest): Could not initialize class org.rocksdb.RocksDB
  firstWithSnapshot(com.iota.iri.controllers.MilestoneViewModelTest): Could not initialize class org.rocksdb.RocksDB
  getHash(com.iota.iri.controllers.MilestoneViewModelTest): Could not initialize class org.rocksdb.RocksDB
  next(com.iota.iri.controllers.MilestoneViewModelTest): Could not initialize class org.rocksdb.RocksDB
  nextWithSnapshot(com.iota.iri.controllers.MilestoneViewModelTest): Could not initialize class org.rocksdb.RocksDB
  first(com.iota.iri.controllers.MilestoneViewModelTest): Could not initialize class org.rocksdb.RocksDB
  index(com.iota.iri.controllers.MilestoneViewModelTest): Could not initialize class org.rocksdb.RocksDB
  store(com.iota.iri.controllers.MilestoneViewModelTest): Could not initialize class org.rocksdb.RocksDB
  snapshot(com.iota.iri.controllers.MilestoneViewModelTest): Could not initialize class org.rocksdb.RocksDB
  PrevBefore(com.iota.iri.controllers.MilestoneViewModelTest): Could not initialize class org.rocksdb.RocksDB
  updateSnapshot(com.iota.iri.controllers.MilestoneViewModelTest): Could not initialize class org.rocksdb.RocksDB
  com.iota.iri.controllers.TransactionViewModelTest: Could not initialize class org.rocksdb.RocksDB
  com.iota.iri.service.TipsManagerTest: Could not initialize class org.rocksdb.RocksDB
  get(com.iota.iri.storage.TangleTest): Could not initialize class org.rocksdb.RocksDB
  save(com.iota.iri.storage.TangleTest): Could not initialize class org.rocksdb.RocksDB
  getKeysStartingWithValue(com.iota.iri.storage.TangleTest): Could not initialize class org.rocksdb.RocksDB
  com.iota.iri.TransactionValidatorTest: Could not initialize class org.rocksdb.RocksDB
  com.iota.iri.TransactionValidatorTest

Tests run: 100, Failures: 0, Errors: 29, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:00 min
[INFO] Finished at: 2017-12-29T09:33:45+02:00
[INFO] Final Memory: 22M/73M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project iri: There are test failures.

Why it does not create the dll in this directory:

C:\Users\User\AppData\Local\Temp

Yes, this is surely the problem is with the RocksDB dll, which is quite important component of the IRI.

I have also compiled rocksdbjni.jars from here http://repo1.maven.org/maven2/org/rocksdb/rocksdbjni/5.8.7/, but this doesn't help either.

Is this true we found that IOTA IRI and Wallet do not work on Windows platform ?

Does anybody have an idea how to fix this ?

**Comment by nevrrmind** [comment]
Try: https://github.com/iotaledger/wallet/issues/773#issuecomment-352172896 For me it worked.
