### ISSUE TITLE
iri stop sync becouse one error during Solid Milestone updating

### ISSUE THREAD

**Issue by avihaiandroid** [iotaledger/iri#453]
iri stop sync becouse one error during Solid Milestone updating

> [Solid Milestone Tracker] ERROR com.iota.iri.Milestone - Error during Solid Milestone updating
java.lang.NullPointerException: null
        at com.iota.iri.model.Transaction.metadata(Transaction.java:68) ~[iri-1.4.1.4.jar:na]
        at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.update(RocksDBPersistenceProvider.java:385) ~[iri-1.4.1.4.jar:na]
        at com.iota.iri.storage.Tangle.update(Tangle.java:92) ~[iri-1.4.1.4.jar:na]
        at com.iota.iri.controllers.TransactionViewModel.update(TransactionViewModel.java:124) ~[iri-1.4.1.4.jar:na]
        at com.iota.iri.controllers.TransactionViewModel.setValidity(TransactionViewModel.java:313) ~[iri-1.4.1.4.jar:na]
        at com.iota.iri.BundleValidator.validate(BundleValidator.java:105) ~[iri-1.4.1.4.jar:na]
        at com.iota.iri.LedgerValidator.getLatestDiff(LedgerValidator.java:84) ~[iri-1.4.1.4.jar:na]
        at com.iota.iri.LedgerValidator.updateSnapshot(LedgerValidator.java:249) ~[iri-1.4.1.4.jar:na]
        at com.iota.iri.Milestone.updateLatestSolidSubtangleMilestone(Milestone.java:228) ~[iri-1.4.1.4.jar:na]
        at com.iota.iri.Milestone.lambda$init$1(Milestone.java:150) ~[iri-1.4.1.4.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]

**Comment by avihaiandroid** [comment]
Fixed in 1.4.1.6
