### ISSUE TITLE
ERROR com.iota.iri.network.Node - Error accessing persistence store. (RocksDB)

### ISSUE THREAD

**Issue by mjollnir14** [iotaledger/iri#466]
After a few hours, bug is reproducible

Appends on loop and blocks all transaction treatment

```
Jan 05 14:32:16 osiris IRI[9073]: 01/05 14:32:16.434 [pool-2-thread-4] ERROR com.iota.iri.network.Node - Error accessing persistence store.
Jan 05 14:32:16 osiris IRI[9073]: java.lang.IllegalArgumentException: Illegal value provided for SubCode.
Jan 05 14:32:16 osiris IRI[9073]: at org.rocksdb.Status$SubCode.getSubCode(Status.java:109) ~[iri-1.4.1.4-compiled.jar:na]
Jan 05 14:32:16 osiris IRI[9073]: at org.rocksdb.Status.<init>(Status.java:30) ~[iri-1.4.1.4-compiled.jar:na]
Jan 05 14:32:16 osiris IRI[9073]: at org.rocksdb.RocksDB.write0(Native Method) ~[iri-1.4.1.4-compiled.jar:na]
Jan 05 14:32:16 osiris IRI[9073]: at org.rocksdb.RocksDB.write(RocksDB.java:602) ~[iri-1.4.1.4-compiled.jar:na]
Jan 05 14:32:16 osiris IRI[9073]: at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.saveBatch(RocksDBPersistenceProvider.java:349) ~[iri-1.4.1.4-compiled.jar:na]
Jan 05 14:32:16 osiris IRI[9073]: at com.iota.iri.storage.Tangle.saveBatch(Tangle.java:53) ~[iri-1.4.1.4-compiled.jar:na]
Jan 05 14:32:16 osiris IRI[9073]: at com.iota.iri.controllers.TransactionViewModel.store(TransactionViewModel.java:207) ~[iri-1.4.1.4-compiled.jar:na]
Jan 05 14:32:16 osiris IRI[9073]: at com.iota.iri.network.Node.processReceivedData(Node.java:385) [iri-1.4.1.4-compiled.jar:na]
Jan 05 14:32:16 osiris IRI[9073]: at com.iota.iri.network.Node.processReceivedDataFromQueue(Node.java:359) [iri-1.4.1.4-compiled.jar:na]
Jan 05 14:32:16 osiris IRI[9073]: at com.iota.iri.network.Node.lambda$spawnProcessReceivedThread$8(Node.java:569) [iri-1.4.1.4-compiled.jar:na]
Jan 05 14:32:16 osiris IRI[9073]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_151]
Jan 05 14:32:16 osiris IRI[9073]: at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_151]
Jan 05 14:32:16 osiris IRI[9073]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
Jan 05 14:32:16 osiris IRI[9073]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
Jan 05 14:32:16 osiris IRI[9073]: at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
Jan 05 14:32:17 osiris IRI[9073]: RocksDBExceptionJni::ThrowNew/StatusJni - Error: unexpected exception!
```

```
  "appName": "IRI",
  "appVersion": "1.4.1.4",
  "jreAvailableProcessors": 12,
  "jreFreeMemory": 108457760,
  "jreVersion": "1.8.0_151",
  "jreMaxMemory": 7249854464,
  "jreTotalMemory": 1374158848,
  "latestMilestone": "KFJJFNLDRDHHVOGTAKMZZKBYALXTNEIPGUHOZWBALVTEUGUWIENFJOBMENXVWOESK9TEADIKWOM9A9999",
  "latestMilestoneIndex": 320157,
  "latestSolidSubtangleMilestone": "SOJAYGBANEXRVYBXOSLNLLCXILWMCSMMAGKLWUZYAJYCYJ9MYZLRKGEAAIUPNLPZYMCHFZZQQYRQA9999",
  "latestSolidSubtangleMilestoneIndex": 258974,
  "neighbors": 6,
  "packetsQueueSize": 0,
  "time": 1515159114897,
  "tips": 5701,
  "transactionsToRequest": 515,
  "duration": 0
}
iota@osiris:~$ uname -a
Linux osiris 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux

Official iri binary 
```

**Comment by alon-e** [comment]
Could your disk be full?

**Comment by mjollnir14** [comment]
It's not near full.

More like a full free inodes to allocate maybe. When I check there is a
good pourcentage free but the check should be made when the exception is
thrown for the first time

I'll give result of df -ih later on

**Comment by mjollnir14** [comment]
When iri is running normally (2 hours uptime):

```
root@osiris:/lib/systemd/system# df -i
Filesystem       Inodes  IUsed    IFree IUse% Mounted on
/dev/md1        1310720 363387   947333   28% /
udev            4112257    415  4111842    1% /dev
tmpfs           4114415    787  4113628    1% /run
tmpfs           4114415      3  4114412    1% /dev/shm
tmpfs           4114415      7  4114408    1% /run/lock
tmpfs           4114415     13  4114402    1% /sys/fs/cgroup
/dev/md0          76608    328    76280    1% /boot
/dev/md2       14262272 353139 13909133    3% /data
tmpfs           4114415      4  4114411    1% /run/user/1001
tmpfs           4114415      4  4114411    1% /run/user/0
```

```
root@osiris:/lib/systemd/system# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/md1         20G   16G  3.2G  84% /
udev             10M     0   10M   0% /dev
tmpfs           6.3G  646M  5.7G  11% /run
tmpfs            16G  8.0K   16G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/md0        282M   33M  231M  13% /boot
/dev/md2        215G  176G   28G  87% /data
tmpfs           3.2G     0  3.2G   0% /run/user/1001
tmpfs           3.2G     0  3.2G   0% /run/user/0
```

PS: iri and database are on /data

**Comment by mjollnir14** [comment]
After error (still looping on the exception. The first exception has happened earlier): 

```
root@osiris:/lib/systemd/system# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/md1         20G   16G  3.1G  84% /
udev             10M     0   10M   0% /dev
tmpfs           6.3G  646M  5.7G  11% /run
tmpfs            16G  8.0K   16G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/md0        282M   33M  231M  13% /boot
/dev/md2        215G  176G   28G  87% /data
tmpfs           3.2G     0  3.2G   0% /run/user/1001
tmpfs           3.2G     0  3.2G   0% /run/user/0
root@osiris:/lib/systemd/system# df -ih
Filesystem     Inodes IUsed IFree IUse% Mounted on
/dev/md1         1.3M  355K  926K   28% /
udev             4.0M   415  4.0M    1% /dev
tmpfs            4.0M   787  4.0M    1% /run
tmpfs            4.0M     3  4.0M    1% /dev/shm
tmpfs            4.0M     7  4.0M    1% /run/lock
tmpfs            4.0M    13  4.0M    1% /sys/fs/cgroup
/dev/md0          75K   328   75K    1% /boot
/dev/md2          14M  341K   14M    3% /data
tmpfs            4.0M     4  4.0M    1% /run/user/1001
tmpfs            4.0M     4  4.0M    1% /run/user/0

```

**Comment by mjollnir14** [comment]
I'll pause this issue and upgrade to 1.4.1.6

**Comment by mjollnir14** [comment]
Same issue on 1.4.1.6

```
Jan 07 11:37:52 osiris IRI[28793]: RocksDBExceptionJni::ThrowNew/StatusJni - Error: unexpected exception!
Jan 07 11:37:52 osiris IRI[28793]: 01/07 11:37:52.057 [pool-2-thread-4] ERROR com.iota.iri.network.Node - Error accessing persistence store.
Jan 07 11:37:52 osiris IRI[28793]: java.lang.IllegalArgumentException: Illegal value provided for SubCode.
Jan 07 11:37:52 osiris IRI[28793]: at org.rocksdb.Status$SubCode.getSubCode(Status.java:109) ~[iri-1.4.1.6.jar:na]
Jan 07 11:37:52 osiris IRI[28793]: at org.rocksdb.Status.<init>(Status.java:30) ~[iri-1.4.1.6.jar:na]
Jan 07 11:37:52 osiris IRI[28793]: at org.rocksdb.RocksDB.write0(Native Method) ~[iri-1.4.1.6.jar:na]
Jan 07 11:37:52 osiris IRI[28793]: at org.rocksdb.RocksDB.write(RocksDB.java:602) ~[iri-1.4.1.6.jar:na]
Jan 07 11:37:52 osiris IRI[28793]: at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.saveBatch(RocksDBPersistenceProvider.java:349) ~[iri-1.4.1.6.jar:na]
Jan 07 11:37:52 osiris IRI[28793]: at com.iota.iri.storage.Tangle.saveBatch(Tangle.java:53) ~[iri-1.4.1.6.jar:na]
Jan 07 11:37:52 osiris IRI[28793]: at com.iota.iri.controllers.TransactionViewModel.store(TransactionViewModel.java:207) ~[iri-1.4.1.6.jar:na]
Jan 07 11:37:52 osiris IRI[28793]: at com.iota.iri.network.Node.processReceivedData(Node.java:376) [iri-1.4.1.6.jar:na]
Jan 07 11:37:52 osiris IRI[28793]: at com.iota.iri.network.Node.processReceivedDataFromQueue(Node.java:358) [iri-1.4.1.6.jar:na]
Jan 07 11:37:52 osiris IRI[28793]: at com.iota.iri.network.Node.lambda$spawnProcessReceivedThread$8(Node.java:559) [iri-1.4.1.6.jar:na]
Jan 07 11:37:52 osiris IRI[28793]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_151]
Jan 07 11:37:52 osiris IRI[28793]: at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_151]
Jan 07 11:37:52 osiris IRI[28793]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
Jan 07 11:37:52 osiris IRI[28793]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
Jan 07 11:37:52 osiris IRI[28793]: at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]

```

**Comment by brunoamancio** [comment]
did you try deleting the mainnetdb and mainnet.log folders and downloading it from iota.partners?

**Comment by mjollnir14** [comment]
Yes that has been done

**Comment by pandamaci** [comment]
Can you check if you have noexec specified for /tmp partition in /etc/fstab?
If yes, you will have to remove it.

**Comment by mjollnir14** [comment]
/tmp is in my / which hasn't that option enabled

```
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,relatime,size=10240k,nr_inodes=4112257,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,relatime,size=6583064k,mode=755)
/dev/md1 on / type ext4 (rw,relatime,errors=remount-ro,data=ordered)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=22,pgrp=1,timeout=300,minproto=5,maxproto=5,direct)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime)
/dev/md0 on /boot type ext4 (rw,relatime,data=ordered)
/dev/md2 on /data type ext4 (rw,relatime,data=ordered)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
tmpfs on /run/user/1001 type tmpfs (rw,nosuid,nodev,relatime,size=3291532k,mode=700,uid=1001,gid=1001)
tmpfs on /run/user/0 type tmpfs (rw,nosuid,nodev,relatime,size=3291532k,mode=700)
```

**Comment by devlaam** [comment]
I have the same issues here. After a few day's of activity:
`01/09 09:48:03.853 [pool-2-thread-4] ERROR com.iota.iri.network.Node - Error accessing persistence store.
org.rocksdb.RocksDBException: While fdatasync: mainnetdb/111261.sst: Input/output error
        at org.rocksdb.RocksDB.write0(Native Method) ~[iri-1.4.1.6.jar:na]
        at org.rocksdb.RocksDB.write(RocksDB.java:602) ~[iri-1.4.1.6.jar:na]
        at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.saveBatch(RocksDBPersistenceProvider.java:349) ~[iri-1.4.1.6.jar:na]
        at com.iota.iri.storage.Tangle.saveBatch(Tangle.java:53) ~[iri-1.4.1.6.jar:na]
        at com.iota.iri.controllers.TransactionViewModel.store(TransactionViewModel.java:207) ~[iri-1.4.1.6.jar:na]
        at com.iota.iri.network.Node.processReceivedData(Node.java:376) [iri-1.4.1.6.jar:na]
        at com.iota.iri.network.Node.processReceivedDataFromQueue(Node.java:358) [iri-1.4.1.6.jar:na]
        at com.iota.iri.network.Node.lambda$spawnProcessReceivedThread$8(Node.java:559) [iri-1.4.1.6.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
 `
Running on 1.4.1.6.

**Comment by jakubcech** [comment]
Are you still experiencing this error?

**Comment by mjollnir14** [comment]
@jakubcech no

**Comment by jakubcech** [comment]
We can reopen if anyone still experiences this.

**Comment by lakshay-saini** [comment]
I got this error `09/20 14:34:04.993 [Tip Solidity Rescan] ERROR com.iota.iri.service.TipsSolidifier - Error during solidity scan : {}
org.rocksdb.RocksDBException: block checksum mismatch: expected 3146606367, got 1829597805  in db/000717.sst offset 30432575 size 5000
        at org.rocksdb.RocksDB.get(Native Method) ~[iri-1.5.3.jar:na]
        at org.rocksdb.RocksDB.get(RocksDB.java:810) ~[iri-1.5.3.jar:na]
        at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.get(RocksDBPersistenceProvider.java:157) ~[iri-1.5.3.jar:na]
        at com.iota.iri.storage.Tangle.load(Tangle.java:40) ~[iri-1.5.3.jar:na]
        at com.iota.iri.controllers.TransactionViewModel.fromHash(TransactionViewModel.java:74) ~[iri-1.5.3.jar:na]
        at com.iota.iri.TransactionValidator.checkSolidity(TransactionValidator.java:139) ~[iri-1.5.3.jar:na]
        at com.iota.iri.service.TipsSolidifier.scanTipsForSolidity(TipsSolidifier.java:66) ~[iri-1.5.3.jar:na]
        at com.iota.iri.service.TipsSolidifier.lambda$init$0(TipsSolidifier.java:36) ~[iri-1.5.3.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]

`
