### ISSUE TITLE
After release 1.4.1.6 - java.lang.IllegalArgumentException: port out of range:-1

### ISSUE THREAD

**Issue by brunoamancio** [iotaledger/iri#468]
I use port 16000 since many versions ago.  Here are the logs:

[main] INFO  com.iota.iri.IRI - Welcome to IRI 1.4.1.6
[main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - Initializing Database Backend...
[main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - RocksDB persistence provider initialized.
[main] INFO  com.iota.iri.network.UDPReceiver - UDP replicator is accepting connections on udp port 16100
[UDP receiving thread] INFO  com.iota.iri.network.UDPReceiver - Spawning Receiver Thread
[UDP receiving thread] INFO  com.iota.iri.network.UDPReceiver - Receiver thread processed/dropped ratio: 0/0
[main] INFO  c.i.i.network.replicator.Replicator - Started ReplicatorSourcePool
[Thread-2] INFO  c.i.i.n.r.ReplicatorSourcePool - TCP replicator is accepting connections on tcp port 16200
[main] INFO  com.iota.iri.network.Node - -> Adding neighbor : XYZ
[main] INFO  com.iota.iri.network.Node - -> Adding neighbor : XYZ
[main] INFO  com.iota.iri.network.Node - -> Adding neighbor : XYZ
[main] INFO  com.iota.iri.network.Node - -> Adding neighbor : XYZ
[main] INFO  com.iota.iri.network.Node - -> Adding neighbor : XYZ
[main] INFO  com.iota.iri.network.Node - -> Adding neighbor : XYZ
[main] INFO  com.iota.iri.network.Node - -> Adding neighbor : XYZ
[main] INFO  com.iota.iri.network.Node - -> Adding neighbor : XYZ
[main] ERROR com.iota.iri.IRI - Exception during IOTA node initialisation:
 java.lang.IllegalArgumentException: port out of range:-1
         at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143) ~[na:1.8.0_151]
         at java.net.InetSocketAddress.<init>(InetSocketAddress.java:224) ~[na:1.8.0_151]
         at com.iota.iri.network.Node.isUriValid(Node.java:668) ~[iri-1.4.1.6.jar:na]
         at com.iota.iri.network.Node.lambda$parseNeighborsConfig$17(Node.java:703) ~[iri-1.4.1.6.jar:na]
         at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[na:1.8.0_151]
         at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_151]
         at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_151]
         at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_151]
         at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175) ~[na:1.8.0_151]
         at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:1.8.0_151]
         at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_151]
         at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_151]
         at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:1.8.0_151]
         at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:1.8.0_151]
         at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_151]
         at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[na:1.8.0_151]
         at com.iota.iri.network.Node.parseNeighborsConfig(Node.java:708) ~[iri-1.4.1.6.jar:na]
         at com.iota.iri.network.Node.init(Node.java:119) ~[iri-1.4.1.6.jar:na]
         at com.iota.iri.Iota.init(Iota.java:111) ~[iri-1.4.1.6.jar:na]
         at com.iota.iri.IRI.main(IRI.java:73) ~[iri-1.4.1.6.jar:na]
[Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...

**Comment by brunoamancio** [comment]
I found the issue, it was a new neighbor's entry in the config files. It was wrongly formatted.
