### ISSUE TITLE
When shutting down IRI, the last line in the report throws RejectedExecutionException when receive packet from neighbor

### ISSUE THREAD

**Issue by yillkid** [iotaledger/iri#484]
HOST: http://node.deviceproof.org:14265

----

A traceback exception message as below:
```
01/16 14:19:48.507 [UDP receiving thread] INFO  com.iota.iri.network.UDPReceiver - Shutting down spawning Receiver Thread
Exception in thread "Thread-1" java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@522a4c0e rejected from java.util.concurrent.ThreadPoolExecutor@19189d8[Shutting down, pool size = 12, active threads = 12, queued tasks = 0, completed tasks = 41150]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
        at com.iota.iri.network.replicator.ReplicatorSinkPool.createSink(ReplicatorSinkPool.java:76)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at com.iota.iri.network.replicator.ReplicatorSinkPool.run(ReplicatorSinkPool.java:70)
        at java.lang.Thread.run(Thread.java:748)
01/16 14:20:01.009 [Shutdown Hook] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers...
```  
According the above message section, exception occurred [during broadcasting data from neighbor with UDP protocol](https://github.com/iotaledger/iri/blob/6889f59c2ec1e74bb2d6eec68cb3d8c019ff966b/src/main/java/com/iota/iri/network/UDPReceiver.java#L92), but this Node does not connect with any UDP protocol neighbors, the output of **getNeighborInfo** API command as below:

```
{
    "duration": 2,
    "neighbors": [
        {
            "address": "xxxx:15600",
            "connectionType": "tcp",
            "numberOfAllTransactions": 0,
            "numberOfInvalidTransactions": 0,
            "numberOfNewTransactions": 0,
            "numberOfRandomTransactionRequests": 0,
            "numberOfSentTransactions": 0
        },
        {
            "address": "xxxx:16100",
            "connectionType": "tcp",
            "numberOfAllTransactions": 37294,
            "numberOfInvalidTransactions": 0,
            "numberOfNewTransactions": 5998,
            "numberOfRandomTransactionRequests": 252,
            "numberOfSentTransactions": 60111
        },
        {
            "address": "xxxx:16100",
            "connectionType": "tcp",
            "numberOfAllTransactions": 19854,
            "numberOfInvalidTransactions": 0,
            "numberOfNewTransactions": 802,
            "numberOfRandomTransactionRequests": 3417,
            "numberOfSentTransactions": 63258
        },
        {
            "address": "xxxx:18750",
            "connectionType": "tcp",
            "numberOfAllTransactions": 60392,
            "numberOfInvalidTransactions": 0,
            "numberOfNewTransactions": 21360,
            "numberOfRandomTransactionRequests": 247,
            "numberOfSentTransactions": 91581
        },
        {
            "address": "xxxx:18750",
            "connectionType": "tcp",
            "numberOfAllTransactions": 42040,
            "numberOfInvalidTransactions": 0,
            "numberOfNewTransactions": 21571,
            "numberOfRandomTransactionRequests": 273,
            "numberOfSentTransactions": 59629
        },
        {
            "address": "xxxx:15600",
            "connectionType": "tcp",
            "numberOfAllTransactions": 36443,
            "numberOfInvalidTransactions": 0,
            "numberOfNewTransactions": 9677,
            "numberOfRandomTransactionRequests": 259,
            "numberOfSentTransactions": 51827
        },
        {
            "address": "xxxx:14700",
            "connectionType": "tcp",
            "numberOfAllTransactions": 72086,
            "numberOfInvalidTransactions": 0,
            "numberOfNewTransactions": 0,
            "numberOfRandomTransactionRequests": 250,
            "numberOfSentTransactions": 91940
        },
        {
            "address": "xxxx:15600",
            "connectionType": "tcp",
            "numberOfAllTransactions": 0,
            "numberOfInvalidTransactions": 0,
            "numberOfNewTransactions": 0,
            "numberOfRandomTransactionRequests": 0,
            "numberOfSentTransactions": 0
        },
        {
            "address": "xxxx:15600",
            "connectionType": "tcp",
            "numberOfAllTransactions": 2260,
            "numberOfInvalidTransactions": 0,
            "numberOfNewTransactions": 0,
            "numberOfRandomTransactionRequests": 255,
            "numberOfSentTransactions": 51347
        }
    ]
}
```

Refering the full IRI [log](https://drive.google.com/file/d/1LfncbnE3IesxSFVK_NqW32PLulCbATdW/view?usp=sharing) for detail.

**Comment by rajivshah3** [comment]
From the log it looks like you're using OpenJDK. Have you tried using the official Java JDK?

**Comment by pompomJuice** [comment]
Ha. Sneaky error.

Here is the reason:

ThreadPoolExecutor states
```
<In {@link ThreadPoolExecutor.DiscardOldestPolicy}, if the
 * executor is not shut down, the task at the head of the work queue
 * is dropped, and then execution is retried (which can fail again,
 * causing this to be repeated.)
```

So basically what is happening is you are running out of resources and the call causing the saturation cannot be interrupted for some reason so then the Executor turns on the oldest thread, the UDP thread which was probably created first when iri starts.

**Comment by jserv** [comment]
@yillkid, can you reproduce this issue?
