### ISSUE TITLE
Too many open files (Accept failed)

### ISSUE THREAD

**Issue by GhostTyper** [iotaledger/iri#497]
I repeatedly get an error exceeding handles since version 1.4.1.7. This error results in IRI spaming the following message with maximum speed:

```
java.net.SocketException: Zu viele offene Dateien (Accept failed)
        at java.net.PlainSocketImpl.socketAccept(Native Method) ~[na:1.8.0_151]
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409) ~[na:1.8.0_151]
        at java.net.ServerSocket.implAccept(ServerSocket.java:545) ~[na:1.8.0_151]
        at java.net.ServerSocket.accept(ServerSocket.java:513) ~[na:1.8.0_151]
        at com.iota.iri.network.replicator.ReplicatorSourcePool.run(ReplicatorSourcePool.java:50) ~[iri-1.4.1.7.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
```

_(`Zu viele offene Dateien`=`Too many open files`)_

However, since the node has quite some load, I increased the maximum open fds ages ago:

```
$ cat /proc/sys/fs/file-max
1637399
$ ulimit -n
4096
```

In front of IRI is nginx as reverse proxy. nginx itself has an amount of workers and connections configured which couldn't exceed the allowed 4096 handles of iri by far. Additionally the load of the node exceeded 500 connections at no time.

Therefore I assume that the current iri version (or the db, or whatever) doesn't cleanup every fd properly.

**Comment by nuriel77** [comment]
Looks like/related https://github.com/iotaledger/iri/issues/492#issuecomment-359867899

**Comment by GhostTyper** [comment]
This is very well possible. However, this error occurred not by "too many connections". It just seems that something in IRI is eatin' handles.

**Comment by nuriel77** [comment]
Could be. I mentioned the relation because I saw this message on nodes where `lsof -Pni:14265` revealed a lot of connections to IRI (which are basically open files). Added to that the open files used by iri... It reached the max and the error produced.

**Comment by brunoamancio** [comment]
Same in my node..

**Comment by GhostTyper** [comment]
This error didn't happen since the new IRI version. @brunoamancio or somebody else, did you have this kind of error again? If no, I would close this ticket.

**Comment by brunoamancio** [comment]
Not anymore. But it might have been caused by the DDoS attacks in the network during the token robberies. In that case it really wouldn't be reproducible until something similar happened.
