### ISSUE TITLE
NullPointerException during attachToTangle

### ISSUE THREAD

**Issue by todofixthis** [iotaledger/iri#50]
Sending `attachToTangle` command to testnet node:

```
curl -D- -X POST 'http://localhost:14265' -d '{
  "branch_transaction": "XDN9JPC9IDEDVXCDHRIZQFRGVYSATABBLHYXXWXHSCQTPDXKFTOIUNOUHQSHWE9PAACZVAKHNRJ9X9999",
  "trunk_transaction": "NGIOABAPTZTMFCTBIFROXETJDWCDFISQHLNRTALAJUT9RJACVTSJBBSWQQCXSBTHBNAH9YGAMRX999999",
  "trytes": [
    "NBTCPCFDEACCPCBDVC9DTCQAJ9RBTC9D9DCDQAEAKDCDFD9DSCFAJ9VBCDJDTCQAJ9ZBMDYBCCKB99999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999H9LAMVD99999999999999999999SDRMTHIMZ9PPP9DT9FFWWIFBYQYMLWRIQRGLUBMSPRDEJZRAHAXQUKTPKMG9RGIKTHPAN9WSQAWURJELV999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999"
  ],
  "min_weight_magnitude": 13,
  "command": "attachToTangle"
}'
```
Response:
```
HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Access-Control-Allow-Origin: *
Keep-Alive: timeout=500, max=100
Content-Type: application/json
Content-Length: 17
Date: Fri, 20 Jan 2017 01:18:25 GMT

{"duration":1005}
```

IRI output:
```
20:18:25.460 [XNIO-1 task-5] INFO  com.iota.iri.service.API - # 5 -> Requesting command 'attachToTangle'
20:18:25.461 [XNIO-1 task-5] ERROR com.iota.iri.service.API - API Exception:
java.lang.NullPointerException: null
	at com.iota.iri.utils.Converter.trits(Converter.java:77) ~[iri-1.1.2.4.jar:na]
	at com.iota.iri.model.Hash.<init>(Hash.java:38) ~[iri-1.1.2.4.jar:na]
	at com.iota.iri.service.API.process(API.java:131) [iri-1.1.2.4.jar:na]
	at com.iota.iri.service.API.processRequest(API.java:99) [iri-1.1.2.4.jar:na]
	at com.iota.iri.service.API.access$000(API.java:61) [iri-1.1.2.4.jar:na]
	at com.iota.iri.service.API$1.handleRequest(API.java:87) [iri-1.1.2.4.jar:na]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:208) [iri-1.1.2.4.jar:na]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809) [iri-1.1.2.4.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
```

Node info:

```
{
    "appName": "IRI Testnet",
    "appVersion": "1.1.2.4",
    "duration": 1,
    "jreAvailableProcessors": 8,
    "jreFreeMemory": 209096776,
    "jreMaxMemory": 3817865216,
    "jreTotalMemory": 257425408,
    "jreVersion": "1.8.0_65",
    "latestMilestone": "999999999999999999999999999999999999999999999999999999999999999999999999999999999",
    "latestMilestoneIndex": 0,
    "latestSolidSubtangleMilestone": "999999999999999999999999999999999999999999999999999999999999999999999999999999999",
    "latestSolidSubtangleMilestoneIndex": 0,
    "neighbors": 0,
    "packetsQueueSize": 0,
    "time": 1484875181582,
    "tips": 1,
    "transactionsToRequest": 0
}
```

**Comment by todofixthis** [comment]
Oops!  Nevermind; this one's a pebble cake.

Wrong attribute names (`trunk_transaction` s/b `trunkTransaction`).
