### ISSUE TITLE
ZMQ Excess Logging on Error IndexOutOfBoundsException

### ISSUE THREAD

**Issue by nuriel77** [iotaledger/iri#505]
Hi. This has been spotted on at least two nodes the past few days. One is using the 501 PR, other is 1.4.1.7 stable. Both have ZMQ enabled.

Error begins:
```sh
Jan 27 12:38:19 vmi157552 iri[3191]: 01/27 12:38:19.763 [Latest Milestone Tracker] INFO  com.iota.iri.Milestone - Latest milestone has changed from #336671 to #336672
Jan 27 12:38:23 vmi157552 iri[3191]: 01/27 12:38:23.758 [Solid Milestone Tracker] INFO  com.iota.iri.Milestone - Latest SOLID SUBTANGLE milestone has changed from #336671 to #336672
Jan 27 12:38:25 vmi157552 iri[3191]: 01/27 12:38:25.131 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 47 , toReply = 0 / totalTransactions = 9521845
Jan 27 12:38:35 vmi157552 iri[3191]: 01/27 12:38:35.134 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 49 , toReply = 2 / totalTransactions = 9521858
Jan 27 12:38:45 vmi157552 iri[3191]: 01/27 12:38:45.137 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 50 , toReply = 0 / totalTransactions = 9521869
Jan 27 12:38:55 vmi157552 iri[3191]: 01/27 12:38:55.156 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 49 , toReply = 0 / totalTransactions = 9521884
Jan 27 12:39:05 vmi157552 iri[3191]: 01/27 12:39:05.480 [pool-2-thread-4] ERROR c.i.iri.storage.ZmqPublishProvider - tx KX9WIIBRYGAGNJERKTWXTTJLNYBGVJACVWNQKWZZINK9CWD9CZUZOCGGBLVYWQISNJLEWBDENAN9A9999 QXJNKSJQROLWDCI9EZPW9KCQYKELEVJQOIFGWUCEHVGBTOOVPXJWBWXLJ9UBDPAURKLNBIUBXQIDNPTHX 0 JB9999999999999999999999999 1517053077 0 0 IKCFPWKJLEUBGDWUVSFPKTOEJGEHILYOJQPQFHGXKHBCIJBOPYRDHLVZWRIFZEGKQP9CGGCJPIAXTQLXC KDKULONSVBKWWIGHYVIISFUQYICWZSTTWA9HJJORFQ99ZSIWFUNMJZSTQGHYJGJNYCARDFTKCTFCZ9999 ZWTPKAWCQNPFOOVJWDSTBEQTTRAWDIVDMDIHOVIJFUPLOCCLTZJVFXACWEDASKXPSKNLIAZPDIFKZ9999 1517053145401
Jan 27 12:39:05 vmi157552 iri[3191]: 01/27 12:39:05.543 [pool-2-thread-4] ERROR c.i.iri.storage.ZmqPublishProvider - Error publishing to zmq.
Jan 27 12:39:05 vmi157552 iri[3191]: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
Jan 27 12:39:05 vmi157552 iri[3191]: #011at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[na:1.8.0_151]
Jan 27 12:39:05 vmi157552 iri[3191]: #011at java.util.ArrayList.get(ArrayList.java:433) ~[na:1.8.0_151]
Jan 27 12:39:05 vmi157552 iri[3191]: #011at zmq.Dist.distribute(Dist.java:157) ~[iri-x.x.x.x.jar:na]
Jan 27 12:39:05 vmi157552 iri[3191]: #011at zmq.Dist.sendToMatching(Dist.java:136) ~[iri-x.x.x.x.jar:na]
Jan 27 12:39:05 vmi157552 iri[3191]: #011at zmq.XPub.xsend(XPub.java:195) ~[iri-x.x.x.x.jar:na]
Jan 27 12:39:05 vmi157552 iri[3191]: #011at zmq.SocketBase.send(SocketBase.java:590) ~[iri-x.x.x.x.jar:na]
Jan 27 12:39:05 vmi157552 iri[3191]: #011at org.zeromq.ZMQ$Socket.send(ZMQ.java:1320) ~[iri-x.x.x.x.jar:na]
Jan 27 12:39:05 vmi157552 iri[3191]: #011at org.zeromq.ZMQ$Socket.send(ZMQ.java:1294) ~[iri-x.x.x.x.jar:na]
Jan 27 12:39:05 vmi157552 iri[3191]: #011at com.iota.iri.zmq.MessageQ.publish(MessageQ.java:33) ~[iri-x.x.x.x.jar:na]
Jan 27 12:39:05 vmi157552 iri[3191]: #011at com.iota.iri.storage.ZmqPublishProvider.update(ZmqPublishProvider.java:69) ~[iri-x.x.x.x.jar:na]
Jan 27 12:39:05 vmi157552 iri[3191]: #011at com.iota.iri.storage.Tangle.update(Tangle.java:92) [iri-x.x.x.x.jar:na]
Jan 27 12:39:05 vmi157552 iri[3191]: #011at com.iota.iri.controllers.TransactionViewModel.update(TransactionViewModel.java:127) [iri-x.x.x.x.jar:na]
```

The error logs profusely, to a degree where the log reaches 20GB+/- in a couple of hours.

A manual restart of IRI then results in milestone stuck and those repeating messages in the logs:
```sh
Jan 27 20:50:50 vmixxxxxx.contaboserver.net iri[13984]: 01/27 20:50:50.083 [Solid Milestone Tracker] INFO  com.iota.iri.Snapshot - Skipping negative value for address: PAQKQMKBGPLZAPOBXZHFKXYDKTIMASZK9CVPPCUTPTIQDELEQ9TNSTBHMYCBHVKGYIBBYBV9VOFMTKYND: -5845483
Jan 27 20:50:44 vmixxxxxx.contaboserver.net iri[13984]: 01/27 20:50:44.716 [Solid Milestone Tracker] INFO  com.iota.iri.Snapshot - Skipping negative value for address: PAQKQMKBGPLZAPOBXZHFKXYDKTIMASZK9CVPPCUTPTIQDELEQ9TNSTBHMYCBHVKGYIBBYBV9VOFMTKYND: -5845483
Jan 27 20:50:44 vmixxxxxx.contaboserver.net iri[13984]: 01/27 20:50:44.449 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 3 , toReply = 0 / totalTransactions = 8495990
Jan 27 20:50:40 vmixxxxxx.contaboserver.net iri[13984]: 01/27 20:50:40.810 [Solid Milestone Tracker] INFO  com.iota.iri.Snapshot - Skipping negative value for address: PAQKQMKBGPLZAPOBXZHFKXYDKTIMASZK9CVPPCUTPTIQDELEQ9TNSTBHMYCBHVKGYIBBYBV9VOFMTKYND: -5845483
Jan 27 20:50:34 vmixxxxxx.contaboserver.net iri[13984]: 01/27 20:50:34.631 [Solid Milestone Tracker] INFO  com.iota.iri.Snapshot - Skipping negative value for address: PAQKQMKBGPLZAPOBXZHFKXYDKTIMASZK9CVPPCUTPTIQDELEQ9TNSTBHMYCBHVKGYIBBYBV9VOFMTKYND: -5845483
Jan 27 20:50:34 vmixxxxxx.contaboserver.net iri[13984]: 01/27 20:50:34.427 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 4 , toReply = 25 / totalTransactions = 8495964
Jan 27 20:50:30 vmixxxxxx.contaboserver.net iri[13984]: 01/27 20:50:30.170 [Solid Milestone Tracker] INFO  com.iota.iri.Snapshot - Skipping negative value for address: PAQKQMKBGPLZAPOBXZHFKXYDKTIMASZK9CVPPCUTPTIQDELEQ9TNSTBHMYCBHVKGYIBBYBV9VOFMTKYND: -5845483
Jan 27 20:50:25 vmixxxxxx.contaboserver.net iri[13984]: 01/27 20:50:25.039 [Solid Milestone Tracker] INFO  com.iota.iri.Snapshot - Skipping negative value for address: PAQKQMKBGPLZAPOBXZHFKXYDKTIMASZK9CVPPCUTPTIQDELEQ9TNSTBHMYCBHVKGYIBBYBV9VOFMTKYND: -5845483
Jan 27 20:50:24 vmixxxxxx.contaboserver.net iri[13984]: 01/27 20:50:24.368 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 2 , toReply = 1 / totalTransactions = 8495927
```

**Comment by felix-apo** [comment]
Same here! But it is called java instead of iri?

```
Jan 31 09:22:25 localhost java[10539]: 01/31 09:22:24.780 [Solid Milestone Tracker] INFO  com.iota.iri.Snapshot - Skipping negative value for address: CVLGK9ESZAFCCPIQFLLLBFUDXGIQ9THZQHFOWLQMWV9GJQEMXAHXLBWTVWKQOBCWJTIPSK9JQXQIQYYKC: -8000000
Jan 31 09:22:25 localhost java[10539]: message repeated 48 times: [ 01/31 09:22:24.780 [Solid Milestone Tracker] INFO  com.iota.iri.Snapshot - Skipping negative value for address: CVLGK9ESZAFCCPIQFLLLBFUDXGIQ9THZQHFOWLQMWV9GJQEMXAHXLBWTVWKQOBCWJTIPSK9JQXQIQYYKC: -8000000]
Jan 31 09:22:25 localhost java[10539]: 01/31 09:22:24.781 [Solid Milestone Tracker] INFO  com.iota.iri.Snapshot - Skipping negative value for address: CVLGK9ESZAFCCPIQFLLLBFUDXGIQ9THZQHFOWLQMWV9GJQEMXAHXLBWTVWKQOBCWJTIPSK9JQXQIQYYKC: -8000000
Jan 31 09:22:25 localhost java[10539]: message repeated 56 times: [ 01/31 09:22:24.781 [Solid Milestone Tracker] INFO  com.iota.iri.Snapshot - Skipping negative value for address: CVLGK9ESZAFCCPIQFLLLBFUDXGIQ9THZQHFOWLQMWV9GJQEMXAHXLBWTVWKQOBCWJTIPSK9JQXQIQYYKC: -8000000]
Jan 31 09:22:25 localhost java[10539]: 01/31 09:22:24.782 [Solid Milestone Tracker] INFO  com.iota.iri.Snapshot - Skipping negative value for address: CVLGK9ESZAFCCPIQFLLLBFUDXGIQ9THZQHFOWLQMWV9GJQEMXAHXLBWTVWKQOBCWJTIPSK9JQXQIQYYKC: -8000000
Jan 31 09:22:25 localhost java[10539]: message repeated 57 times: [ 01/31 09:22:24.782 [Solid Milestone Tracker] INFO  com.iota.iri.Snapshot - Skipping negative value for address: CVLGK9ESZAFCCPIQFLLLBFUDXGIQ9THZQHFOWLQMWV9GJQEMXAHXLBWTVWKQOBCWJTIPSK9JQXQIQYYKC: -8000000]
Jan 31 09:22:25 localhost java[10539]: 01/31 09:22:24.783 [Solid Milestone Tracker] INFO  com.iota.iri.Snapshot - Skipping negative value for address: CVLGK9ESZAFCCPIQFLLLBFUDXGIQ9THZQHFOWLQMWV9GJQEMXAHXLBWTVWKQOBCWJTIPSK9JQXQIQYYKC: -8000000
```

**Comment by nuriel77** [comment]
@felix-apo this doesn't look like the zmq error I posted. The errors you posted I've seen when upgrading to IRI 1.4.2.1 without having removed the old database.

**Comment by michi6383** [comment]
Feb  3 06:25:04 vmd24512 IRI[3309]: 02/03 06:25:04.135 [pool-2-thread-3] ERROR com.iota.iri.network.Node - Neighbor DNS Refresher Thread Exception:
Feb  3 06:25:04 vmd24512 IRI[3309]: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
Feb  3 06:25:04 vmd24512 IRI[3309]: #011at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[na:1.8.0_161]
Feb  3 06:25:04 vmd24512 IRI[3309]: #011at java.util.ArrayList.set(ArrayList.java:448) ~[na:1.8.0_161]
Feb  3 06:25:04 vmd24512 IRI[3309]: #011at java.util.Collections.swap(Collections.java:497) ~[na:1.8.0_161]
Feb  3 06:26:07 vmd24512 IRI[3309]: 02/03 06:26:05.998 [pool-2-thread-3] ERROR com.iota.iri.network.Node - Neighbor DNS Refresher Thread Exception:
Feb  3 06:26:07 vmd24512 IRI[3309]: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
Feb  3 06:26:07 vmd24512 IRI[3309]: 02/03 06:26:05.999 [pool-2-thread-3] ERROR com.iota.iri.network.Node - Neighbor DNS Refresher Thread Exception:
Feb  3 06:26:07 vmd24512 IRI[3309]: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
triggered every milli second. so 1000 exceptions a second in logs
Feb  3 06:26:07 vmd24512 IRI[3309]: 02/03 06:26:06.122 [pool-2-thread-4] ERROR c.i.iri.storage.ZmqPublishProvider - tx NMNYSWUHSMDLJPEVRBRJEMUFZEAVYCHGRENQTDBQUD9KHREXSF9VYRUCLOKGOYUYUDLSGWFZVDGWZ9999 SPPRLTTIVYUONPOPQSWGCPMZWDOMQGWFUEPKUQIVUKROCHRNCR9MXNGNQSAGLKUDX9MZQWCPFJQS9DWAY 0 F99SPAMALOT9999999999999999 1517635028 0 0 LYK9JAXGHNVNTFHONPQDBAKLXZHYCEZDFGAP9CWYTZGIVJC9DKXTYJHGZEVTWNXX9CUWYCVKFXSAK9DCY PZJGXEXYFYIARFUNFWN9JLQAWYYMKLMHNONYAKZYRDJSKCMVVUOWLYAMJBQDVFQ9GACQAUMHMTXA99999 UWIMYPKKVPHJSECYRAMMKSKUCGMHHVHHS99PBTPZJZMYJWLUTNHNZCXOEVYRYZKOSBHUWDPFTQTGA9999 1517635566122
Feb  3 06:26:07 vmd24512 IRI[3309]: 02/03 06:26:06.123 [pool-2-thread-4] ERROR c.i.iri.storage.ZmqPublishProvider - Error publishing to zmq.
and zmq crashed
57671848  60G -rw-r-----  1 syslog  adm      60G Feb  3 10:54 syslog
57671697 154G -rw-r-----  1 syslog  adm     154G Feb  3 06:25 syslog.1

**Comment by fijter** [comment]
Same issue here, IRI 1.4.2.1 - ZMQ enabled. syslog fills up within hours disabling my machine. It keeps repeating this:

```Feb 12 14:25:52 home iri[13906]: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
Feb 12 14:25:52 home iri[13906]: #011at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[na:1.8.0_151]
Feb 12 14:25:52 home iri[13906]: #011at java.util.ArrayList.set(ArrayList.java:448) ~[na:1.8.0_151]
Feb 12 14:25:52 home iri[13906]: #011at java.util.Collections.swap(Collections.java:497) ~[na:1.8.0_151]
Feb 12 14:25:52 home iri[13906]: #011at zmq.Dist.write(Dist.java:173) ~[iri-1.4.2.1.jar:na]
Feb 12 14:25:52 home iri[13906]: #011at zmq.Dist.distribute(Dist.java:157) ~[iri-1.4.2.1.jar:na]
Feb 12 14:25:52 home iri[13906]: #011at zmq.Dist.sendToMatching(Dist.java:136) ~[iri-1.4.2.1.jar:na]
Feb 12 14:25:52 home iri[13906]: #011at zmq.XPub.xsend(XPub.java:195) ~[iri-1.4.2.1.jar:na]
Feb 12 14:25:52 home iri[13906]: #011at zmq.SocketBase.send(SocketBase.java:590) ~[iri-1.4.2.1.jar:na]
Feb 12 14:25:52 home iri[13906]: #011at org.zeromq.ZMQ$Socket.send(ZMQ.java:1320) ~[iri-1.4.2.1.jar:na]
Feb 12 14:25:52 home iri[13906]: #011at org.zeromq.ZMQ$Socket.send(ZMQ.java:1294) ~[iri-1.4.2.1.jar:na]
Feb 12 14:25:52 home iri[13906]: #011at com.iota.iri.zmq.MessageQ.publish(MessageQ.java:33) ~[iri-1.4.2.1.jar:na]
Feb 12 14:25:52 home iri[13906]: #011at com.iota.iri.network.Node.lambda$null$2(Node.java:152) ~[iri-1.4.2.1.jar:na]
Feb 12 14:25:52 home iri[13906]: #011at java.util.Optional.ifPresent(Optional.java:159) ~[na:1.8.0_151]
Feb 12 14:25:52 home iri[13906]: #011at com.iota.iri.network.Node.lambda$null$3(Node.java:150) ~[iri-1.4.2.1.jar:na]
Feb 12 14:25:52 home iri[13906]: #011at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[na:1.8.0_151]
Feb 12 14:25:52 home iri[13906]: #011at com.iota.iri.network.Node.lambda$spawnNeighborDNSRefresherThread$4(Node.java:148) ~[iri-1.4.2.1.jar:na]
Feb 12 14:25:52 home iri[13906]: #011at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_151]
Feb 12 14:25:52 home iri[13906]: #011at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_151]
Feb 12 14:25:52 home iri[13906]: #011at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
Feb 12 14:25:52 home iri[13906]: #011at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
Feb 12 14:25:52 home iri[13906]: #011at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
Feb 12 14:25:52 home iri[13906]: 02/12 14:25:51.713 [pool-2-thread-3] INFO  com.iota.iri.network.Node - Checking Neighbors' Ip...
Feb 12 14:25:52 home iri[13906]: 02/12 14:25:51.713 [pool-2-thread-3] INFO  com.iota.iri.network.Node - DNS Checker: Validating DNS Address 'n1.vlpo.tech' with '75.152.104.163'
Feb 12 14:25:52 home iri[13906]: 02/12 14:25:51.713 [pool-2-thread-3] ERROR com.iota.iri.network.Node - Neighbor DNS Refresher Thread Exception:
```

**Comment by euri10** [comment]
affected as well, log spams the below, I deleted the old db, downloaded new one, nonetheless it fills syslog quick enough

```
Feb 26 02:47:32 ssdnodes-86271 IRI[16015]:         at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_161]
Feb 26 02:47:32 ssdnodes-86271 IRI[16015]: 02/26 02:47:32.896 [pool-2-thread-4] ERROR c.i.iri.storage.ZmqPublishProvider - tx EKNOBWONJGAHCBOXWAQHPZ9KIMBINYQGPMXEFLNZNQ9HOCYCYBHDRIXECJOB9PLSJWT9BFK9J9ZAZ9999 999999999999999999999999999999999999999999999999999999999999999999999999999999999 0 A99999999999999999999999999 1519641945 0 0 ILLJJSWC9ASW9XDNJ9NQFCGOPOLJKBKVVKAKA9CXGWEEQZAAOXFNZUEHBUNIJPGWKKOT9WAQXW9KJIXAW UMKVD99ROZUBGHCQTVQBKGIKVRZCRAJTZZTDCPHCFMKUJBAQNWIQIYBYASXWUCOFTUOKVWUAGSDQ99999 ZAYOAXPASRVFSXYTWYLNWW9MDVFZ9TUJDSXFBDJI9VKMHKZPWWOHBUAD9FNDQQTBDUGJVPPXZOPKZ9999 1519642052895
Feb 26 02:47:32 ssdnodes-86271 IRI[16015]: 02/26 02:47:32.897 [pool-2-thread-4] ERROR c.i.iri.storage.ZmqPublishProvider - Error publishing to zmq.
Feb 26 02:47:32 ssdnodes-86271 IRI[16015]: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
Feb 26 02:47:32 ssdnodes-86271 IRI[16015]:         at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[na:1.8.0_161]
Feb 26 02:47:32 ssdnodes-86271 IRI[16015]:         at java.util.ArrayList.get(ArrayList.java:433) ~[na:1.8.0_161]
Feb 26 02:47:32 ssdnodes-86271 IRI[16015]:         at zmq.socket.pubsub.Dist.distribute(Dist.java:161) ~[iri-1.4.2.2.jar:na]
Feb 26 02:47:32 ssdnodes-86271 IRI[16015]:         at zmq.socket.pubsub.Dist.sendToMatching(Dist.java:137) ~[iri-1.4.2.2.jar:na]
Feb 26 02:47:32 ssdnodes-86271 IRI[16015]:         at zmq.socket.pubsub.XPub.xsend(XPub.java:177) ~[iri-1.4.2.2.jar:na]
Feb 26 02:47:32 ssdnodes-86271 IRI[16015]:         at zmq.SocketBase.send(SocketBase.java:712) ~[iri-1.4.2.2.jar:na]
Feb 26 02:47:32 ssdnodes-86271 IRI[16015]:         at org.zeromq.ZMQ$Socket.send(ZMQ.java:2588) ~[iri-1.4.2.2.jar:na]
Feb 26 02:47:32 ssdnodes-86271 IRI[16015]:         at org.zeromq.ZMQ$Socket.send(ZMQ.java:2562) ~[iri-1.4.2.2.jar:na]
Feb 26 02:47:32 ssdnodes-86271 IRI[16015]:         at com.iota.iri.zmq.MessageQ.publish(MessageQ.java:33) ~[iri-1.4.2.2.jar:na]
Feb 26 02:47:32 ssdnodes-86271 IRI[16015]:         at com.iota.iri.storage.ZmqPublishProvider.update(ZmqPublishProvider.java:69) ~[iri-1.4.2.2.jar:na]
Feb 26 02:47:32 ssdnodes-86271 IRI[16015]:         at com.iota.iri.storage.Tangle.update(Tangle.java:92) [iri-1.4.2.2.jar:na]
Feb 26 02:47:32 ssdnodes-86271 IRI[16015]:         at com.iota.iri.controllers.TransactionViewModel.update(TransactionViewModel.java:127) [iri-1.4.2.2.jar:na]
Feb 26 02:47:32 ssdnodes-86271 IRI[16015]:         at com.iota.iri.network.Node.processReceivedData(Node.java:394) [iri-1.4.2.2.jar:na]
Feb 26 02:47:32 ssdnodes-86271 IRI[16015]:         at com.iota.iri.network.Node.processReceivedDataFromQueue(Node.java:365) [iri-1.4.2.2.jar:na]
Feb 26 02:47:32 ssdnodes-86271 IRI[16015]:         at com.iota.iri.network.Node.lambda$spawnProcessReceivedThread$8(Node.java:564) [iri-1.4.2.2.jar:na]
Feb 26 02:47:32 ssdnodes-86271 IRI[16015]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_161]
Feb 26 02:47:32 ssdnodes-86271 IRI[16015]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_161]
Feb 26 02:47:32 ssdnodes-86271 IRI[16015]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_161]
```

**Comment by nuriel77** [comment]
This seems to be happening more frequently since 1.4.2.2
```Feb 28 18:32:32 v22018015681060432 iri[870]: 02/28 18:32:31.717 [pool-2-thread-3] ERROR com.iota.iri.network.Node - Neighbor DNS Refresher Thread Exception:
Feb 28 18:32:32 v22018015681060432 iri[870]: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
Feb 28 18:32:32 v22018015681060432 iri[870]: #011at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[na:1.8.0_162]
Feb 28 18:32:32 v22018015681060432 iri[870]: #011at java.util.ArrayList.set(ArrayList.java:448) ~[na:1.8.0_162]
Feb 28 18:32:32 v22018015681060432 iri[870]: #011at java.util.Collections.swap(Collections.java:497) ~[na:1.8.0_162]
Feb 28 18:32:32 v22018015681060432 iri[870]: #011at zmq.socket.pubsub.Dist.write(Dist.java:177) ~[iri-1.4.2.2.jar:na]
Feb 28 18:32:32 v22018015681060432 iri[870]: #011at zmq.socket.pubsub.Dist.distribute(Dist.java:161) ~[iri-1.4.2.2.jar:na]
Feb 28 18:32:32 v22018015681060432 iri[870]: #011at zmq.socket.pubsub.Dist.sendToMatching(Dist.java:137) ~[iri-1.4.2.2.jar:na]
Feb 28 18:32:32 v22018015681060432 iri[870]: #011at zmq.socket.pubsub.XPub.xsend(XPub.java:177) ~[iri-1.4.2.2.jar:na]
Feb 28 18:32:32 v22018015681060432 iri[870]: #011at zmq.SocketBase.send(SocketBase.java:712) ~[iri-1.4.2.2.jar:na]
Feb 28 18:32:32 v22018015681060432 iri[870]: #011at org.zeromq.ZMQ$Socket.send(ZMQ.java:2588) ~[iri-1.4.2.2.jar:na]
Feb 28 18:32:32 v22018015681060432 iri[870]: #011at org.zeromq.ZMQ$Socket.send(ZMQ.java:2562) ~[iri-1.4.2.2.jar:na]
Feb 28 18:32:32 v22018015681060432 iri[870]: #011at com.iota.iri.zmq.MessageQ.publish(MessageQ.java:33) ~[iri-1.4.2.2.jar:na]
Feb 28 18:32:32 v22018015681060432 iri[870]: #011at com.iota.iri.network.Node.lambda$null$2(Node.java:152) ~[iri-1.4.2.2.jar:na]
Feb 28 18:32:32 v22018015681060432 iri[870]: #011at java.util.Optional.ifPresent(Optional.java:159) ~[na:1.8.0_162]
Feb 28 18:32:32 v22018015681060432 iri[870]: #011at com.iota.iri.network.Node.lambda$null$3(Node.java:150) ~[iri-1.4.2.2.jar:na]
Feb 28 18:32:32 v22018015681060432 iri[870]: #011at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[na:1.8.0_162]
Feb 28 18:32:32 v22018015681060432 iri[870]: #011at com.iota.iri.network.Node.lambda$spawnNeighborDNSRefresherThread$4(Node.java:148) ~[iri-1.4.2.2.jar:na]
Feb 28 18:32:32 v22018015681060432 iri[870]: #011at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_162]
Feb 28 18:32:32 v22018015681060432 iri[870]: #011at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_162]
Feb 28 18:32:32 v22018015681060432 iri[870]: #011at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_162]
Feb 28 18:32:32 v22018015681060432 iri[870]: #011at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_162]
Feb 28 18:32:32 v22018015681060432 iri[870]: #011at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_162]
```
Somebody else's node

**Comment by nuriel77** [comment]
@alon-e @GalRogozinski there is an increase in reports about this since 1.4.2.2. Could also be related to higher TPS. Is it possible to at least implement some fix to avoid the excess logging until the root cause is found?

**Comment by th0br0** [comment]
At cause appears to be a data race in zeromq, just going off reading their code.

Could you build & try whether the issue persists with this branch?
https://github.com/th0br0/iri/tree/fix-zmq-ioob

**Comment by nuriel77** [comment]
Thanks @th0br0 . Will give it a go.
I guess this will be hard to assess, as those crashes are sporadic. I will also ask node operators who experience crashes to give it a try.

**Comment by henningvs** [comment]
I'm experiencing the same problem:
```
iota_iri              | 03/11 00:30:19.032 [pool-2-thread-4] ERROR c.i.iri.storage.ZmqPublishProvider - tx RESJOKBHKCNCXLCCYNBCMSCUELLERJYYPTUZMVJIDEAIXMECYIAANQZDRGZVLKKKFAPOGEYTYIELA9999 WEOKN9ISQKZOJPVUMQIMLEKNZIDKTRFVJPHKOPNKIWVTVNVMAMRQSMHE9UADWNYUE9ZLUYBK9VNSQJN9D 0 999999999999999999999999999 1519492024 2 3 9YBTALIZHQCVZYPJLXHIFPORAXBIOCKAVULQKEPUJ9AEQDLFXODS9W9CIFNWPZHW9QGXJG9JOUTIRFGCC TBLHDREIGHUMVO9MGWMDXGFXHCUGORYBAONFCRGBAHPISXFVBEADONGJKWNFJSEOEEGHCWROIUEYA9999 TCE9WXIPUNOMYDYPGELXPHEMNICFCBDITSOERTSAUOOLMOHAEINRKQEZCQXDLXGC9DSLPOXUPBVCA9999 1520728219032
iota_iri              | 03/11 00:30:19.033 [pool-2-thread-4] ERROR c.i.iri.storage.ZmqPublishProvider - Error publishing to zmq.
iota_iri              | java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
iota_iri              |         at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[na:1.8.0_151]
iota_iri              |         at java.util.ArrayList.get(ArrayList.java:433) ~[na:1.8.0_151]
iota_iri              |         at zmq.socket.pubsub.Dist.distribute(Dist.java:161) ~[iri.jar:na]
iota_iri              |         at zmq.socket.pubsub.Dist.sendToMatching(Dist.java:137) ~[iri.jar:na]
iota_iri              |         at zmq.socket.pubsub.XPub.xsend(XPub.java:177) ~[iri.jar:na]
iota_iri              |         at zmq.SocketBase.send(SocketBase.java:712) ~[iri.jar:na]
iota_iri              |         at org.zeromq.ZMQ$Socket.send(ZMQ.java:2588) ~[iri.jar:na]
iota_iri              |         at org.zeromq.ZMQ$Socket.send(ZMQ.java:2562) ~[iri.jar:na]
iota_iri              |         at com.iota.iri.zmq.MessageQ.publish(MessageQ.java:33) ~[iri.jar:na]
iota_iri              |         at com.iota.iri.storage.ZmqPublishProvider.update(ZmqPublishProvider.java:69) ~[iri.jar:na]
iota_iri              |         at com.iota.iri.storage.Tangle.update(Tangle.java:92) [iri.jar:na]
iota_iri              |         at com.iota.iri.controllers.TransactionViewModel.update(TransactionViewModel.java:127) [iri.jar:na]
iota_iri              |         at com.iota.iri.network.Node.processReceivedData(Node.java:394) [iri.jar:na]
iota_iri              |         at com.iota.iri.network.Node.processReceivedDataFromQueue(Node.java:365) [iri.jar:na]
iota_iri              |         at com.iota.iri.network.Node.lambda$spawnProcessReceivedThread$8(Node.java:564) [iri.jar:na]
iota_iri              |         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_151]
iota_iri              |         at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_151]
iota_iri              |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
iota_iri              |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
iota_iri              |         at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
```

Can I help you find the problem?

**Comment by alon-e** [comment]
#569 was merged into `dev`, please reopen is issue still occurs.
