### ISSUE TITLE
Error: Request Error: attempt to unlock read lock, not locked by current thread     at Object.requestError

### ISSUE THREAD

**Issue by AaronVasquez** [iotaledger/iri#534]
Calling `sendTrytes` or `sendTransfers` from the `iota.lib.js` client

```
Error: Request Error: attempt to unlock read lock, not locked by current thread
    at Object.requestError (/home/oyster/hooknode/node_modules/iota.lib.js/lib/errors/requestErrors.js:11:12)
    at makeRequest.prepareResult (/home/oyster/hooknode/node_modules/iota.lib.js/lib/utils/makeRequest.js:293:24)
    at exports.XMLHttpRequest.request.onreadystatechange (/home/oyster/hooknode/node_modules/iota.lib.js/lib/utils/makeRequest.js:71:25)
    at exports.XMLHttpRequest.dispatchEvent (/home/oyster/hooknode/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/home/oyster/hooknode/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/home/oyster/hooknode/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
```

**Comment by romansemko** [comment]
Also seeing this. 99% when doing "getTransactionsToApprove" using field.carriota.com load balancer:

'attempt to unlock read lock, not locked by current thread'.
