### ISSUE TITLE
IRI on Windows not working - Could not initialize class org.rocksdb.RocksDB

### ISSUE THREAD

**Issue by pkhutal** [iotaledger/iri#539]
Hello Team,

Thank you for your great work!

I am following the following instructions to setup IOTA Wallet: 
**git clone https://github.com/iotaledger/iri
cd iri
mvn clean compile && mvn package**

But this is throwing error : 

02/17 12:16:09.578 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers...
02/17 12:16:09.581 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers...
02/17 12:16:09.584 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers...
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.002 sec <<< FAILURE!
get(com.iota.iri.storage.TangleTest)  Time elapsed: 0.001 sec  <<< ERROR!
**java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB**
        at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.<init>(RocksDBPersistenceProvider.java:28)
        at com.iota.iri.storage.TangleTest.setUp(TangleTest.java:37)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Could you please tell me what i am missing?

Thank you.

**Comment by arukavytsia** [comment]
Upvote. I faced the same issue during `mvn package` phase, `mvn clean compile` passed fine.

**Comment by pkhutal** [comment]
Yeah, its problem with windows. But it is working fine on Mac.

**Comment by arukavytsia** [comment]
Also on Linux machine, it works as it should.

**Comment by schultz-it-solutions** [comment]
Upvote as well!

I think i have the same issue on a Windows Server 2012 R2 system.
Any thoughts whether (and when) this could be solved for windows?

**Comment by EnisOlgac** [comment]
**Did team give up windows?** 
Last working version is "1.4.1.1". Release 1.4.1.2 has a footnote:

> ". Upgrade to RocksDB 5.7.3"

I think upgrade was never been tested for Windows.

**Comment by JurajNL** [comment]
I've got the same problem. Can't wait for a working Windows version for IRI.

**Comment by alon-e** [comment]
consolidating with #350 - possible workaround: https://github.com/iotaledger/wallet/issues/773#issuecomment-352172896

**Comment by thenanox** [comment]
I wrote this comment on other issue, and wanted to contribute it here maybe it helps:

I've been checking around on rocksdb and this bug is something related to the physical CPU you have in your computer. If you have >= Haswell intel processors (4xxx) propably works for you. In case you are using previous CPU, then it won't work with 5.7.3 rocksdbjni.

This happens because of the way rocksdb build for windows the package rocksdbjni. In some point after 5.3.6 they started to include AVX2 flag on build, that is an extension of cpu instructions for Haswell => CPUs (more in here also for AMD users https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#Advanced_Vector_Extensions_2)

The issue in rocksdb is here:
facebook/rocksdb#3307

Solutions:

One solution for IRI is to use 5.3.6 dependency on pom.xml for rocksdbjni, but i dont know if IRI uses any funcionality from 5.7.3. This solution will be backwards compatibility for old cpu users.

The other solution is to create an iota build from sources using this instructions https://github.com/facebook/rocksdb/wiki/Building-on-Windows and upload to mvnrepository so everybody can use it. (ethereum have this https://mvnrepository.com/artifact/org.ethereum/rocksdbjni)
