### ISSUE TITLE
IOTA fails to start when using ProtectSystem=full in systemd

### ISSUE THREAD

**Issue by TheFiZi** [iotaledger/iri#548]
systemd file: /lib/systemd/system/iota.service

```
[Unit]
Description=IOTA (IRI) full node
After=network.target

[Service]
WorkingDirectory=/home/iota
User=iota
Group=iota
PrivateDevices=yes
ProtectSystem=full
Type=simple
ExecReload=/bin/kill -HUP
KillMode=mixed
KillSignal=SIGTERM
TimeoutStopSec=60
ExecStart=/bin/java -Xmx1401m -Djava.net.preferIPv4Stack=true -jar /home/iota/node/iri-1.4.2.1.jar -c /home/iota/node/iota.ini
SyslogIdentifier=IRI
Restart=on-failure
RestartSec=30

[Install]
WantedBy=multi-user.target
Alias=iota.service

```

When I try to start iota I receive the following:

```
Redirecting to /bin/systemctl status iota.service
● iota.service - IOTA (IRI) full node
   Loaded: loaded (/usr/lib/systemd/system/iota.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2018-02-19 19:26:08 PST; 11s ago
 Main PID: 17258 (java)
   CGroup: /system.slice/iota.service
           └─17258 /bin/java -Xmx1401m -Djava.net.preferIPv4Stack=true -jar /home/iota/node/iri-1.4.2.1.jar -c /home/iota/node/iota.ini

Feb 19 19:26:19 HOOKNODE-TEST.nom.fizi.ca IRI[17258]: 02/19 19:26:19.954 [main] ERROR com.iota.iri.IRI - Exception during IOTA node initialisation:
Feb 19 19:26:19 HOOKNODE-TEST.nom.fizi.ca IRI[17258]: org.rocksdb.RocksDBException: while open a file for lock: /home/iota/node/mainnetdb/LOCK: Read-only file system
Feb 19 19:26:19 HOOKNODE-TEST.nom.fizi.ca IRI[17258]: at org.rocksdb.RocksDB.open(Native Method) ~[iri-1.4.2.1.jar:na]
Feb 19 19:26:19 HOOKNODE-TEST.nom.fizi.ca IRI[17258]: at org.rocksdb.RocksDB.open(RocksDB.java:286) ~[iri-1.4.2.1.jar:na]
Feb 19 19:26:19 HOOKNODE-TEST.nom.fizi.ca IRI[17258]: at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.initDB(RocksDBPersistenceProvider.java:510) ~[iri-1.4.2.1.jar:na]
Feb 19 19:26:19 HOOKNODE-TEST.nom.fizi.ca IRI[17258]: at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.init(RocksDBPersistenceProvider.java:75) ~[iri-1.4.2.1.jar:na]
Feb 19 19:26:19 HOOKNODE-TEST.nom.fizi.ca IRI[17258]: at com.iota.iri.storage.Tangle.init(Tangle.java:26) ~[iri-1.4.2.1.jar:na]
Feb 19 19:26:19 HOOKNODE-TEST.nom.fizi.ca IRI[17258]: at com.iota.iri.Iota.init(Iota.java:93) ~[iri-1.4.2.1.jar:na]
Feb 19 19:26:19 HOOKNODE-TEST.nom.fizi.ca IRI[17258]: at com.iota.iri.IRI.main(IRI.java:73) ~[iri-1.4.2.1.jar:na]
Feb 19 19:26:19 HOOKNODE-TEST.nom.fizi.ca IRI[17258]: 02/19 19:26:19.954 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...
```

The home dir (/home/iota) is fully read/write to the IOTA user.

I disabled ProtectSystem and was able to start IOTA so I checked what files it was accessing (excluding it's HOMEDIR):

```
COMMAND   PID USER   FD      TYPE             DEVICE  SIZE/OFF     NODE NAME
java    16425 iota  rtd       DIR              253,0       244       64 /
java    16425 iota  txt       REG              253,0      7304 34083822 /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/bin/java
java    16425 iota  mem       REG              253,0     68192    17051 /usr/lib64/libbz2.so.1.0.6
java    16425 iota  mem       REG              253,0    157424    17021 /usr/lib64/liblzma.so.5.2.2
java    16425 iota  mem       REG              253,0     99944    17086 /usr/lib64/libelf-0.168.so
java    16425 iota  mem       REG              253,0     19888    17132 /usr/lib64/libattr.so.1.1.0
java    16425 iota  mem       REG              253,0    297328    49466 /usr/lib64/libdw-0.168.so
java    16425 iota  mem       REG              253,0     20032    17136 /usr/lib64/libcap.so.2.22
java    16425 iota  mem       REG              253,0    111080     8103 /usr/lib64/libresolv-2.17.so
java    16425 iota  mem       REG              253,0     27776     8095 /usr/lib64/libnss_dns-2.17.so
java    16425 iota  mem       REG              253,0     40496 67663220 /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/amd64/libmanagement.so
java    16425 iota  mem       REG              253,0 106070960     8067 /usr/lib/locale/locale-archive
java    16425 iota  mem       REG              253,0   6079223 34284090 /tmp/librocksdbjni4464289956751822260.so
java    16425 iota  mem       REG              253,0     77928 67663223 /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/amd64/libnio.so
java    16425 iota  mem       REG              253,0     99328 67663222 /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/amd64/libnet.so
java    16425 iota  mem       REG              253,0     66280    13565 /usr/lib64/libnss_myhostname.so.2
java    16425 iota  mem       REG              253,0  73232502 67663283 /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/rt.jar
java    16425 iota  mem       REG              253,0     36560 67663230 /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/amd64/libzip.so
java    16425 iota  mem       REG              253,0     62184   230849 /usr/lib64/libnss_files-2.17.so
java    16425 iota  mem       REG              253,0    198240 67663212 /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/amd64/libjava.so
java    16425 iota  mem       REG              253,0     61272 67663229 /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/amd64/libverify.so
java    16425 iota  mem       REG              253,0     44448     8105 /usr/lib64/librt-2.17.so
java    16425 iota  mem       REG              253,0     88720   754631 /usr/lib64/libgcc_s-4.8.5-20150702.so.1
java    16425 iota  mem       REG              253,0   1139680    16993 /usr/lib64/libm-2.17.so
java    16425 iota  mem       REG              253,0    995840   230862 /usr/lib64/libstdc++.so.6.0.19
java    16425 iota  mem       REG              253,0  14754704 34384416 /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/amd64/server/libjvm.so
java    16425 iota  mem       REG              253,0   2127336     8078 /usr/lib64/libc-2.17.so
java    16425 iota  mem       REG              253,0     19776    16991 /usr/lib64/libdl-2.17.so
java    16425 iota  mem       REG              253,0     62144    50484 /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/amd64/jli/libjli.so
java    16425 iota  mem       REG              253,0     90664    17015 /usr/lib64/libz.so.1.2.7
java    16425 iota  mem       REG              253,0    144792     8101 /usr/lib64/libpthread-2.17.so
java    16425 iota  mem       REG              253,0    164112     8066 /usr/lib64/ld-2.17.so
java    16425 iota  mem       REG              253,0   3203275 67663265 /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/charsets.jar
java    16425 iota  mem       REG              253,0   2033499    80632 /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/ext/nashorn.jar
java    16425 iota  mem       REG              253,0     32768 16596964 /tmp/hsperfdata_iota/16425
java    16425 iota  mem       REG              253,0    762233 67663274 /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/jsse.jar
java    16425 iota    0r      CHR                1,3       0t0     1031 /dev/null
java    16425 iota    1u     unix 0xffff8800129c3c00       0t0    55160 socket
java    16425 iota    2u     unix 0xffff8800129c3c00       0t0    55160 socket
java    16425 iota    3r      REG              253,0  73232502 67663283 /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/rt.jar
java    16425 iota    5r      REG              253,0    762233 67663274 /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/jsse.jar
java    16425 iota    6r      CHR                1,8       0t0    55171 /dev/random
java    16425 iota    7r      CHR                1,9       0t0    55172 /dev/urandom
java    16425 iota    8r      CHR                1,8       0t0    55171 /dev/random
java    16425 iota    9r      CHR                1,8       0t0    55171 /dev/random
java    16425 iota   10r      CHR                1,9       0t0    55172 /dev/urandom
java    16425 iota   11r      CHR                1,9       0t0    55172 /dev/urandom
java    16425 iota   12r      REG              253,0   2033499    80632 /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/ext/nashorn.jar
java    16425 iota   14u     unix 0xffff8800129c0000       0t0    55191 socket
java    16425 iota   18u     unix 0xffff88001d843400       0t0    53806 socket
java    16425 iota   20u     IPv4              53808       0t0      TCP *:15600 (LISTEN)
java    16425 iota   21r      REG              253,0   3203275 67663265 /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/charsets.jar
java    16425 iota   24u     IPv4              53805       0t0      UDP *:14600
java    16425 iota   39r     FIFO                0,8       0t0    53811 pipe
java    16425 iota   40w     FIFO                0,8       0t0    53811 pipe
java    16425 iota   41u  a_inode                0,9         0     7014 [eventpoll]
java    16425 iota   42r     FIFO                0,8       0t0    53812 pipe
java    16425 iota   43w     FIFO                0,8       0t0    53812 pipe
java    16425 iota   44u  a_inode                0,9         0     7014 [eventpoll]
java    16425 iota   45r     FIFO                0,8       0t0    53813 pipe
java    16425 iota   46w     FIFO                0,8       0t0    53813 pipe
java    16425 iota   47u  a_inode                0,9         0     7014 [eventpoll]
java    16425 iota   80u     IPv4              53814       0t0      TCP *:14265 (LISTEN)
java    16425 iota   87r  a_inode                0,9         0     7014 inotify
java    16425 iota   88u     unix 0xffff88001d841400       0t0    53815 socket
java    16425 iota   89u     unix 0xffff88001d847000       0t0    53816 socket
```

Based on this list I expect the problem is either `/usr/` or `/tmp/`

I tried `PrivateTmp=true` and that did not resolve the issue.

That leads me to believe that IOTA or RocksDB thinks it needs write permissions to `/usr/lib/jvm/` or `/usr/lib64/`.

Is this a bug? or expected?

**Comment by TheFiZi** [comment]
Sorry forgot to mention, it’s on CentOS 7.

**Comment by nuriel77** [comment]
@TheFiZi this has nothing to do with IRI.

On CentOS/Redhat setting `ProtectSystem` to any value somehow causes home directory to also be mounted as ready-only (as opposed to what is documented for systemd). You can test that with other services that require write permissions. 

In any case, whether this a bug in systemd or unexpected behavior on RedHat/CentOS, I think that /home should be left for real users and not for services.

In the [iri-playbook](https://github.com/nuriel77/iri-playbook/blob/master/roles/iri/templates/iri.service.j2), iri (and all other services) are never installed in home folder and can run successfully with `ProtectSystem=full`

**Comment by TheFiZi** [comment]
@nuriel77 Good to know. Thank you for the explanation.
