### ISSUE TITLE
NullPointerException: source may not be initialized before checking by Node:addressMatch

### ISSUE THREAD

**Issue by alon-e** [iotaledger/iri#657]
https://github.com/iotaledger/iri/blob/16e5a34f5df16d7df2d2af30203bf61f88fc893c/src/main/java/com/iota/iri/network/TCPNeighbor.java#L115

```java.lang.NullPointerException: null
	at com.iota.iri.network.TCPNeighbor.matches(TCPNeighbor.java:115) ~[classes/:na]
	at com.iota.iri.network.Node.preProcessReceivedData(Node.java:235) ~[classes/:na]
	at com.iota.iri.network.UDPReceiver.lambda$null$0(UDPReceiver.java:84) [classes/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_162]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_162]```

**Comment by gjeee** [comment]
same issue i guess as https://github.com/iotaledger/iri/issues/574 as reported by @footloosejava

**Comment by alon-e** [comment]
Thanks @gjeee!
Totally missed that :)
