### ISSUE TITLE
transactionsToRequest filling up

### ISSUE THREAD

**Issue by gjeee** [iotaledger/iri#779]
### Bug description
As soon as tps picks up, I see the number of transactions to request grow considerably (normally it hovered around 1-2 now it's like almost 5000). So somehow IRI is unable to retrieve the asked transactions. My feeling is that it is related to #761 since the non-solid tips-queue is filling up as well. So these tx are no candidates for incoming random tip requests. As a consequence tx are not propagating properly (i think).

![image](https://user-images.githubusercontent.com/13155183/40839312-48d3c252-65a2-11e8-9050-80795746ec8c.png)

![image](https://user-images.githubusercontent.com/13155183/40839332-59c9b4f4-65a2-11e8-8057-441366021589.png)

Other nodes have the same behaviour. Pls see the load column in this [node overview](http://iota-nodes.net/).

### Hardware Spec
IRI v1.4.2.4 with 10G RAM / 4 cores / 300GB SSD running on Ubuntu 16.04.3 LTS

### Steps To Reproduce
1. Just run a node :-)

### Expected behaviour
transactionsToRequest should stay low (irrespective of tps)

### Actual behavior
transactionsToRequest grows too big (but stays within capacity of 5000 of course)

### Am I planning to do it myself with a PR?
Yes/No.

**Comment by rapmue** [comment]
And here are some graphics. 

![image](https://user-images.githubusercontent.com/3046949/40842205-641d0518-65ad-11e8-89be-81aa0f9fba74.png)
![image](https://user-images.githubusercontent.com/3046949/40842213-6bc61df4-65ad-11e8-8fae-836b06b60aed.png)
![image](https://user-images.githubusercontent.com/3046949/40842218-76095ce0-65ad-11e8-9d16-0f7bb17ad2b9.png)
![image](https://user-images.githubusercontent.com/3046949/40842301-b9101b0a-65ad-11e8-9eac-33f4cd1fe1b5.png)

and what I noticed is that no matter what, the max tips never raise over 10K

![image](https://user-images.githubusercontent.com/3046949/40842288-adbf9226-65ad-11e8-995f-cb7c8f0d7764.png)

**Comment by gjeee** [comment]
> and what I noticed is that no matter what, the max tips never raise over 10K

that is logical, since tips = solid tips + non-solid tips, both are implemented by means of a queue with a max capacity of 5000

**Comment by rapmue** [comment]
Thanks for the compliment. Ok, I hope I understand the topic of this whole tips. Solid tips are tips which are confirmed and non solid tips are the ones which aren't? But what happens when this queue get saturated?

**Comment by gjeee** [comment]
nope solid tips are tips with no gaps in its branch....confirmation status does not have anything to do with this.

when the queue gets saturated, the oldest ones are dropped from the queue...they are still in db of course. 5000 is a bit arbitrary indeed.

**Comment by GalRogozinski** [comment]
Did you consult discord or tried to restart and resync the database with a downloaded db before opening this bug?

**Comment by gjeee** [comment]
Ok i can try to start completely clean. But as you can see [here](http://iota-nodes.net/) a lot of nodes showing same behaviour. Just sort column load (=transactionsToRequest) descending. Restarting/resyncing is not exactly a proper solution imo.

**Comment by GalRogozinski** [comment]
>Restarting/resyncing is not exactly a proper solution imo.

I agree, but use it as an interim solution for now.

**Comment by rajivshah3** [comment]
When I shut down IRI after `toRequest` increases a lot, I seem to get this error:

```

^C06/07 01:28:46.302 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...
06/07 01:28:47.135 [pool-3-thread-1] INFO  com.iota.iri.network.Node - Shutting down Broadcaster Thread
06/07 01:28:47.136 [pool-3-thread-4] INFO  com.iota.iri.network.Node - Shutting down Process Received Data Thread
06/07 01:28:47.136 [pool-3-thread-5] INFO  com.iota.iri.network.Node - Shutting down Reply To Request Thread
06/07 01:28:47.243 [pool-3-thread-3] INFO  com.iota.iri.network.Node - Shutting down Neighbor DNS Refresher Thread
06/07 01:28:51.867 [pool-3-thread-2] INFO  com.iota.iri.network.Node - Shutting down Requester Thread
06/07 01:28:52.194 [UDP receiving thread] INFO  com.iota.iri.network.UDPReceiver - Shutting down spawning Receiver Thread
Exception in thread "Thread-1" java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@2e770f41 rejected from java.util.concurrent.Thr
eadPoolExecutor@72762afb[Shutting down, pool size = 9, active threads = 9, queued tasks = 0, completed tasks = 8502]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
        at com.iota.iri.network.replicator.ReplicatorSinkPool.createSink(ReplicatorSinkPool.java:74)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at com.iota.iri.network.replicator.ReplicatorSinkPool.run(ReplicatorSinkPool.java:68)
        at java.lang.Thread.run(Thread.java:748)
06/07 01:29:04.698 [Shutdown Hook] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers...
```
I'm not sure what it means or whether it helps

**Comment by gjeee** [comment]
well after some thought, I think it was some kind of attack where a lot of txs were spammed with bogus trunk and/or branch (which are subsequently added to transactionsToRequest set). can this be a possible scenario?

**Comment by gjeee** [comment]
i don't see the request queue filling up that drastic anymore since v1.5.0. 
so i will close this issue for now.
