### ISSUE TITLE
IRI failed to launch

### ISSUE THREAD

**Issue by Shaithias** [iotaledger/iri#859]
### Bug description
IRI fails to launch. with following output:
C:\Users\xyz\Desktop\Iota IRI>java -jar iri-1.5.1.jar -c iri.ini
```
Logging - property 'logging-level' set to: [INFO]
07/10 16:55:16.183 [main] WARN  com.iota.iri.IRI$IRILauncher - No neighbor has been specified. Server starting nodeless.
07/10 16:55:16.188 [main] INFO  com.iota.iri.IRI$IRILauncher - Welcome to IRI Testnet 1.5.1
07/10 16:55:17.237 [main] INFO  com.iota.iri.IRI$IRILauncher - You have set the debug flag. To enable debug output, you need to uncomment the DEBUG appender in the source tree at iri/src/main/resource
s/logback.xml and re-package iri.jar
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\xyz\AppData\Local\Temp\librocksdbjni7649461062080759978.dll: ??↑☻
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.load0(Unknown Source)
        at java.lang.System.load(Unknown Source)
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
        at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
        at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
        at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
        at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.<init>(RocksDBPersistenceProvider.java:28)
        at com.iota.iri.Iota.initializeTangle(Iota.java:186)
        at com.iota.iri.Iota.init(Iota.java:108)
        at com.iota.iri.IRI$IRILauncher.main(IRI.java:109)
        at com.iota.iri.IRI.main(IRI.java:32)
07/10 16:55:17.524 [Shutdown Hook] INFO  com.iota.iri.IRI$IRILauncher - Shutting down IOTA node, please hold tight...
07/10 16:55:23.530 [Shutdown Hook] ERROR com.iota.iri.IRI$IRILauncher - Exception occurred shutting down IOTA node:
java.lang.NullPointerException: null
        at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:73) ~[iri-1.5.1.jar:na]
        at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:30) ~[iri-1.5.1.jar:na]
        at com.iota.iri.Iota.shutdown(Iota.java:160) ~[iri-1.5.1.jar:na]
        at com.iota.iri.IRI$IRILauncher.lambda$shutdownHook$0(IRI.java:357) ~[iri-1.5.1.jar:na]
        at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_171]
```
### Hardware Spec
Windows 7

### Steps To Reproduce
1. Launch IRI

### Expected behaviour
Iota should launch

### Actual behavior
Iota failed to launch

**Comment by rajivshah3** [comment]
Did you build IRI from source or use the .jar from the GitHub releases page?

**Comment by Shaithias** [comment]
I used the jar I downloaded and placed it on desktop and ran it.

On Jul 11, 2018 1:02 PM, Rajiv Shah <notifications@github.com> wrote:

Did you build IRI from source or use the .jar from the GitHub releases page?

**Comment by rajivshah3** [comment]
Maybe this will help: https://github.com/facebook/rocksdb/issues/1302? Seems like a native dependency might be missing

**Comment by jakubcech** [comment]
This looks like the same issue as #350. Can you try the resolution here?:
https://github.com/iotaledger/iri/issues/350#issuecomment-348781909

**Comment by jakubcech** [comment]
Closing as duplicate
