### ISSUE TITLE
package fails

### ISSUE THREAD

**Issue by ignasg** [iotaledger/iri#893]
### Bug description
mvn package fails

### Hardware Spec
Windows 7, 8GB ram

### Steps To Reproduce
1. clone repo
2. mvn clean compile
3. mvn package

### Expected behaviour
iri should build, test pass

### Actual behavior
iri fails to build, test fail

### Errors
```
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------------< com.iota:iri >----------------------------
[INFO] Building IRI 1.5.2
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-checkstyle-plugin:3.0.0:check (validate) @ iri ---
[INFO] Starting audit...
Audit done.
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.9:prepare-agent (default) @ iri ---
[INFO] argLine set to -javaagent:C:\\Users\\ai.ai-PC\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.7.9\\org.jacoco.agent-0.7.9-runtime.jar=destfile=C:\\prj\\iri\\target\\jacoco.exec
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ iri ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 7 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ iri ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ iri ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\prj\iri\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ iri ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.21.0:test (default-test) @ iri ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.iota.iri.BundleValidatorTest
07/29 03:05:52.584 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.455 s <<< FAILURE! - in com.iota.iri.BundleValidatorTest
[ERROR] com.iota.iri.BundleValidatorTest  Time elapsed: 1.449 s  <<< ERROR!
java.lang.UnsatisfiedLinkError: C:\Users\ai.ai-PC\AppData\Local\Temp\librocksdbjni8070860278500232389.dll: àý8
	at com.iota.iri.BundleValidatorTest.setUp(BundleValidatorTest.java:30)

[INFO] Running com.iota.iri.conf.ConfigurationTest
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 s - in com.iota.iri.conf.ConfigurationTest
[INFO] Running com.iota.iri.controllers.BundleViewModelTest
07/29 03:05:52.756 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
07/29 03:05:52.760 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
07/29 03:05:52.765 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
07/29 03:05:52.769 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
07/29 03:05:52.773 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
[ERROR] Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.007 s <<< FAILURE! - in com.iota.iri.controllers.BundleViewModelTest
[ERROR] quietGetTail(com.iota.iri.controllers.BundleViewModelTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.controllers.BundleViewModelTest.setUp(BundleViewModelTest.java:26)

[ERROR] fromHash(com.iota.iri.controllers.BundleViewModelTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.controllers.BundleViewModelTest.setUp(BundleViewModelTest.java:26)

[ERROR] getTail(com.iota.iri.controllers.BundleViewModelTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.controllers.BundleViewModelTest.setUp(BundleViewModelTest.java:26)

[ERROR] quietFromHash(com.iota.iri.controllers.BundleViewModelTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.controllers.BundleViewModelTest.setUp(BundleViewModelTest.java:26)

[ERROR] getTransactionViewModels(com.iota.iri.controllers.BundleViewModelTest)  Time elapsed: 0.002 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.controllers.BundleViewModelTest.setUp(BundleViewModelTest.java:26)

[INFO] Running com.iota.iri.controllers.MilestoneViewModelTest
07/29 03:05:52.783 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
07/29 03:05:52.787 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
07/29 03:05:52.891 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
07/29 03:05:52.904 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
07/29 03:05:52.909 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
07/29 03:05:52.925 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
07/29 03:05:52.935 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
07/29 03:05:52.942 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
07/29 03:05:52.947 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
07/29 03:05:52.960 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
07/29 03:05:52.965 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
07/29 03:05:52.990 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
07/29 03:05:53.003 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
07/29 03:05:53.013 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
07/29 03:05:53.020 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
07/29 03:05:53.031 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
[ERROR] Tests run: 16, Failures: 0, Errors: 16, Skipped: 0, Time elapsed: 0.12 s <<< FAILURE! - in com.iota.iri.controllers.MilestoneViewModelTest
[ERROR] initSnapshot(com.iota.iri.controllers.MilestoneViewModelTest)  Time elapsed: 0.002 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.controllers.MilestoneViewModelTest.setUpTest(MilestoneViewModelTest.java:28)

[ERROR] nextGreaterThan(com.iota.iri.controllers.MilestoneViewModelTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.controllers.MilestoneViewModelTest.setUpTest(MilestoneViewModelTest.java:28)

[ERROR] previous(com.iota.iri.controllers.MilestoneViewModelTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.controllers.MilestoneViewModelTest.setUpTest(MilestoneViewModelTest.java:28)

[ERROR] latest(com.iota.iri.controllers.MilestoneViewModelTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.controllers.MilestoneViewModelTest.setUpTest(MilestoneViewModelTest.java:28)

[ERROR] getMilestone(com.iota.iri.controllers.MilestoneViewModelTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.controllers.MilestoneViewModelTest.setUpTest(MilestoneViewModelTest.java:28)

[ERROR] latestSnapshot(com.iota.iri.controllers.MilestoneViewModelTest)  Time elapsed: 0.007 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.controllers.MilestoneViewModelTest.setUpTest(MilestoneViewModelTest.java:28)

[ERROR] firstWithSnapshot(com.iota.iri.controllers.MilestoneViewModelTest)  Time elapsed: 0.008 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.controllers.MilestoneViewModelTest.setUpTest(MilestoneViewModelTest.java:28)

[ERROR] getHash(com.iota.iri.controllers.MilestoneViewModelTest)  Time elapsed: 0.012 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.controllers.MilestoneViewModelTest.setUpTest(MilestoneViewModelTest.java:28)

[ERROR] next(com.iota.iri.controllers.MilestoneViewModelTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.controllers.MilestoneViewModelTest.setUpTest(MilestoneViewModelTest.java:28)

[ERROR] nextWithSnapshot(com.iota.iri.controllers.MilestoneViewModelTest)  Time elapsed: 0.043 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.controllers.MilestoneViewModelTest.setUpTest(MilestoneViewModelTest.java:28)

[ERROR] first(com.iota.iri.controllers.MilestoneViewModelTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.controllers.MilestoneViewModelTest.setUpTest(MilestoneViewModelTest.java:28)

[ERROR] index(com.iota.iri.controllers.MilestoneViewModelTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.controllers.MilestoneViewModelTest.setUpTest(MilestoneViewModelTest.java:28)

[ERROR] store(com.iota.iri.controllers.MilestoneViewModelTest)  Time elapsed: 0.011 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.controllers.MilestoneViewModelTest.setUpTest(MilestoneViewModelTest.java:28)

[ERROR] snapshot(com.iota.iri.controllers.MilestoneViewModelTest)  Time elapsed: 0.019 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.controllers.MilestoneViewModelTest.setUpTest(MilestoneViewModelTest.java:28)

[ERROR] PrevBefore(com.iota.iri.controllers.MilestoneViewModelTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.controllers.MilestoneViewModelTest.setUpTest(MilestoneViewModelTest.java:28)

[ERROR] updateSnapshot(com.iota.iri.controllers.MilestoneViewModelTest)  Time elapsed: 0.007 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.controllers.MilestoneViewModelTest.setUpTest(MilestoneViewModelTest.java:28)

[INFO] Running com.iota.iri.controllers.TagViewModelTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in com.iota.iri.controllers.TagViewModelTest
[INFO] Running com.iota.iri.controllers.TipsViewModelTest
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.419 s - in com.iota.iri.controllers.TipsViewModelTest
[INFO] Running com.iota.iri.controllers.TransactionRequesterTest
[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.681 s - in com.iota.iri.controllers.TransactionRequesterTest
[INFO] Running com.iota.iri.controllers.TransactionViewModelTest
07/29 03:05:54.221 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.013 s <<< FAILURE! - in com.iota.iri.controllers.TransactionViewModelTest
[ERROR] com.iota.iri.controllers.TransactionViewModelTest  Time elapsed: 0.012 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.controllers.TransactionViewModelTest.setUp(TransactionViewModelTest.java:35)

[INFO] Running com.iota.iri.hash.CurlTest
549289149
14527045
37
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.898 s - in com.iota.iri.hash.CurlTest
[INFO] Running com.iota.iri.hash.ISSTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.248 s - in com.iota.iri.hash.ISSTest
[INFO] Running com.iota.iri.hash.KerlTest
0 iteration: 7161062796154924679510263884351976746646584363262279752765042781340751417733492663251975868529798034798702195113766
1000 iteration: 892195128229512285607220612765404308825830095643217259836429472393160294638332215713833873531180991814834173936820
2000 iteration: 7379681735270339046998922748551842021817572572588594738906388746738863519750105310767181435086242007845505447957027
3000 iteration: -6207478026600144464912228685037143927969426523416595525231588313536419293089521744813468471310470304924659289891710
4000 iteration: -14199212770223000534354805113490397162056729589386549653145251134845232928302747297114264273343611756894775032719882
5000 iteration: 3610343434619569794630423469658949071153997714856141876089569155154128765791701774190959322058893886965335708505255
6000 iteration: -14453522999607881751799419514897335075625385592472435495086313569082425888477384241336384569275796519065181599103064
7000 iteration: 10107382641446682278918615783842521834535555725793998336484353003350588173564058899667508308728224471562858773893067
8000 iteration: -5714187499421609454709456020076391012093067076441169858800932443758657316142711373267482089457915754325495040257898
9000 iteration: 12777123412526326157082706408680512477219575640170874908423601017533901266387997530287553613552828852126796098733871
0 iteration: 15531730876026057244011385198964458665870993614369674489447837370209937102793466998438479129197530743776790418922380
1000 iteration: -5413085648529849007086902989999101281874700763165752089853365459922178921715254868112597714189721518603301863255986
2000 iteration: 10930475005554643557758909905083472560937751375000212025582521596612687885088173544924913412082575599213563956338361
3000 iteration: -5508239348667616268529828889941930475989693892263684881244741183979886209400849493002618586167066940306902738193869
4000 iteration: -6724236503712528873075014256792888490808306406364122740618705780719867981616303974190326736350782956313646006147490
5000 iteration: 15751531645071805100737958222890371617495432008741350897603033029641427563848493970001019991558803449673214909360069
6000 iteration: -8086881805392674055496754832834869648148710745520848884394552737303745605763251597373797409939278209247779488540714
7000 iteration: 9079627883877003302133221655209533831592885812676392313057940695296240008738892463585152909722476869421113310247117
8000 iteration: -3020799520416598668455911534383509367119288563613711205780215062193581375792562463366454896298479910723780587204373
9000 iteration: 3879922415123448268045496169883966970309424393531594523508870067143468063519205372722686711780273504383260007075473
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.255 s - in com.iota.iri.hash.KerlTest
[INFO] Running com.iota.iri.hash.PearlDiverTest
[WARNING] Tests run: 5, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.208 s - in com.iota.iri.hash.PearlDiverTest
[INFO] Running com.iota.iri.IXITest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.106 s - in com.iota.iri.IXITest
[INFO] Running com.iota.iri.model.HashTest
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.094 s - in com.iota.iri.model.HashTest
[INFO] Running com.iota.iri.service.tipselection.impl.CumulativeWeightCalculatorTest
07/29 03:06:02.088 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.008 s <<< FAILURE! - in com.iota.iri.service.tipselection.impl.CumulativeWeightCalculatorTest
[ERROR] com.iota.iri.service.tipselection.impl.CumulativeWeightCalculatorTest  Time elapsed: 0.008 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.service.tipselection.impl.CumulativeWeightCalculatorTest.setUp(CumulativeWeightCalculatorTest.java:45)

[INFO] Running com.iota.iri.service.tipselection.impl.EntryPointSelectorImplTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.657 s - in com.iota.iri.service.tipselection.impl.EntryPointSelectorImplTest
[INFO] Running com.iota.iri.service.tipselection.impl.RatingOneTest
07/29 03:06:02.765 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.002 s <<< FAILURE! - in com.iota.iri.service.tipselection.impl.RatingOneTest
[ERROR] com.iota.iri.service.tipselection.impl.RatingOneTest  Time elapsed: 0.002 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.service.tipselection.impl.RatingOneTest.setUp(RatingOneTest.java:39)

[INFO] Running com.iota.iri.service.tipselection.impl.TailFinderImplTest
07/29 03:06:02.795 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.007 s <<< FAILURE! - in com.iota.iri.service.tipselection.impl.TailFinderImplTest
[ERROR] com.iota.iri.service.tipselection.impl.TailFinderImplTest  Time elapsed: 0.006 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.service.tipselection.impl.TailFinderImplTest.setUp(TailFinderImplTest.java:41)

[INFO] Running com.iota.iri.service.tipselection.impl.WalkerAlphaTest
07/29 03:06:02.808 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in com.iota.iri.service.tipselection.impl.WalkerAlphaTest
[ERROR] com.iota.iri.service.tipselection.impl.WalkerAlphaTest  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.service.tipselection.impl.WalkerAlphaTest.setUp(WalkerAlphaTest.java:45)

[INFO] Running com.iota.iri.service.tipselection.impl.WalkValidatorImplTest
07/29 03:06:02.839 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.027 s <<< FAILURE! - in com.iota.iri.service.tipselection.impl.WalkValidatorImplTest
[ERROR] com.iota.iri.service.tipselection.impl.WalkValidatorImplTest  Time elapsed: 0.021 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.service.tipselection.impl.WalkValidatorImplTest.setUp(WalkValidatorImplTest.java:52)

[ERROR] com.iota.iri.service.tipselection.impl.WalkValidatorImplTest  Time elapsed: 0.026 s  <<< ERROR!
java.lang.NullPointerException
	at com.iota.iri.service.tipselection.impl.WalkValidatorImplTest.tearDown(WalkValidatorImplTest.java:43)

[INFO] Running com.iota.iri.SnapshotTest
07/29 03:06:14.133 [main] INFO  com.iota.iri.Snapshot - Skipping negative value for address: ESRQPWWIECDGDDZEHGJNMEVJNSVOSMECPPVRPEVRZFVIZYNNXZNTOTJOZNGCZNQVSPXBXTYUJUOXYASLS: -100
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.308 s - in com.iota.iri.SnapshotTest
[INFO] Running com.iota.iri.storage.TangleTest
07/29 03:06:14.185 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
07/29 03:06:14.194 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
07/29 03:06:14.203 [main] INFO  com.iota.iri.storage.Tangle - Shutting down Tangle Persistence Providers... 
[ERROR] Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.024 s <<< FAILURE! - in com.iota.iri.storage.TangleTest
[ERROR] get(com.iota.iri.storage.TangleTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.storage.TangleTest.setUp(TangleTest.java:31)

[ERROR] save(com.iota.iri.storage.TangleTest)  Time elapsed: 0.009 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.storage.TangleTest.setUp(TangleTest.java:31)

[ERROR] getKeysStartingWithValue(com.iota.iri.storage.TangleTest)  Time elapsed: 0.009 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.storage.TangleTest.setUp(TangleTest.java:31)

[INFO] Running com.iota.iri.TransactionValidatorTest
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in com.iota.iri.TransactionValidatorTest
[ERROR] com.iota.iri.TransactionValidatorTest  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.TransactionValidatorTest.setUp(TransactionValidatorTest.java:39)

[ERROR] com.iota.iri.TransactionValidatorTest  Time elapsed: 0 s  <<< ERROR!
java.lang.NullPointerException
	at com.iota.iri.TransactionValidatorTest.tearDown(TransactionValidatorTest.java:51)

[INFO] Running com.iota.iri.utils.BoundedHashSetTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.01 s - in com.iota.iri.utils.BoundedHashSetTest
[INFO] Running com.iota.iri.utils.collections.impl.BoundedSetWrapperTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.021 s - in com.iota.iri.utils.collections.impl.BoundedSetWrapperTest
[INFO] Running com.iota.iri.utils.TestSerializer
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in com.iota.iri.utils.TestSerializer
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   BundleValidatorTest.setUp:30 » UnsatisfiedLink C:\Users\ai.ai-PC\AppData\Local...
[ERROR] com.iota.iri.TransactionValidatorTest.com.iota.iri.TransactionValidatorTest
[ERROR]   Run 1: TransactionValidatorTest.setUp:39 » NoClassDefFound Could not initialize class...
[ERROR]   Run 2: TransactionValidatorTest.tearDown:51 NullPointer
[INFO] 
[ERROR]   BundleViewModelTest.setUp:26 » NoClassDefFound Could not initialize class org....
[ERROR]   BundleViewModelTest.setUp:26 » NoClassDefFound Could not initialize class org....
[ERROR]   BundleViewModelTest.setUp:26 » NoClassDefFound Could not initialize class org....
[ERROR]   BundleViewModelTest.setUp:26 » NoClassDefFound Could not initialize class org....
[ERROR]   BundleViewModelTest.setUp:26 » NoClassDefFound Could not initialize class org....
[ERROR]   MilestoneViewModelTest.setUpTest:28 » NoClassDefFound Could not initialize cla...
[ERROR]   MilestoneViewModelTest.setUpTest:28 » NoClassDefFound Could not initialize cla...
[ERROR]   MilestoneViewModelTest.setUpTest:28 » NoClassDefFound Could not initialize cla...
[ERROR]   MilestoneViewModelTest.setUpTest:28 » NoClassDefFound Could not initialize cla...
[ERROR]   MilestoneViewModelTest.setUpTest:28 » NoClassDefFound Could not initialize cla...
[ERROR]   MilestoneViewModelTest.setUpTest:28 » NoClassDefFound Could not initialize cla...
[ERROR]   MilestoneViewModelTest.setUpTest:28 » NoClassDefFound Could not initialize cla...
[ERROR]   MilestoneViewModelTest.setUpTest:28 » NoClassDefFound Could not initialize cla...
[ERROR]   MilestoneViewModelTest.setUpTest:28 » NoClassDefFound Could not initialize cla...
[ERROR]   MilestoneViewModelTest.setUpTest:28 » NoClassDefFound Could not initialize cla...
[ERROR]   MilestoneViewModelTest.setUpTest:28 » NoClassDefFound Could not initialize cla...
[ERROR]   MilestoneViewModelTest.setUpTest:28 » NoClassDefFound Could not initialize cla...
[ERROR]   MilestoneViewModelTest.setUpTest:28 » NoClassDefFound Could not initialize cla...
[ERROR]   MilestoneViewModelTest.setUpTest:28 » NoClassDefFound Could not initialize cla...
[ERROR]   MilestoneViewModelTest.setUpTest:28 » NoClassDefFound Could not initialize cla...
[ERROR]   MilestoneViewModelTest.setUpTest:28 » NoClassDefFound Could not initialize cla...
[ERROR]   TransactionViewModelTest.setUp:35 » NoClassDefFound Could not initialize class...
[ERROR]   CumulativeWeightCalculatorTest.setUp:45 » NoClassDefFound Could not initialize...
[ERROR]   RatingOneTest.setUp:39 » NoClassDefFound Could not initialize class org.rocksd...
[ERROR]   TailFinderImplTest.setUp:41 » NoClassDefFound Could not initialize class org.r...
[ERROR] com.iota.iri.service.tipselection.impl.WalkValidatorImplTest.com.iota.iri.service.tipselection.impl.WalkValidatorImplTest
[ERROR]   Run 1: WalkValidatorImplTest.setUp:52 » NoClassDefFound Could not initialize class or...
[ERROR]   Run 2: WalkValidatorImplTest.tearDown:43 NullPointer
[INFO] 
[ERROR]   WalkerAlphaTest.setUp:45 » NoClassDefFound Could not initialize class org.rock...
[ERROR]   TangleTest.setUp:31 » NoClassDefFound Could not initialize class org.rocksdb.R...
[ERROR]   TangleTest.setUp:31 » NoClassDefFound Could not initialize class org.rocksdb.R...
[ERROR]   TangleTest.setUp:31 » NoClassDefFound Could not initialize class org.rocksdb.R...
[INFO] 
[ERROR] Tests run: 112, Failures: 0, Errors: 32, Skipped: 1
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30.930 s
[INFO] Finished at: 2018-07-29T03:06:14+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project iri: There are test failures.
[ERROR] 
[ERROR] Please refer to C:\prj\iri\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```

**Comment by rajivshah3** [comment]
Since you're running Windows, it might be something wrong with RocksDB or a dependency. You could try solutions mentioned in https://github.com/iotaledger/iri/issues/350
